#include <machine.h>
#include "types.h"
#include "ASM.h"

void font_x_swap()
{
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	CX,0x0008");
ASM_INLINE("_82B22:");
	ASM_INLINE("RCL	AH,1");
	ASM_INLINE("RCR	BH,1");
	ASM_INLINE("RCL	AL,1");
	ASM_INLINE("RCR	BL,1");
	ASM_INLINE("LOOP	_82B22");
	ASM_INLINE("POP	CX");
	ASM_INLINE("MOV	AX,BX");
}

void font_put2_sub()
{
	ASM_INLINE("PUSH	BP");
	ASM_INLINE("MOV	BP,SP");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("PUSH	DS");
	ASM_INLINE("MOV	DS,BX");
	ASM_INLINE("MOV	SI,AX");
	ASM_INLINE("MOV	ES,DX");
	ASM_INLINE("MOV	DI,CX");
	ASM_INLINE("MOV	CX,0x0008");
	ASM_INLINE("TEST	[BP+0x06].W,0x8000");
	ASM_INLINE("JNZ	_82B4C");
	//ASM_INLINE("JMP	_82B81");
	ASM_OP3(0xE9,0x35,0x00);
ASM_INLINE("_82B4C:");
	ASM_INLINE("TEST	[BP+0x06].W,0x4000");
	ASM_INLINE("JNZ	_82B56");
	//ASM_INLINE("JMP	_82B6E");
	ASM_OP3(0xE9,0x18,0x00);
ASM_INLINE("_82B56:");
	ASM_INLINE("ADD	SI,0x000E");
ASM_INLINE("_82B59:");
	ASM_INLINE("MOV	AX,[SI].W");
	ASM_INLINE("CALLF	font_x_swap_, SEG font_x_swap_");
	ASM_INLINE("MOV	ES:[DI].W,AX");
	ASM_INLINE("SUB	SI,0x0002");
	ASM_INLINE("ADD	DI,0x0002");
	ASM_INLINE("LOOP	_82B59");
	//ASM_INLINE("JMP	_82BA6");
	ASM_OP3(0xE9,0x38,0x00);
ASM_INLINE("_82B6E:");
	ASM_INLINE("ADD	SI,0x000E");
ASM_INLINE("_82B71:");
	ASM_INLINE("MOV	AX,[SI].W");
	ASM_INLINE("MOV	ES:[DI].W,AX");
	ASM_INLINE("SUB	SI,0x0002");
	ASM_INLINE("ADD	DI,0x0002");
	ASM_INLINE("LOOP	_82B71");
	//ASM_INLINE("JMP	_82BA6");
	ASM_OP3(0xE9,0x25,0x00);
ASM_INLINE("_82B81:");
	ASM_INLINE("TEST	[BP+0x06].W,0x4000");
	ASM_INLINE("JNZ	_82B8B");
	//ASM_INLINE("JMP	_82BA0");
	ASM_OP3(0xE9,0x15,0x00);
ASM_INLINE("_82B8B:");
	ASM_INLINE("MOV	AX,[SI].W");
	ASM_INLINE("CALLF	font_x_swap_, SEG font_x_swap_");
	ASM_INLINE("MOV	ES:[DI].W,AX");
	ASM_INLINE("ADD	SI,0x0002");
	ASM_INLINE("ADD	DI,0x0002");
	ASM_INLINE("LOOP	_82B8B");
	//ASM_INLINE("JMP	_82BA6");
	ASM_OP3(0xE9,0x06,0x00);
ASM_INLINE("_82BA0:");
	ASM_INLINE("MOV	CX,0x0008");
	ASM_INLINE("CLD");
	ASM_INLINE("REP MOVSW");
ASM_INLINE("_82BA6:");
	ASM_INLINE("POP	DS");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	CX");
	ASM_INLINE("POP	BP");
}
