#include <machine.h>
#include "types.h"
#include "func_tbl.h"

const u16 far functbl[][8] = {
    { 0x0000, 0x0002, 0x0000, 0x0000, 0x0000, 0x0000, 0x0100, 0x000F },
    { 0x0001, 0x0002, 0x0101, 0x0101, 0x0001, 0x0000, 0x0100, 0x0012 },
    { 0x0001, 0x0001, 0x0100, 0x0100, 0x0001, 0x0000, 0x0100, 0x0012 },
    { 0x0001, 0x0003, 0x0102, 0x0102, 0x0001, 0x0000, 0x0100, 0x0014 },
    { 0x0002, 0x0003, 0x0102, 0x0105, 0x0007, 0x0001, 0x0100, 0x0015 },
    { 0x0002, 0x0005, 0x0103, 0x0107, 0x0007, 0x0003, 0x0101, 0x0014 },
    { 0x0002, 0x0004, 0x0105, 0x0108, 0x0004, 0x0001, 0x0102, 0x0015 },
    { 0x0002, 0x0004, 0x0101, 0x0107, 0x0006, 0x0002, 0x0103, 0x0014 },
    { 0x0002, 0x0002, 0x0102, 0x0107, 0x0005, 0x0001, 0x0104, 0x0015 },
    { 0x0002, 0x0005, 0x0102, 0x0108, 0x0004, 0x0003, 0x0105, 0x0014 },
    { 0x0002, 0x0007, 0x0103, 0x0103, 0x0005, 0x0001, 0x0106, 0x0015 },
    { 0x0002, 0x000A, 0x0100, 0x0102, 0x0004, 0x0002, 0x0107, 0x0014 },
    { 0x0002, 0x000F, 0x0103, 0x0100, 0x0007, 0x0001, 0x0108, 0x0015 },
    { 0x0002, 0x000F, 0x0102, 0x0101, 0x0006, 0x0001, 0x0109, 0x0014 },
    { 0x0002, 0x000C, 0x0105, 0x0104, 0x0004, 0x0001, 0x010A, 0x0015 },
    { 0x0003, 0x0019, 0x0103, 0x0108, 0x0000, 0x0000, 0x0100, 0x0018 },
    { 0x0003, 0x0004, 0x0000, 0x0000, 0x0000, 0x0000, 0x0100, 0x0018 },
    { 0x0003, 0x0007, 0x0000, 0x0000, 0x0000, 0x0000, 0x0100, 0x001A },
    { 0x0003, 0x0007, 0x0100, 0x0105, 0x0004, 0x0000, 0x0100, 0x0019 },
    { 0x0003, 0x0002, 0x0103, 0x0100, 0x0004, 0x0000, 0x0100, 0x001A },
    { 0x0003, 0x0007, 0x0103, 0x0108, 0x0000, 0x0000, 0x0100, 0x001B },
    { 0x0003, 0x000A, 0x0103, 0x0108, 0x0004, 0x0000, 0x0100, 0x001A },
    { 0x0002, 0x0005, 0x0106, 0x0108, 0x0004, 0x0003, 0x0100, 0x0015 },
    { 0x0002, 0x000F, 0x0102, 0x0103, 0x0004, 0x0003, 0x010A, 0x0018 },
    { 0x0002, 0x0014, 0x0101, 0x0104, 0x0004, 0x0003, 0x010B, 0x0018 },
    { 0x0200, 0x0200, 0x0200, 0x0200, 0x0200, 0x0200, 0x0200, 0x0200 }
};

const u16 far tuneup_table[][6] = {
    { 0x000A, 0x000F, 0x000C, 0x000C, 0x000F, 0x0014 },
    { 0x0001, 0x0003, 0x0002, 0x0001, 0x0002, 0x0005 },
    { 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000 },
    { 0x000A, 0x000C, 0x000C, 0x0008, 0x000A, 0x000F },
    { 0x0000, 0x000C, 0x0000, 0x000C, 0x000E, 0x0000 },
    { 0x0012, 0x0000, 0x0012, 0x0000, 0x0000, 0x0000 },
    { 0x0012, 0x0000, 0x0000, 0x0014, 0x0000, 0x0000 },
    { 0x0000, 0x0012, 0x0000, 0x0000, 0x0000, 0x0000 },
    { 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000 },
    { 0x0000, 0x0014, 0x0000, 0x0000, 0x0000, 0x0014 },
    { 0x0000, 0x0012, 0x0000, 0x0014, 0x0000, 0x0000 },
    { 0x0000, 0x0000, 0x001C, 0x0000, 0x0000, 0x0000 },
    { 0x0018, 0x0000, 0x0000, 0x0014, 0x0000, 0x0000 },
    { 0x0018, 0x0000, 0x0018, 0x0000, 0x0000, 0x001C },
    { 0x0000, 0x0000, 0x0000, 0x0018, 0x0000, 0x0000 },
    { 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000 },
    { 0x000A, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000 },
    { 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000 },
    { 0x0000, 0x000A, 0x0000, 0x0000, 0x000A, 0x0000 },
    { 0x0000, 0x0000, 0x0000, 0x0000, 0x000A, 0x0000 },
    { 0x0000, 0x0000, 0x0014, 0x0000, 0x0012, 0x0000 },
    { 0x0000, 0x0000, 0x0000, 0x000F, 0x0000, 0x0000 },
    { 0x0000, 0x0000, 0x0012, 0x0000, 0x0000, 0x0000 },
    { 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000 },
    { 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000 },
    { 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF }
};

static const char far weapon_name00[] = "MOVE   ";
static const char far weapon_name01[] = "SONOR  ";
static const char far weapon_name02[] = "SENSOR ";
static const char far weapon_name03[] = "RADAR  ";
static const char far weapon_name04[] = "VULCAN ";
static const char far weapon_name05[] = "A-RIFLE";
static const char far weapon_name06[] = "LASER  ";
static const char far weapon_name07[] = "RAILGUN";
static const char far weapon_name08[] = "H-GUN  ";
static const char far weapon_name09[] = "BLAST  ";
static const char far weapon_name10[] = "STUN-G ";
static const char far weapon_name11[] = "MISSILE";
static const char far weapon_name12[] = "SPREAD ";
static const char far weapon_name13[] = "HEAVY-G";
static const char far weapon_name14[] = "SPIRAL ";
static const char far weapon_name15[] = "WARP   ";
static const char far weapon_name16[] = "BOOSTER";
static const char far weapon_name17[] = "E-FIELD";
static const char far weapon_name18[] = "JAMMER ";
static const char far weapon_name19[] = "FLASH  ";
static const char far weapon_name20[] = "DECOY  ";
static const char far weapon_name21[] = "PAINT  ";
static const char far weapon_name22[] = "HUMMER ";
static const char far weapon_name23[] = "PHOTON ";
static const char far weapon_name24[] = "PHITHER";

const char far * far weapon_name[] =
{
    weapon_name00,
    weapon_name01,
    weapon_name02,
    weapon_name03,
    weapon_name04,
    weapon_name05,
    weapon_name06,
    weapon_name07,
    weapon_name08,
    weapon_name09,
    weapon_name10,
    weapon_name11,
    weapon_name12,
    weapon_name13,
    weapon_name14,
    weapon_name15,
    weapon_name16,
    weapon_name17,
    weapon_name18,
    weapon_name19,
    weapon_name20,
    weapon_name21,
    weapon_name22,
    weapon_name23,
    weapon_name24,
};

const struct MAUData far aulist[] = {
    /* SHUNER */
    {
        /* type */   TYPE_KNIGHT,
        /* unk01 */  0,
        /* hp */     8,
        /* en */     20,
        /* tp */     20,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_SONOR,
        /* move */   WEAPON_VULCAN,
        /* move */   WEAPON_STUN_G,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  1,
        /* unk0E */  0,
    },
    /* WELG */
    {
        /* type */   TYPE_KNIGHT,
        /* unk01 */  0,
        /* hp */     7,
        /* en */     25,
        /* tp */     20,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_SONOR,
        /* move */   WEAPON_RAILGUN,
        /* move */   WEAPON_SPREAD,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  1,
        /* unk0E */  0,
    },
    /* ORNET */
    {
        /* type */   TYPE_INSECT,
        /* unk01 */  0,
        /* hp */     5,
        /* en */     35,
        /* tp */     20,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_A_RIFLE,
        /* move */   WEAPON_STUN_G,
        /* move */   WEAPON_WARP,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  1,
        /* unk0E */  0,
    },
    /* BEETZ */
    {
        /* type */   TYPE_INSECT,
        /* unk01 */  0,
        /* hp */     5,
        /* en */     35,
        /* tp */     20,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_SONOR,
        /* move */   WEAPON_A_RIFLE,
        /* move */   WEAPON_BOOSTER,
        /* move */   WEAPON_HUMMER,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  1,
        /* unk0E */  0,
    },
    /* ROID */
    {
        /* type */   TYPE_ROOK,
        /* unk01 */  0,
        /* hp */     6,
        /* en */     35,
        /* tp */     20,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_SENSOR,
        /* move */   WEAPON_BLAST,
        /* move */   WEAPON_MISSILE,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  1,
        /* unk0E */  0,
    },
    /* MONO */
    {
        /* type */   TYPE_SEEKER,
        /* unk01 */  0,
        /* hp */     7,
        /* en */     30,
        /* tp */     20,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_RADAR,
        /* move */   WEAPON_LASER,
        /* move */   WEAPON_HUMMER,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  1,
        /* unk0E */  0,
    },
    /* BLINK */
    {
        /* type */   TYPE_SEEKER,
        /* unk01 */  0,
        /* hp */     5,
        /* en */     30,
        /* tp */     20,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_RADAR,
        /* move */   WEAPON_A_RIFLE,
        /* move */   WEAPON_STUN_G,
        /* move */   WEAPON_DECOY,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  1,
        /* unk0E */  0,
    },
    /* CANAVIS */
    {
        /* type */   TYPE_RANGER,
        /* unk01 */  0,
        /* hp */     6,
        /* en */     30,
        /* tp */     20,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_SONOR,
        /* move */   WEAPON_LASER,
        /* move */   WEAPON_JAMMER,
        /* move */   WEAPON_PAINT,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  1,
        /* unk0E */  0,
    },
    /* ORG */
    {
        /* type */   TYPE_ROOK,
        /* unk01 */  0,
        /* hp */     8,
        /* en */     30,
        /* tp */     20,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_SENSOR,
        /* move */   WEAPON_LASER,
        /* move */   WEAPON_MISSILE,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  1,
        /* unk0E */  0,
    },
    /* M_DOWN */
    {
        /* type */   TYPE_ROOK,
        /* unk01 */  0,
        /* hp */     5,
        /* en */     40,
        /* tp */     20,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_RADAR,
        /* move */   WEAPON_RAILGUN,
        /* move */   WEAPON_MISSILE,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  1,
        /* unk0E */  0,
    },
    /* GAZE */
    {
        /* type */   TYPE_SEEKER,
        /* unk01 */  0,
        /* hp */     6,
        /* en */     25,
        /* tp */     20,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_RADAR,
        /* move */   WEAPON_VULCAN,
        /* move */   WEAPON_SPIRAL,
        /* move */   WEAPON_FLASH,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  1,
        /* unk0E */  0,
    },
    /* HYUMN */
    {
        /* type */   TYPE_RANGER,
        /* unk01 */  0,
        /* hp */     5,
        /* en */     30,
        /* tp */     20,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_SENSOR,
        /* move */   WEAPON_RAILGUN,
        /* move */   WEAPON_DECOY,
        /* move */   WEAPON_HUMMER,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  1,
        /* unk0E */  0,
    },
    /* SOLID */
    {
        /* type */   TYPE_PROTO,
        /* unk01 */  0,
        /* hp */     9,
        /* en */     45,
        /* tp */     20,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_SENSOR,
        /* move */   WEAPON_H_GUN,
        /* move */   WEAPON_JAMMER,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  1,
        /* unk0E */  0,
    },
    /* MOLTH */
    {
        /* type */   TYPE_INSECT,
        /* unk01 */  0,
        /* hp */     5,
        /* en */     35,
        /* tp */     20,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_SONOR,
        /* move */   WEAPON_LASER,
        /* move */   WEAPON_E_FIELD,
        /* move */   WEAPON_JAMMER,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  3,
        /* unk0E */  10,
    },
    /* DINGO */
    {
        /* type */   TYPE_RANGER,
        /* unk01 */  0,
        /* hp */     7,
        /* en */     25,
        /* tp */     20,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_SENSOR,
        /* move */   WEAPON_VULCAN,
        /* move */   WEAPON_MISSILE,
        /* move */   WEAPON_PAINT,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  3,
        /* unk0E */  11,
    },
    /* HOUND */
    {
        /* type */   TYPE_KNIGHT,
        /* unk01 */  0,
        /* hp */     7,
        /* en */     25,
        /* tp */     0,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_SONOR,
        /* move */   WEAPON_SPREAD,
        /* move */   WEAPON_WARP,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  2,
        /* unk0E */  13,
    },
    /* GLID */
    {
        /* type */   TYPE_KNIGHT,
        /* unk01 */  0,
        /* hp */     6,
        /* en */     30,
        /* tp */     0,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_SONOR,
        /* move */   WEAPON_STUN_G,
        /* move */   WEAPON_HEAVY_G,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  2,
        /* unk0E */  13,
    },
    /* APHEX */
    {
        /* type */   TYPE_KNIGHT,
        /* unk01 */  0,
        /* hp */     7,
        /* en */     25,
        /* tp */     0,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_SONOR,
        /* move */   WEAPON_LASER,
        /* move */   WEAPON_SPIRAL,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  2,
        /* unk0E */  12,
    },
    /* HOPER */
    {
        /* type */   TYPE_INSECT,
        /* unk01 */  0,
        /* hp */     5,
        /* en */     30,
        /* tp */     0,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_SENSOR,
        /* move */   WEAPON_RAILGUN,
        /* move */   WEAPON_HEAVY_G,
        /* move */   WEAPON_E_FIELD,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  2,
        /* unk0E */  12,
    },
    /* CICADE */
    {
        /* type */   TYPE_INSECT,
        /* unk01 */  0,
        /* hp */     5,
        /* en */     30,
        /* tp */     0,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_SENSOR,
        /* move */   WEAPON_MISSILE,
        /* move */   WEAPON_E_FIELD,
        /* move */   WEAPON_JAMMER,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  2,
        /* unk0E */  8,
    },
    /* ROGUE */
    {
        /* type */   TYPE_ROOK,
        /* unk01 */  0,
        /* hp */     7,
        /* en */     30,
        /* tp */     0,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_SONOR,
        /* move */   WEAPON_BLAST,
        /* move */   WEAPON_SPREAD,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  2,
        /* unk0E */  13,
    },
    /* MUSHA */
    {
        /* type */   TYPE_ROOK,
        /* unk01 */  0,
        /* hp */     8,
        /* en */     35,
        /* tp */     0,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_SENSOR,
        /* move */   WEAPON_MISSILE,
        /* move */   WEAPON_HUMMER,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  2,
        /* unk0E */  9,
    },
    /* RENS */
    {
        /* type */   TYPE_SEEKER,
        /* unk01 */  0,
        /* hp */     6,
        /* en */     25,
        /* tp */     0,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_SONOR,
        /* move */   WEAPON_SENSOR,
        /* move */   WEAPON_LASER,
        /* move */   WEAPON_PAINT,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  2,
        /* unk0E */  10,
    },
    /* PSY_O */
    {
        /* type */   TYPE_SEEKER,
        /* unk01 */  0,
        /* hp */     5,
        /* en */     25,
        /* tp */     0,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_RADAR,
        /* move */   WEAPON_A_RIFLE,
        /* move */   WEAPON_E_FIELD,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  2,
        /* unk0E */  8,
    },
    /* SILVER */
    {
        /* type */   TYPE_RANGER,
        /* unk01 */  0,
        /* hp */     5,
        /* en */     40,
        /* tp */     0,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_SONOR,
        /* move */   WEAPON_STUN_G,
        /* move */   WEAPON_FLASH,
        /* move */   WEAPON_HUMMER,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  2,
        /* unk0E */  9,
    },
    /* ELVEN */
    {
        /* type */   TYPE_RANGER,
        /* unk01 */  0,
        /* hp */     7,
        /* en */     20,
        /* tp */     0,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_SENSOR,
        /* move */   WEAPON_MISSILE,
        /* move */   WEAPON_E_FIELD,
        /* move */   WEAPON_DECOY,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  2,
        /* unk0E */  8,
    },
    /* ZERO */
    {
        /* type */   TYPE_PROTO,
        /* unk01 */  0,
        /* hp */     6,
        /* en */     30,
        /* tp */     0,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_SENSOR,
        /* move */   WEAPON_RAILGUN,
        /* move */   WEAPON_STUN_G,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  2,
        /* unk0E */  11,
    },
    /* DEPT */
    {
        /* type */   TYPE_KNIGHT,
        /* unk01 */  0,
        /* hp */     8,
        /* en */     20,
        /* tp */     0,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_SONOR,
        /* move */   WEAPON_LASER,
        /* move */   WEAPON_STUN_G,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  2,
        /* unk0E */  11,
    },
    /* CONFU */
    {
        /* type */   TYPE_KNIGHT,
        /* unk01 */  0,
        /* hp */     7,
        /* en */     25,
        /* tp */     0,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_SONOR,
        /* move */   WEAPON_STUN_G,
        /* move */   WEAPON_HEAVY_G,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  2,
        /* unk0E */  13,
    },
    /* FLEA */
    {
        /* type */   TYPE_INSECT,
        /* unk01 */  0,
        /* hp */     4,
        /* en */     40,
        /* tp */     0,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_SONOR,
        /* move */   WEAPON_LASER,
        /* move */   WEAPON_BOOSTER,
        /* move */   WEAPON_E_FIELD,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  2,
        /* unk0E */  8,
    },
    /* TICK */
    {
        /* type */   TYPE_INSECT,
        /* unk01 */  0,
        /* hp */     5,
        /* en */     35,
        /* tp */     0,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_SENSOR,
        /* move */   WEAPON_LASER,
        /* move */   WEAPON_SPREAD,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  2,
        /* unk0E */  10,
    },
    /* RIKET */
    {
        /* type */   TYPE_INSECT,
        /* unk01 */  0,
        /* hp */     5,
        /* en */     30,
        /* tp */     0,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_SONOR,
        /* move */   WEAPON_STUN_G,
        /* move */   WEAPON_SPREAD,
        /* move */   WEAPON_PAINT,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  2,
        /* unk0E */  12,
    },
    /* DIVA */
    {
        /* type */   TYPE_ROOK,
        /* unk01 */  0,
        /* hp */     7,
        /* en */     30,
        /* tp */     0,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_SENSOR,
        /* move */   WEAPON_HEAVY_G,
        /* move */   WEAPON_SPIRAL,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  2,
        /* unk0E */  12,
    },
    /* GRIM */
    {
        /* type */   TYPE_ROOK,
        /* unk01 */  0,
        /* hp */     8,
        /* en */     30,
        /* tp */     0,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_SENSOR,
        /* move */   WEAPON_RAILGUN,
        /* move */   WEAPON_SPIRAL,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  2,
        /* unk0E */  11,
    },
    /* GOA */
    {
        /* type */   TYPE_ROOK,
        /* unk01 */  0,
        /* hp */     7,
        /* en */     30,
        /* tp */     0,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_SENSOR,
        /* move */   WEAPON_MISSILE,
        /* move */   WEAPON_BOOSTER,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  2,
        /* unk0E */  9,
    },
    /* DIRIS */
    {
        /* type */   TYPE_SEEKER,
        /* unk01 */  0,
        /* hp */     6,
        /* en */     25,
        /* tp */     0,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_SENSOR,
        /* move */   WEAPON_LASER,
        /* move */   WEAPON_STUN_G,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  2,
        /* unk0E */  13,
    },
    /* KEPTER */
    {
        /* type */   TYPE_SEEKER,
        /* unk01 */  0,
        /* hp */     5,
        /* en */     30,
        /* tp */     0,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_SENSOR,
        /* move */   WEAPON_A_RIFLE,
        /* move */   WEAPON_WARP,
        /* move */   WEAPON_FLASH,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  2,
        /* unk0E */  8,
    },
    /* RENGS */
    {
        /* type */   TYPE_SEEKER,
        /* unk01 */  0,
        /* hp */     5,
        /* en */     30,
        /* tp */     0,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_RADAR,
        /* move */   WEAPON_BLAST,
        /* move */   WEAPON_WARP,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  2,
        /* unk0E */  10,
    },
    /* VENOM */
    {
        /* type */   TYPE_RANGER,
        /* unk01 */  0,
        /* hp */     5,
        /* en */     35,
        /* tp */     0,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_SENSOR,
        /* move */   WEAPON_STUN_G,
        /* move */   WEAPON_SPREAD,
        /* move */   WEAPON_E_FIELD,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  2,
        /* unk0E */  8,
    },
    /* CASCADE */
    {
        /* type */   TYPE_RANGER,
        /* unk01 */  0,
        /* hp */     7,
        /* en */     20,
        /* tp */     0,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_SENSOR,
        /* move */   WEAPON_LASER,
        /* move */   WEAPON_STUN_G,
        /* move */   WEAPON_DECOY,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  2,
        /* unk0E */  9,
    },
    /* HYPNO */
    {
        /* type */   TYPE_RANGER,
        /* unk01 */  0,
        /* hp */     6,
        /* en */     25,
        /* tp */     0,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_SONOR,
        /* move */   WEAPON_RAILGUN,
        /* move */   WEAPON_HEAVY_G,
        /* move */   WEAPON_FLASH,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  2,
        /* unk0E */  13,
    },
    /* SIFER */
    {
        /* type */   TYPE_PROTO,
        /* unk01 */  0,
        /* hp */     10,
        /* en */     45,
        /* tp */     0,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_RADAR,
        /* move */   WEAPON_LASER,
        /* move */   WEAPON_WARP,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  2,
        /* unk0E */  12,
    },
    /* UNKNOWN */
    {
        /* type */   TYPE_UNK,
        /* unk01 */  0,
        /* hp */     99,
        /* en */     25,
        /* tp */     0,
        /* move */   WEAPON_MOVE,
        /* move */   WEAPON_SONOR,
        /* move */   WEAPON_H_GUN,
        /* move */   WEAPON_SPREAD,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* move */   WEAPON_INVALID,
        /* unk0D */  0,
        /* unk0E */  0,
    },
};

static const char far chara_name00[] = "SHUNER ";
static const char far chara_name01[] = "WELG   ";
static const char far chara_name02[] = "ORNET  ";
static const char far chara_name03[] = "BEETZ  ";
static const char far chara_name04[] = "ROID   ";
static const char far chara_name05[] = "MONO   ";
static const char far chara_name06[] = "BLINK  ";
static const char far chara_name07[] = "CANAVIS";
static const char far chara_name08[] = "ORG    ";
static const char far chara_name09[] = "M-DOWN ";
static const char far chara_name10[] = "GAZE   ";
static const char far chara_name11[] = "HYUMN  ";
static const char far chara_name12[] = "SOLID  ";
static const char far chara_name13[] = "MOLTH  ";
static const char far chara_name14[] = "DINGO  ";
static const char far chara_name15[] = "HOUND  ";
static const char far chara_name16[] = "GLID   ";
static const char far chara_name17[] = "APHEX  ";
static const char far chara_name18[] = "HOPER  ";
static const char far chara_name19[] = "CICADE ";
static const char far chara_name20[] = "ROGUE  ";
static const char far chara_name21[] = "MUSHA  ";
static const char far chara_name22[] = "RENS   ";
static const char far chara_name23[] = "PSY-O  ";
static const char far chara_name24[] = "SILVER ";
static const char far chara_name25[] = "ELVEN  ";
static const char far chara_name26[] = "ZERO   ";
static const char far chara_name27[] = "DEPT   ";
static const char far chara_name28[] = "CONFU  ";
static const char far chara_name29[] = "FLEA   ";
static const char far chara_name30[] = "TICK   ";
static const char far chara_name31[] = "RIKET  ";
static const char far chara_name32[] = "DIVA   ";
static const char far chara_name33[] = "GRIM   ";
static const char far chara_name34[] = "GOA    ";
static const char far chara_name35[] = "DIRIS  ";
static const char far chara_name36[] = "KEPTER ";
static const char far chara_name37[] = "RENGS  ";
static const char far chara_name38[] = "VENOM  ";
static const char far chara_name39[] = "CASCADE";
static const char far chara_name40[] = "HYPNO  ";
static const char far chara_name41[] = "SIFER  ";

const char far * far chara_name[] =
{
    chara_name00,
    chara_name01,
    chara_name02,
    chara_name03,
    chara_name04,
    chara_name05,
    chara_name06,
    chara_name07,
    chara_name08,
    chara_name09,
    chara_name10,
    chara_name11,
    chara_name12,
    chara_name13,
    chara_name14,
    chara_name15,
    chara_name16,
    chara_name17,
    chara_name18,
    chara_name19,
    chara_name20,
    chara_name21,
    chara_name22,
    chara_name23,
    chara_name24,
    chara_name25,
    chara_name26,
    chara_name27,
    chara_name28,
    chara_name29,
    chara_name30,
    chara_name31,
    chara_name32,
    chara_name33,
    chara_name34,
    chara_name35,
    chara_name36,
    chara_name37,
    chara_name38,
    chara_name39,
    chara_name40,
    chara_name41,
};

static const char far type_name00[] = "KNIGHT ";
static const char far type_name01[] = "INSECT ";
static const char far type_name02[] = "ROOK   ";
static const char far type_name03[] = "SEEKER ";
static const char far type_name04[] = "RANGER ";
static const char far type_name05[] = "PROTO  ";

const char far * far type_name[] =
{
    type_name00,
    type_name01,
    type_name02,
    type_name03,
    type_name04,
    type_name05,
};

const u8 far stagelist[] = {
    0x10, 0x15, 0x17, 0x13, 0x1A, 0x14, 0x11, 0x16, 0x18, 0x0E, 0x19, 0x0F, 0x12, 0x15, 0x10, 0x1B,
    0x1C, 0x22, 0x27, 0x21, 0x25, 0x1F, 0x1D, 0x24, 0x26, 0x20, 0x1E, 0x23, 0x29, 0x28, 0x2A, 0x1B 
};

const u8 far stageadd[] = {
    0x00, 0x00, 0x00, 0x08,
    0x00, 0x00, 0x00, 0x09,
    0x00, 0x00, 0x00, 0x0A,
    0x00, 0x00, 0x00, 0x0B,
    0x0C 
};


