#include <machine.h>
#include "types.h"
#include "IP_MES.h"
#include "SYSTEM.h"
#include "SERIAL.h"
#include "SPRINTF.h"
#include "SWANMAIN.h"
#include "MEMORY.h"
#include "SWAN_L_C.h"
#include "PAD.h"

static u16 unk0 = 0;

static char str0[] = "IP_MES test program";
static char str1[] = "                 level1.00";
static char str2[] = "- EntryList - No:Ip:Ln:Ma -";
static char str3[] = "%d:%d.%d.%d.%d:%d:%d";
static char str4[] = "- used:%d - free:%d - max:%d -";
static char str5[] = "Initialize RIGHT+LEFT+A";
static char str6[] = "button push";
static char str7[] = ">--=[  Ipmes Init. ]==--<";
static char str8[] = "%04X:%04X";

static void near unk_830F2()
{
	ASM_INLINE("PUSH	BP");
	ASM_INLINE("MOV	BP,SP");
	ASM_INLINE("SUB	SP,0x0004");
	ASM_INLINE("MOV	[BP-0x04].W,AX");
	ASM_INLINE("MOV	[BP-0x02].W,BX");
	ASM_INLINE("MOV	SP,BP");
	ASM_INLINE("POP	BP");
}

static void near unk_83102()
{
	ASM_INLINE("PUSH	BP");
	ASM_INLINE("MOV	BP,SP");
	ASM_INLINE("SUB	SP,0x0004");
	ASM_INLINE("MOV	[BP-0x04].W,AX");
	ASM_INLINE("MOV	[BP-0x02].W,BX");
	ASM_INLINE("MOV	BX,[BP-0x04].W");
	ASM_INLINE("MOV	AX,[BP-0x02].W");
	ASM_INLINE("CMP	AX,0x8000");
	ASM_INLINE("JNZ	_8311D");
	ASM_INLINE("CMP	BX,0x00FF");
ASM_INLINE("_8311D:");
	ASM_INLINE("JNZ	_83123");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("JMP	_8317A");
ASM_INLINE("_83123:");
	ASM_INLINE("MOV	BX,[BP-0x04].W");
	ASM_INLINE("MOV	AX,[BP-0x02].W");
	ASM_INLINE("CMP	AX,0x8000");
	ASM_INLINE("JNZ	_83132");
	ASM_INLINE("CMP	BX,0x00FF");
ASM_INLINE("_83132:");
	ASM_INLINE("JNZ	_83138");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("JMP	_8317A");
ASM_INLINE("_83138:");
	ASM_INLINE("MOV	BX,[BP-0x04].W");
	ASM_INLINE("MOV	AX,[BP-0x02].W");
	ASM_INLINE("CMP	AX,0x8000");
	ASM_INLINE("JNZ	_83147");
	ASM_INLINE("CMP	BX,0x00FF");
ASM_INLINE("_83147:");
	ASM_INLINE("JNZ	_8314D");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("JMP	_8317A");
ASM_INLINE("_8314D:");
	ASM_INLINE("MOV	BX,[BP-0x04].W");
	ASM_INLINE("MOV	AX,[BP-0x02].W");
	ASM_INLINE("CMP	AX,0x8000");
	ASM_INLINE("JNZ	_8315C");
	ASM_INLINE("CMP	BX,0x00FF");
ASM_INLINE("_8315C:");
	ASM_INLINE("JNZ	_83162");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("JMP	_8317A");
ASM_INLINE("_83162:");
	ASM_INLINE("MOV	BX,[BP-0x04].W");
	ASM_INLINE("MOV	AX,[BP-0x02].W");
	ASM_INLINE("CMP	AX,0x8000");
	ASM_INLINE("JNZ	_83171");
	ASM_INLINE("CMP	BX,0x00FF");
ASM_INLINE("_83171:");
	ASM_INLINE("JNZ	_83177");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("JMP	_8317A");
ASM_INLINE("_83177:");
	ASM_INLINE("MOV	AX,0xFFFF");
ASM_INLINE("_8317A:");
	ASM_INLINE("MOV	SP,BP");
	ASM_INLINE("POP	BP");
}

static void near unk_8317E()
{
	ASM_INLINE("PUSH	BP");
	ASM_INLINE("MOV	BP,SP");
	ASM_INLINE("SUB	SP,0x0004");
	ASM_INLINE("MOV	[BP-0x04].W,AX");
	ASM_INLINE("MOV	[BP-0x02].W,BX");
	ASM_INLINE("MOV	BX,[BP-0x04].W");
	ASM_INLINE("MOV	AX,[BP-0x02].W");
	ASM_INLINE("CMP	AX,0x8000");
	ASM_INLINE("JNZ	_83199");
	ASM_INLINE("CMP	BX,0x00FF");
ASM_INLINE("_83199:");
	ASM_INLINE("JNZ	_8319F");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("JMP	_831F6");
ASM_INLINE("_8319F:");
	ASM_INLINE("MOV	BX,[BP-0x04].W");
	ASM_INLINE("MOV	AX,[BP-0x02].W");
	ASM_INLINE("CMP	AX,0x8000");
	ASM_INLINE("JNZ	_831AE");
	ASM_INLINE("CMP	BX,0x00FF");
ASM_INLINE("_831AE:");
	ASM_INLINE("JNZ	_831B4");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("JMP	_831F6");
ASM_INLINE("_831B4:");
	ASM_INLINE("MOV	BX,[BP-0x04].W");
	ASM_INLINE("MOV	AX,[BP-0x02].W");
	ASM_INLINE("CMP	AX,0x8000");
	ASM_INLINE("JNZ	_831C3");
	ASM_INLINE("CMP	BX,0x00FF");
ASM_INLINE("_831C3:");
	ASM_INLINE("JNZ	_831C9");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("JMP	_831F6");
ASM_INLINE("_831C9:");
	ASM_INLINE("MOV	BX,[BP-0x04].W");
	ASM_INLINE("MOV	AX,[BP-0x02].W");
	ASM_INLINE("CMP	AX,0x8000");
	ASM_INLINE("JNZ	_831D8");
	ASM_INLINE("CMP	BX,0x00FF");
ASM_INLINE("_831D8:");
	ASM_INLINE("JNZ	_831DE");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("JMP	_831F6");
ASM_INLINE("_831DE:");
	ASM_INLINE("MOV	BX,[BP-0x04].W");
	ASM_INLINE("MOV	AX,[BP-0x02].W");
	ASM_INLINE("CMP	AX,0x8000");
	ASM_INLINE("JNZ	_831ED");
	ASM_INLINE("CMP	BX,0x00FF");
ASM_INLINE("_831ED:");
	ASM_INLINE("JNZ	_831F3");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("JMP	_831F6");
ASM_INLINE("_831F3:");
	ASM_INLINE("MOV	AX,0xFFFF");
ASM_INLINE("_831F6:");
	ASM_INLINE("MOV	SP,BP");
	ASM_INLINE("POP	BP");
}

static void near unk_831FA()
{
	ASM_INLINE("PUSH	BP");
	ASM_INLINE("MOV	BP,SP");
	ASM_INLINE("SUB	SP,0x0004");
	ASM_INLINE("MOV	[BP-0x04].W,AX");
	ASM_INLINE("MOV	[BP-0x02].W,BX");
	ASM_INLINE("MOV	BX,[BP-0x04].W");
	ASM_INLINE("MOV	AX,[BP-0x02].W");
	ASM_INLINE("CMP	AX,0x8000");
	ASM_INLINE("JNZ	_83215");
	ASM_INLINE("CMP	BX,0x00FF");
ASM_INLINE("_83215:");
	ASM_INLINE("JNZ	_8321B");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("JMP	_83272");
ASM_INLINE("_8321B:");
	ASM_INLINE("MOV	BX,[BP-0x04].W");
	ASM_INLINE("MOV	AX,[BP-0x02].W");
	ASM_INLINE("CMP	AX,0x8000");
	ASM_INLINE("JNZ	_8322A");
	ASM_INLINE("CMP	BX,0x00FF");
ASM_INLINE("_8322A:");
	ASM_INLINE("JNZ	_83230");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("JMP	_83272");
ASM_INLINE("_83230:");
	ASM_INLINE("MOV	BX,[BP-0x04].W");
	ASM_INLINE("MOV	AX,[BP-0x02].W");
	ASM_INLINE("CMP	AX,0x8000");
	ASM_INLINE("JNZ	_8323F");
	ASM_INLINE("CMP	BX,0x00FF");
ASM_INLINE("_8323F:");
	ASM_INLINE("JNZ	_83245");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("JMP	_83272");
ASM_INLINE("_83245:");
	ASM_INLINE("MOV	BX,[BP-0x04].W");
	ASM_INLINE("MOV	AX,[BP-0x02].W");
	ASM_INLINE("CMP	AX,0x8000");
	ASM_INLINE("JNZ	_83254");
	ASM_INLINE("CMP	BX,0x00FF");
ASM_INLINE("_83254:");
	ASM_INLINE("JNZ	_8325A");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("JMP	_83272");
ASM_INLINE("_8325A:");
	ASM_INLINE("MOV	BX,[BP-0x04].W");
	ASM_INLINE("MOV	AX,[BP-0x02].W");
	ASM_INLINE("CMP	AX,0x8000");
	ASM_INLINE("JNZ	_83269");
	ASM_INLINE("CMP	BX,0x00FF");
ASM_INLINE("_83269:");
	ASM_INLINE("JNZ	_8326F");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("JMP	_83272");
ASM_INLINE("_8326F:");
	ASM_INLINE("MOV	AX,0xFFFF");
ASM_INLINE("_83272:");
	ASM_INLINE("MOV	SP,BP");
	ASM_INLINE("POP	BP");
}

void ip_init()
{
	ASM_INLINE("MOV	BX,0x0E92");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("JMP	_8328A");
ASM_INLINE("_8327D:");
	ASM_INLINE("MOV	[BX].W,0x00FF");
	ASM_INLINE("MOV	[BX+0x02].W,0x8000");
	ASM_INLINE("INC	AX");
	ASM_INLINE("ADD	BX,0x0016");
ASM_INLINE("_8328A:");
	ASM_INLINE("CMP	AX,0x0010");
	ASM_INLINE("JL	_8327D");
	ASM_INLINE("XOR	AX,AX");
}

static void near unk_83292()
{
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("MOV	SI,0x0E92");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("JMP	_832B0");
ASM_INLINE("_8329B:");
	ASM_INLINE("MOV	CX,[SI].W");
	ASM_INLINE("MOV	BX,[SI+0x02].W");
	ASM_INLINE("CMP	BX,0x8000");
	ASM_INLINE("JNZ	_832AA");
	ASM_INLINE("CMP	CX,0x00FF");
ASM_INLINE("_832AA:");
	ASM_INLINE("JZ	_832B8");
	ASM_INLINE("INC	AX");
	ASM_INLINE("ADD	SI,0x0016");
ASM_INLINE("_832B0:");
	ASM_INLINE("CMP	AX,0x0010");
	ASM_INLINE("JL	_8329B");
	ASM_INLINE("MOV	AX,0xFFFF");
ASM_INLINE("_832B8:");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	CX");
}

static void near unk_832BB()
{
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	BX,0x0E92");
	ASM_INLINE("MOV	SI,0x0FF2");
	ASM_INLINE("MOV	AL,0xFF");
	ASM_INLINE("MOV	CL,0x63");
	ASM_INLINE("XOR	DX,DX");
	ASM_INLINE("JMP	_832ED");
ASM_INLINE("_832CD:");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("MOV	DI,[BX].W");
	ASM_INLINE("MOV	DX,[BX+0x02].W");
	ASM_INLINE("CMP	DX,0x8000");
	ASM_INLINE("JNZ	_832DD");
	ASM_INLINE("CMP	DI,0x00FF");
ASM_INLINE("_832DD:");
	ASM_INLINE("POP	DX");
	ASM_INLINE("JZ	_832E8");
	ASM_INLINE("CMP	CL,[SI].B");
	ASM_INLINE("JLE	_832E8");
	ASM_INLINE("MOV	AL,DL");
	ASM_INLINE("MOV	CL,[SI].B");
ASM_INLINE("_832E8:");
	ASM_INLINE("INC	DX");
	ASM_INLINE("ADD	BX,0x0016");
	ASM_INLINE("INC	SI");
ASM_INLINE("_832ED:");
	ASM_INLINE("CMP	DX,0x0010");
	ASM_INLINE("JL	_832CD");
	ASM_INLINE("CBW");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
}

static void near unk_832F8()
{
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	BX,0x0FF2");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("JMP	_8330F");
ASM_INLINE("_83300:");
	ASM_INLINE("CMP	[BX].B,0x00");
	ASM_INLINE("JLE	_83309");
	ASM_INLINE("MOV	AL,0x01");
	ASM_INLINE("JMP	_8330B");
ASM_INLINE("_83309:");
	ASM_INLINE("XOR	AL,AL");
ASM_INLINE("_8330B:");
	ASM_INLINE("SUB	[BX].B,AL");
	ASM_INLINE("INC	CX");
	ASM_INLINE("INC	BX");
ASM_INLINE("_8330F:");
	ASM_INLINE("CMP	CX,0x0010");
	ASM_INLINE("JL	_83300");
	ASM_INLINE("POP	CX");
}

static void near unk_83316()
{
	ASM_INLINE("PUSH	BP");
	ASM_INLINE("MOV	BP,SP");
	ASM_INLINE("SUB	SP,0x0004");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	[BP-0x04].W,AX");
	ASM_INLINE("MOV	[BP-0x02].W,BX");
	ASM_INLINE("MOV	SI,CX");
	ASM_INLINE("MOV	CX,DX");
	ASM_INLINE("MOV	AX,[BP-0x04].W");
	ASM_INLINE("MOV	BX,[BP-0x02].W");
	ASM_INLINE("CALL	unk_83102_");
	ASM_INLINE("TEST	AX,AX");
	ASM_INLINE("JNZ	_8333C");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("JMP	_833BE");
ASM_INLINE("_8333C:");
	ASM_INLINE("CALL	unk_832F8_");
	ASM_INLINE("CALL	unk_83292_");
	ASM_INLINE("MOV	BX,AX");
	ASM_INLINE("CMP	BX,-1");
	ASM_INLINE("JZ	_8337D");
	ASM_INLINE("MOV	AX,BX");
	ASM_INLINE("MOV	DX,0x0016");
	ASM_INLINE("MUL	DX");
	ASM_INLINE("MOV	DI,AX");
	ASM_INLINE("ADD	DI,0x0E92");
	ASM_INLINE("MOV	DX,[BP-0x04].W");
	ASM_INLINE("MOV	AX,[BP-0x02].W");
	ASM_INLINE("MOV	[DI].W,DX");
	ASM_INLINE("MOV	[DI+0x02].W,AX");
	ASM_INLINE("MOV	[DI+0x14].W,CX");
	ASM_INLINE("MOV	[BX+0x0FF2].B,0x63");
	ASM_INLINE("ADD	DI,0x0004");
	ASM_INLINE("JMP	_83375");
ASM_INLINE("_8336E:");
	ASM_INLINE("MOV	AL,[SI].B");
	ASM_INLINE("INC	SI");
	ASM_INLINE("MOV	[DI].B,AL");
	ASM_INLINE("INC	DI");
	ASM_INLINE("DEC	CX");
ASM_INLINE("_83375:");
	ASM_INLINE("TEST	CX,CX");
	ASM_INLINE("JNZ	_8336E");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("JMP	_833BE");
ASM_INLINE("_8337D:");
	ASM_INLINE("CALL	unk_832BB_");
	ASM_INLINE("MOV	BX,AX");
	ASM_INLINE("CMP	BX,-1");
	ASM_INLINE("JZ	_833BB");
	ASM_INLINE("MOV	AX,BX");
	ASM_INLINE("MOV	DX,0x0016");
	ASM_INLINE("MUL	DX");
	ASM_INLINE("MOV	DI,AX");
	ASM_INLINE("ADD	DI,0x0E92");
	ASM_INLINE("MOV	DX,[BP-0x04].W");
	ASM_INLINE("MOV	AX,[BP-0x02].W");
	ASM_INLINE("MOV	[DI].W,DX");
	ASM_INLINE("MOV	[DI+0x02].W,AX");
	ASM_INLINE("MOV	[DI+0x14].W,CX");
	ASM_INLINE("MOV	[BX+0x0FF2].B,0x63");
	ASM_INLINE("ADD	DI,0x0004");
	ASM_INLINE("JMP	_833B3");
ASM_INLINE("_833AC:");
	ASM_INLINE("MOV	AL,[SI].B");
	ASM_INLINE("INC	SI");
	ASM_INLINE("MOV	[DI].B,AL");
	ASM_INLINE("INC	DI");
	ASM_INLINE("DEC	CX");
ASM_INLINE("_833B3:");
	ASM_INLINE("TEST	CX,CX");
	ASM_INLINE("JNZ	_833AC");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("JMP	_833BE");
ASM_INLINE("_833BB:");
	ASM_INLINE("MOV	AX,0xFFFF");
ASM_INLINE("_833BE:");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
	ASM_INLINE("MOV	SP,BP");
	ASM_INLINE("POP	BP");
}

static void near unk_833C6()
{
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	SI,AX");
	ASM_INLINE("MOV	CX,0x0E92");
	ASM_INLINE("XOR	DI,DI");
	ASM_INLINE("JMP	_83419");
ASM_INLINE("_833D3:");
	ASM_INLINE("MOV	DX,[SI].W");
	ASM_INLINE("MOV	AX,[SI+0x02].W");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("CMP	AX,[BX+0x02].W");
	ASM_INLINE("JNZ	_833E1");
	ASM_INLINE("CMP	DX,[BX].W");
ASM_INLINE("_833E1:");
	ASM_INLINE("JNZ	_83415");
	ASM_INLINE("MOV	DI,SI");
	ASM_INLINE("ADD	DI,0x0004");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("ADD	BX,0x0004");
	ASM_INLINE("JMP	_833F8");
ASM_INLINE("_833EF:");
	ASM_INLINE("MOV	AL,[BX].B");
	ASM_INLINE("INC	BX");
	ASM_INLINE("MOV	[DI].B,AL");
	ASM_INLINE("INC	DI");
	ASM_INLINE("DEC	[SI+0x14].W");
ASM_INLINE("_833F8:");
	ASM_INLINE("CMP	[SI+0x14].W,0x0000");
	ASM_INLINE("JNZ	_833EF");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("MOV	AX,[BX+0x14].W");
	ASM_INLINE("MOV	[SI+0x14].W,AX");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("MOV	[BX].W,0x00FF");
	ASM_INLINE("MOV	[BX+0x02].W,0x8000");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("JMP	_83421");
ASM_INLINE("_83415:");
	ASM_INLINE("INC	DI");
	ASM_INLINE("ADD	CX,0x0016");
ASM_INLINE("_83419:");
	ASM_INLINE("CMP	DI,0x0010");
	ASM_INLINE("JL	_833D3");
	ASM_INLINE("MOV	AX,0xFFFF");
ASM_INLINE("_83421:");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
}

void ip_r()
{
	lcd_option_1; //Force include
	serial_in; //Force include
	ASM_INLINE("PUSH	BP");
	ASM_INLINE("MOV	BP,SP");
	ASM_INLINE("SUB	SP,0x0106");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	SI,AX");
	ASM_INLINE("JMP	_83491");
ASM_INLINE("_83435:");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("CALLF	lcd_option_1_, SEG lcd_option_1_");
	ASM_INLINE("MOV	AL,[BP-0x0104].B");
	ASM_INLINE("XOR	AH,AH");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("MOV	CX,0x0018");
	//ASM_INLINE("JCXZ	_83450");
	ASM_OP2(0xE3,0x06);
ASM_INLINE("_8344A:");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("RCL	BX,1");
	ASM_INLINE("LOOP	_8344A");
ASM_INLINE("_83450:");
	ASM_INLINE("MOV	CL,[BP-0x0103].B");
	ASM_INLINE("XOR	CH,CH");
	ASM_INLINE("XOR	DX,DX");
	ASM_INLINE("MOV	CX,CX");
	ASM_INLINE("XOR	DX,DX");
	ASM_INLINE("OR	AX,DX");
	ASM_INLINE("OR	BX,CX");
	ASM_INLINE("MOV	DL,[BP-0x0102].B");
	ASM_INLINE("XOR	DH,DH");
	ASM_INLINE("XOR	DI,DI");
	ASM_INLINE("MOV	CX,0x0008");
	//ASM_INLINE("JCXZ	_83473");
	ASM_OP2(0xE3,0x06);
ASM_INLINE("_8346D:");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("RCL	DI,1");
	ASM_INLINE("LOOP	_8346D");
ASM_INLINE("_83473:");
	ASM_INLINE("OR	AX,DX");
	ASM_INLINE("OR	BX,DI");
	ASM_INLINE("MOV	CL,[BP-0x0101].B");
	ASM_INLINE("XOR	CH,CH");
	ASM_INLINE("XOR	DX,DX");
	ASM_INLINE("OR	AX,CX");
	ASM_INLINE("OR	BX,DX");
	ASM_INLINE("LEA	CX,[BP-0x0100].B");
	ASM_INLINE("MOV	DX,[BP-0x0106].W");
	ASM_INLINE("SUB	DX,0x0004");
	ASM_INLINE("CALL	unk_83316_");
ASM_INLINE("_83491:");
	ASM_INLINE("LEA	AX,[BP-0x0104].B");
	ASM_INLINE("LEA	BX,[BP-0x0106].B");
	ASM_INLINE("CALLF	serial_in_, SEG serial_in_");
	ASM_INLINE("TEST	AX,AX");
	ASM_INLINE("JNZ	_83435");
	ASM_INLINE("MOV	AX,SI");
	ASM_INLINE("CALL	unk_833C6_");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
	ASM_INLINE("MOV	SP,BP");
	ASM_INLINE("POP	BP");
}

void ip_w()
{
	serial_out; //Force include
	lcd_option_3; //Force include
	ASM_INLINE("PUSH	BP");
	ASM_INLINE("MOV	BP,SP");
	ASM_INLINE("SUB	SP,0x0104");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	SI,AX");
	ASM_INLINE("MOV	AX,[SI].W");
	ASM_INLINE("MOV	BX,[SI+0x02].W");
	ASM_INLINE("CALL	unk_83102_");
	ASM_INLINE("TEST	AX,AX");
	ASM_INLINE("JNZ	_834CC");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("JMP	_83561");
ASM_INLINE("_834CC:");
	ASM_INLINE("MOV	AX,[SI].W");
	ASM_INLINE("MOV	BX,[SI+0x02].W");
	ASM_INLINE("MOV	CX,0x0018");
	//ASM_INLINE("JCXZ	_834DC");
	ASM_OP2(0xE3,0x06);
ASM_INLINE("_834D6:");
	ASM_INLINE("SHR	BX,1");
	ASM_INLINE("RCR	AX,1");
	ASM_INLINE("LOOP	_834D6");
ASM_INLINE("_834DC:");
	ASM_INLINE("AND	AX,0x00FF");
	ASM_INLINE("AND	BX,0x0000");
	ASM_INLINE("MOV	[BP-0x0104].B,AL");
	ASM_INLINE("MOV	AX,[SI].W");
	ASM_INLINE("MOV	AX,[SI+0x02].W");
	ASM_INLINE("MOV	AX,AX");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("AND	AX,0x00FF");
	ASM_INLINE("AND	BX,0x0000");
	ASM_INLINE("MOV	[BP-0x0103].B,AL");
	ASM_INLINE("MOV	AX,[SI].W");
	ASM_INLINE("MOV	BX,[SI+0x02].W");
	ASM_INLINE("MOV	CX,0x0008");
	//ASM_INLINE("JCXZ	_8350B");
	ASM_OP2(0xE3,0x06);
ASM_INLINE("_83505:");
	ASM_INLINE("SHR	BX,1");
	ASM_INLINE("RCR	AX,1");
	ASM_INLINE("LOOP	_83505");
ASM_INLINE("_8350B:");
	ASM_INLINE("AND	AX,0x00FF");
	ASM_INLINE("AND	BX,0x0000");
	ASM_INLINE("MOV	[BP-0x0102].B,AL");
	ASM_INLINE("MOV	AX,[SI].W");
	ASM_INLINE("MOV	BX,[SI+0x02].W");
	ASM_INLINE("AND	AX,0x00FF");
	ASM_INLINE("AND	BX,0x0000");
	ASM_INLINE("MOV	[BP-0x0101].B,AL");
	ASM_INLINE("LEA	BX,[BP-0x0100].B");
	ASM_INLINE("MOV	DI,SI");
	ASM_INLINE("ADD	DI,0x0004");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("JMP	_8353A");
ASM_INLINE("_83533:");
	ASM_INLINE("MOV	AL,[DI].B");
	ASM_INLINE("INC	DI");
	ASM_INLINE("MOV	[BX].B,AL");
	ASM_INLINE("INC	BX");
	ASM_INLINE("INC	CX");
ASM_INLINE("_8353A:");
	ASM_INLINE("CMP	CX,[SI+0x14].W");
	ASM_INLINE("JL	_83533");
	ASM_INLINE("LEA	AX,[BP-0x0104].B");
	ASM_INLINE("MOV	BX,[SI+0x14].W");
	ASM_INLINE("ADD	BX,0x0004");
	ASM_INLINE("CALLF	serial_out_, SEG serial_out_");
	ASM_INLINE("TEST	AX,AX");
	ASM_INLINE("JNZ	_8355E");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("CALLF	lcd_option_3_, SEG lcd_option_3_");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("JMP	_83561");
ASM_INLINE("_8355E:");
	ASM_INLINE("MOV	AX,0xFFFF");
ASM_INLINE("_83561:");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	CX");
	ASM_INLINE("MOV	SP,BP");
	ASM_INLINE("POP	BP");
}

void ip_clear()
{
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	BX,AX");
	ASM_INLINE("XOR	DX,DX");
	ASM_INLINE("MOV	SI,0x0E92");
	ASM_INLINE("XOR	DI,DI");
	ASM_INLINE("JMP	_83595");
ASM_INLINE("_83577:");
	ASM_INLINE("MOV	CX,[BX].W");
	ASM_INLINE("MOV	AX,[BX+0x02].W");
	ASM_INLINE("CMP	AX,[SI+0x02].W");
	ASM_INLINE("JNZ	_83583");
	ASM_INLINE("CMP	CX,[SI].W");
ASM_INLINE("_83583:");
	ASM_INLINE("JNZ	_83591");
	ASM_INLINE("MOV	[SI].W,0x00FF");
	ASM_INLINE("MOV	[SI+0x02].W,0x8000");
	ASM_INLINE("MOV	DX,0x0001");
ASM_INLINE("_83591:");
	ASM_INLINE("INC	DI");
	ASM_INLINE("ADD	SI,0x0016");
ASM_INLINE("_83595:");
	ASM_INLINE("CMP	DI,0x0010");
	ASM_INLINE("JL	_83577");
	ASM_INLINE("TEST	DX,DX");
	ASM_INLINE("JZ	_835A2");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("JMP	_835A5");
ASM_INLINE("_835A2:");
	ASM_INLINE("MOV	AX,0xFFFF");
ASM_INLINE("_835A5:");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
}

static void near unk_835AA()
{
	cls; //Force include
	print; //Force include
	hsprintf; //Force include
	ASM_INLINE("PUSH	BP");
	ASM_INLINE("MOV	BP,SP");
	ASM_INLINE("SUB	SP,0x0100");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("CALLF	cls_, SEG cls_");
	ASM_INLINE("MOV	SI,0x0001");
	ASM_INLINE("MOV	BX,0x0000");
	ASM_INLINE("MOV	AX,0xA000");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("INC	SI");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("DEC	BX");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("MOV	DX,0x0212");
	ASM_INLINE("CALLF	print_, SEG print_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("MOV	BX,0x0000");
	ASM_INLINE("MOV	AX,0xA000");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("INC	SI");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("DEC	BX");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("MOV	DX,0x0226");
	ASM_INLINE("CALLF	print_, SEG print_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("MOV	BX,0x0000");
	ASM_INLINE("MOV	AX,0xA000");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("INC	SI");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("DEC	BX");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("MOV	DX,0x0242");
	ASM_INLINE("CALLF	print_, SEG print_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("XOR	DI,DI");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("JMP	_836F8");
ASM_INLINE("_8361E:");
	ASM_INLINE("MOV	AX,CX");
	ASM_INLINE("MOV	BX,0x0016");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("MOV	BX,AX");
	ASM_INLINE("MOV	DX,[BX+0x0E92].W");
	ASM_INLINE("MOV	AX,[BX+0x0E94].W");
	ASM_INLINE("CMP	AX,0x8000");
	ASM_INLINE("JNZ	_83638");
	ASM_INLINE("CMP	DX,0x00FF");
ASM_INLINE("_83638:");
	ASM_INLINE("JNZ	_8363D");
	ASM_INLINE("JMP	_836F7");
ASM_INLINE("_8363D:");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("MOV	AL,[BX+0x0FF2].B");
	ASM_INLINE("CBW");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,CX");
	ASM_INLINE("MOV	BX,0x0016");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("MOV	BX,AX");
	ASM_INLINE("ADD	BX,0x0E92");
	ASM_INLINE("PUSH	[BX+0x14].W");
	ASM_INLINE("MOV	AX,CX");
	ASM_INLINE("MOV	BX,0x0016");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("MOV	BX,AX");
	ASM_INLINE("MOV	AX,[BX+0x0E92].W");
	ASM_INLINE("AND	AX,0x00FF");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	AX,CX");
	ASM_INLINE("MOV	BX,0x0016");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("MOV	BX,AX");
	ASM_INLINE("MOV	AX,[BX+0x0E92].W");
	ASM_INLINE("MOV	BX,[BX+0x0E94].W");
	ASM_INLINE("MOV	CX,0x0008");
	//ASM_INLINE("JCXZ	_83684");
	ASM_OP2(0xE3,0x06);
ASM_INLINE("_8367E:");
	ASM_INLINE("SHR	BX,1");
	ASM_INLINE("RCR	AX,1");
	ASM_INLINE("LOOP	_8367E");
ASM_INLINE("_83684:");
	ASM_INLINE("AND	AX,0x00FF");
	ASM_INLINE("POP	CX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,CX");
	ASM_INLINE("MOV	BX,0x0016");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("MOV	BX,AX");
	ASM_INLINE("MOV	AX,[BX+0x0E92].W");
	ASM_INLINE("MOV	AX,[BX+0x0E94].W");
	ASM_INLINE("MOV	BX,AX");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("AND	BX,0x00FF");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	AX,CX");
	ASM_INLINE("MOV	BX,0x0016");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("MOV	BX,AX");
	ASM_INLINE("MOV	AX,[BX+0x0E92].W");
	ASM_INLINE("MOV	BX,[BX+0x0E94].W");
	ASM_INLINE("MOV	CX,0x0018");
	//ASM_INLINE("JCXZ	_836C0");
	ASM_OP2(0xE3,0x06);
ASM_INLINE("_836BA:");
	ASM_INLINE("SHR	BX,1");
	ASM_INLINE("RCR	AX,1");
	ASM_INLINE("LOOP	_836BA");
ASM_INLINE("_836C0:");
	ASM_INLINE("AND	AX,0x00FF");
	ASM_INLINE("POP	CX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	AX,0x025E");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("LEA	AX,[BP-0x0100].B");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("CALLF	hsprintf_, SEG hsprintf_");
	ASM_INLINE("ADD	SP,0x0012");
	ASM_INLINE("MOV	BX,0x0000");
	ASM_INLINE("MOV	AX,0xA000");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("INC	SI");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("DEC	BX");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("LEA	DX,[BP-0x0100].B");
	ASM_INLINE("CALLF	print_, SEG print_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("INC	DI");
	ASM_INLINE("POP	CX");
ASM_INLINE("_836F7:");
	ASM_INLINE("INC	CX");
ASM_INLINE("_836F8:");
	ASM_INLINE("CMP	CX,0x0010");
	ASM_INLINE("JGE	_83700");
	ASM_INLINE("JMP	_8361E");
ASM_INLINE("_83700:");
	ASM_INLINE("MOV	AX,0x0010");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x0010");
	ASM_INLINE("SUB	AX,DI");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	AX,0x0274");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("LEA	AX,[BP-0x0100].B");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("CALLF	hsprintf_, SEG hsprintf_");
	ASM_INLINE("ADD	SP,0x000A");
	ASM_INLINE("MOV	BX,0x0000");
	ASM_INLINE("MOV	AX,0xA000");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("INC	SI");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("DEC	BX");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("LEA	DX,[BP-0x0100].B");
	ASM_INLINE("CALLF	print_, SEG print_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("MOV	BX,0x0000");
	ASM_INLINE("MOV	AX,0xA000");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("MOV	DX,0x0294");
	ASM_INLINE("CALLF	print_, SEG print_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("INC	SI");
	ASM_INLINE("MOV	BX,0x0000");
	ASM_INLINE("MOV	AX,0xA000");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("MOV	DX,0x02AC");
	ASM_INLINE("CALLF	print_, SEG print_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
	ASM_INLINE("MOV	SP,BP");
	ASM_INLINE("POP	BP");
}

static void near unk_8377B()
{
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("XOR	SI,SI");
	ASM_INLINE("JMP	_837A2");
ASM_INLINE("_83784:");
	ASM_INLINE("MOV	AX,SI");
	ASM_INLINE("MOV	BX,0x0016");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("MOV	BX,AX");
	ASM_INLINE("MOV	DX,[BX+0x0E92].W");
	ASM_INLINE("MOV	AX,[BX+0x0E94].W");
	ASM_INLINE("CMP	AX,0x8000");
	ASM_INLINE("JNZ	_8379E");
	ASM_INLINE("CMP	DX,0x00FF");
ASM_INLINE("_8379E:");
	ASM_INLINE("JZ	_837A1");
	ASM_INLINE("INC	CX");
ASM_INLINE("_837A1:");
	ASM_INLINE("INC	SI");
ASM_INLINE("_837A2:");
	ASM_INLINE("CMP	SI,0x0010");
	ASM_INLINE("JL	_83784");
	ASM_INLINE("MOV	AX,CX");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
}


void ip_mes_test_init()
{
	task_delete; //Force include
	memalloc; //Force include
	task_append; //Force include
	font_load; //Force include
	nbg_ddf; //Force include
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("CALLF	task_delete_, SEG task_delete_");
	ASM_INLINE("MOV	AX,0x0002");
	ASM_INLINE("CALLF	memalloc_, SEG memalloc_");
	ASM_INLINE("MOV	SI,AX");
	ASM_INLINE("TEST	SI,SI");
	ASM_INLINE("JZ	_837EE");
	ASM_INLINE("MOV	AX,unk_837F2_");
	ASM_INLINE("MOV	BX,SEG unk_837F2_");
	ASM_INLINE("MOV	CX,SI");
	ASM_INLINE("CALLF	task_append_, SEG task_append_");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("MOV	CX,0x0000");
	ASM_INLINE("MOV	DX,0xA000");
	ASM_INLINE("CALLF	font_load_, SEG font_load_");
	ASM_INLINE("CALL	unk_835AA_");
	ASM_INLINE("MOV	[SI].W,AX");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("MOV	BX,0x0001");
	ASM_INLINE("CALLF	nbg_ddf_, SEG nbg_ddf_");
ASM_INLINE("_837EE:");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
}

/*BUG?: Someone forgot to make this as near?*/
static void unk_837F2()
{
	print; //Force include
	ip_init; //Force include
	task_delete; //Force include
	memfree; //Force include
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("MOV	SI,AX");
	ASM_INLINE("CALL	unk_8377B_");
	ASM_INLINE("CMP	AX,[SI].W");
	ASM_INLINE("JZ	_83803");
	ASM_INLINE("CALL	unk_835AA_");
	ASM_INLINE("MOV	[SI].W,AX");
ASM_INLINE("_83803:");
	ASM_INLINE("TEST	[0x0952].W,0x0800"); //pad.unk0
	ASM_INLINE("JZ	_8383B");
	ASM_INLINE("TEST	[0x0952].W,0x0200"); //pad.unk0
	ASM_INLINE("JZ	_8383B");
	ASM_INLINE("TEST	[0x0956].W,0x0004"); //pad.unk4
	ASM_INLINE("JZ	_8383B");
	ASM_INLINE("MOV	BX,0x0000");
	ASM_INLINE("MOV	AX,0xA000");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("MOV	DX,0x02B8");
	ASM_INLINE("CALLF	print_, SEG print_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("CALLF	ip_init_, SEG ip_init_");
ASM_INLINE("_8383B:");
	ASM_INLINE("TEST	[0x0956].W,0x0002"); //pad.unk4
	ASM_INLINE("JZ	_8384F");
	ASM_INLINE("CALLF	task_delete_, SEG task_delete_");
	ASM_INLINE("MOV	AX,SI");
	ASM_INLINE("CALLF	memfree_, SEG memfree_");
ASM_INLINE("_8384F:");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
}
