#include <machine.h>
#include "types.h"
#include "m_sub.h"
#include "m_game.h"
#include "SERIAL.h"
#include "func_tbl.h"
#include "SWAN_L_C.h"
#include "SWANMAIN.h"
#include "SPRINTF.h"
#include "SYSTEM.h"
#include "SOUND_CODE.h"
#include "MEMORY.h"
#include "PAD.h"
#include "story.h"
#include "IP_MES.h"
#include "PUT_TEXT.h"
#include "m_cpu2p.h"
#include "m_weapon.h"
#include "tuneup.h"
#include "ASM.h"
#include "WORK.h"

extern const u8 far G_TURN_char_adr[];
extern const u8 far G_ENG_char_adr[];
extern const u8 far G_HP_char_adr[];
extern const u8 far G_FUNC_char_adr[];
extern const u8 far G_AU1_char_adr[];
extern const u8 far G_AU2_char_adr[];
extern const u8 far G_AU3_char_adr[];
extern const u8 far G_GAME_char_adr[];
extern const u8 far G_SPACE_char_adr[];

static const char far str_pause[] = "PAUSE";
static const char far str_exit[] = "EXIT";

static const char far * far str_all[] =
{
    str_pause,
    str_exit,
};

static const u8 far unk_1[] = {5,4};
static const u8 far unk_2[] = {4,6,8,6};
static const u8 far unk_3[] = {4,6,8};

void font_put3()
{
	font_put2_sub; //Force include
	ASM_INLINE("PUSH	BP");
	ASM_INLINE("MOV	BP,SP");
	ASM_INLINE("SUB	SP,0x000C");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	DX,AX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("MOV	AX,BX");
	ASM_INLINE("MOV	DI,CX");
	ASM_INLINE("MOV	BX,[BP+0x06].W");
	ASM_INLINE("MOV	BX,[BP+0x08].W");
	ASM_INLINE("MOV	CX,BX");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("MOV	CX,CX");
	ASM_INLINE("XOR	DX,DX");
	ASM_INLINE("MOV	SI,[BP+0x06].W");
	ASM_INLINE("LES	BX,[BP+0x06]");
	ASM_INLINE("ADD	SI,ES:[BX+0x0E].W");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("OR	DX,SI");
	ASM_INLINE("OR	CX,BX");
	ASM_INLINE("MOV	[BP-0x04].W,DX");
	ASM_INLINE("MOV	[BP-0x02].W,CX");
	ASM_INLINE("MOV	BX,[BP+0x06].W");
	ASM_INLINE("MOV	BX,[BP+0x08].W");
	ASM_INLINE("MOV	CX,BX");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("MOV	CX,CX");
	ASM_INLINE("XOR	DX,DX");
	ASM_INLINE("MOV	SI,[BP+0x06].W");
	ASM_INLINE("LES	BX,[BP+0x06]");
	ASM_INLINE("ADD	SI,ES:[BX+0x0C].W");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("OR	DX,SI");
	ASM_INLINE("OR	CX,BX");
	ASM_INLINE("MOV	[BP-0x08].W,DX");
	ASM_INLINE("MOV	[BP-0x06].W,CX");
	ASM_INLINE("MOV	CX,[0x00F8].W");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("MOV	SI,[0x005E].W");
	ASM_INLINE("XOR	DX,DX");
	ASM_INLINE("OR	CX,SI");
	ASM_INLINE("OR	BX,DX");
	ASM_INLINE("MOV	[BP-0x0C].W,CX");
	ASM_INLINE("MOV	[BP-0x0A].W,BX");
	ASM_INLINE("LES	BX,[BP+0x06]");
	ASM_INLINE("MOV	BX,ES:[BX+0x04].W");
	ASM_INLINE("SAR	BX,1");
	ASM_INLINE("SAR	BX,1");
	ASM_INLINE("SAR	BX,1");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("POP	DX");
	ASM_INLINE("ADD	AX,DX");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("ADD	BX,AX");
	ASM_INLINE("MOV	CX,ES:[BX].W");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	AX,[BP-0x08].W");
	ASM_INLINE("MOV	BX,[BP-0x06].W");
	ASM_INLINE("AND	CX,0x01FF");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("ADD	AX,CX");
	ASM_INLINE("MOV	CX,[BP-0x0C].W");
	ASM_INLINE("MOV	DX,[BP-0x0A].W");
	ASM_INLINE("SHL	DI,1");
	ASM_INLINE("SHL	DI,1");
	ASM_INLINE("SHL	DI,1");
	ASM_INLINE("SHL	DI,1");
	ASM_INLINE("ADD	CX,DI");
	ASM_INLINE("CALLF	font_put2_sub_, SEG font_put2_sub_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
	ASM_INLINE("MOV	SP,BP");
	ASM_INLINE("POP	BP");
}

void font_putN()
{
	ASM_INLINE("PUSH	BP");
	ASM_INLINE("MOV	BP,SP");
	ASM_INLINE("SUB	SP,0x000C");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	SI,AX");
	ASM_INLINE("MOV	DI,BX");
	ASM_INLINE("MOV	[BP-0x04].W,CX");
	ASM_INLINE("MOV	[BP-0x02].W,DX");
	ASM_INLINE("MOV	AX,[BP-0x04].W");
	ASM_INLINE("MOV	AX,[BP-0x02].W");
	ASM_INLINE("MOV	BX,AX");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("MOV	AX,BX");
	ASM_INLINE("XOR	DX,DX");
	ASM_INLINE("MOV	CX,[BP-0x04].W");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("ADD	CX,ES:[BX+0x0C].W");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("OR	DX,CX");
	ASM_INLINE("OR	AX,BX");
	ASM_INLINE("MOV	[BP-0x08].W,DX");
	ASM_INLINE("MOV	[BP-0x06].W,AX");
	ASM_INLINE("MOV	BX,[0x00F8].W");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("MOV	AX,BX");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("MOV	DX,[0x005E].W");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("OR	BX,DX");
	ASM_INLINE("OR	AX,CX");
	ASM_INLINE("MOV	[BP-0x0C].W,BX");
	ASM_INLINE("MOV	[BP-0x0A].W,AX");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,[BP-0x08].W");
	ASM_INLINE("MOV	BX,[BP-0x06].W");
	ASM_INLINE("SHL	SI,1");
	ASM_INLINE("SHL	SI,1");
	ASM_INLINE("SHL	SI,1");
	ASM_INLINE("SHL	SI,1");
	ASM_INLINE("ADD	AX,SI");
	ASM_INLINE("MOV	CX,[BP-0x0C].W");
	ASM_INLINE("MOV	DX,[BP-0x0A].W");
	ASM_INLINE("SHL	DI,1");
	ASM_INLINE("SHL	DI,1");
	ASM_INLINE("SHL	DI,1");
	ASM_INLINE("SHL	DI,1");
	ASM_INLINE("ADD	CX,DI");
	ASM_INLINE("CALLF	font_put2_sub_, SEG font_put2_sub_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
	ASM_INLINE("MOV	SP,BP");
	ASM_INLINE("POP	BP");
}

void put_energy_value(s16 unk1, s16 unk2)
{
	font_put2XY(0x38, unk1, 2, 1, 0x18, 0, 1, G_ENG_char_adr);
	font_put2XY(0x3a, unk2, 2, 1, 0x1a, 0, 1, G_ENG_char_adr);
}

void put_energy_level(s16 unk1, s16 unk2)
{
	u16 val;

	val = ((unk2 / 5) - 4) << 3;
	font_put2XY(val, unk1, 8, 1, 0x14, 1, 1, G_ENG_char_adr);
}

void put_turn_value(s16 val)
{  
	s16 div = val / 100;
	s16 mod = val % 100;

	if (val < 10)
	{
		font_put2XY(0, val, 3, 1, 0x11, 8, 1, G_TURN_char_adr);
	}
	else
	{
		font_put2XY(3, div, 1, 1, 0x11, 8, 1, G_TURN_char_adr);
		div = (mod / 0x14);
		mod = (mod % 0x14);
		font_put2XY(div * 2 + 4, mod, 2, 1, 0x12, 8, 1, G_TURN_char_adr);
	}
}

void put_turn_level(s16 val)
{
	font_put2XY(0, 10 + val, 4, 1, 0x10, 9, 1, G_TURN_char_adr);
}

void put_hp_level(s16 unk1, s16 unk2, s16 unk3)
{
	if (unk2 == 0xf)
	{
		unk2 = 0;
	}

	if(unk1 == 0)
	{
		font_put2XY(4 * (unk3 - 3), unk2 << 1, 4, 2, 0x10, 4, 1, G_HP_char_adr);
	}
	else
	{
		font_put2XY(4 * (unk3 - 3), unk2 << 1, 4, 2, 0x10, 0xe, 1, G_HP_char_adr);
	}
}

void put_function_name(s16 unk)
{
	s16 val;

	font_put2XY(0, unk << 1, 8, 2, 0x14, 6, 1, G_FUNC_char_adr);

	val = functbl[unk][1];
	if(9 < val)
	{
		font_put2XY(0xc + (val / 10), 0, 1, 2, 0x1a, 6, 1, G_FUNC_char_adr);
		val %= 10;
	}
	font_put2XY(0xc + val, 2, 1, 2, 0x1b, 6, 1, G_FUNC_char_adr);
}

void put_au_big(s16 unk1, s16 unk2)
{
	switch(unk2 / 20)
	{
		case 0:
		{
			if (unk1)
			{
				font_put2XY(unk2 << 2, 0, 4, 4, 0x10, 10, 1, G_AU1_char_adr);
				break;
			}
			else
			{
				font_put2XY(4 * unk2, 0, 4, 4, 0x10, 0, 1, G_AU1_char_adr);
				break;
			}
		}
		case 1:
		{
			if (unk1)
			{
				font_put2XY(4 * (unk2 - 20), 0, 4, 4, 0x10, 10, 1, G_AU2_char_adr);
				break;
			}
			else
			{
				font_put2XY(4 * (unk2 - 20), 0, 4, 4, 0x10, 0, 1, G_AU2_char_adr);
				break;
			}
		}
		case 2:
		{
			if (unk1)
			{
				font_put2XY(4 * (unk2 - 40), 0, 4, 4, 0x10, 10, 1, G_AU3_char_adr);
			}
			else
			{
				font_put2XY(4 * (unk2 - 40), 0, 4, 4, 0x10, 0, 1, G_AU3_char_adr);
			}
		}
		case 3:
		{
			break;
		}
	}
}

void load_au_small()
{
	font_put3; //Force include
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	CX,AX");
	ASM_INLINE("MOV	SI,BX");
	ASM_INLINE("MOV	AX,CX");
	ASM_INLINE("MOV	BX,0x0014");
	ASM_INLINE("CWD");
	ASM_INLINE("IDIV	BX");
	ASM_INLINE("CMP	AX,0x0003");
	ASM_INLINE("JNZ	_86D83");
	ASM_INLINE("JMP	_86F6B");
ASM_INLINE("_86D83:");
	ASM_INLINE("CMP	AX,0x0002");
	ASM_INLINE("JNZ	_86D8B");
	ASM_INLINE("JMP	_86ED0");
ASM_INLINE("_86D8B:");
	ASM_INLINE("CMP	AX,0x0001");
	ASM_INLINE("JNZ	_86D93");
	ASM_INLINE("JMP	_86E32");
ASM_INLINE("_86D93:");
	ASM_INLINE("TEST	AX,AX");
	ASM_INLINE("JZ	_86D9A");
	ASM_INLINE("JMP	_86F6B");
ASM_INLINE("_86D9A:");
	ASM_INLINE("XOR	DX,DX");
	ASM_INLINE("JMP	_86DDE");
ASM_INLINE("_86D9E:");
	ASM_INLINE("XOR	DI,DI");
	ASM_INLINE("JMP	_86DD8");
ASM_INLINE("_86DA2:");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	BX,G_AU1_char_adr_");
	ASM_INLINE("MOV	AX,SEG G_AU1_char_adr_");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,CX");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("ADD	AX,DI");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	BX,0x0004");
	ASM_INLINE("ADD	BX,DX");
	ASM_INLINE("MOV	AX,DX");
	ASM_INLINE("MOV	CX,0x001C");
	ASM_INLINE("MUL	CX");
	ASM_INLINE("ADD	AX,0x0070");
	ASM_INLINE("MOV	CX,SI");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("ADD	CX,DI");
	ASM_INLINE("ADD	CX,AX");
	ASM_INLINE("POP	AX");
	ASM_INLINE("CALLF	font_put3_, SEG font_put3_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("INC	DI");
	ASM_INLINE("POP	CX");
	ASM_INLINE("POP	DX");
ASM_INLINE("_86DD8:");
	ASM_INLINE("CMP	DI,0x0002");
	ASM_INLINE("JL	_86DA2");
	ASM_INLINE("INC	DX");
ASM_INLINE("_86DDE:");
	ASM_INLINE("CMP	DX,0x0003");
	ASM_INLINE("JL	_86D9E");
	ASM_INLINE("XOR	DX,DX");
	ASM_INLINE("JMP	_86E2A");
ASM_INLINE("_86DE7:");
	ASM_INLINE("XOR	DI,DI");
	ASM_INLINE("JMP	_86E24");
ASM_INLINE("_86DEB:");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	BX,G_AU1_char_adr_");
	ASM_INLINE("MOV	AX,SEG G_AU1_char_adr_");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,CX");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("ADD	AX,DI");
	ASM_INLINE("ADD	AX,0x0002");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	BX,0x0004");
	ASM_INLINE("ADD	BX,DX");
	ASM_INLINE("MOV	AX,DX");
	ASM_INLINE("MOV	CX,0x001C");
	ASM_INLINE("MUL	CX");
	ASM_INLINE("ADD	AX,0x00C4");
	ASM_INLINE("MOV	CX,SI");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("ADD	CX,DI");
	ASM_INLINE("ADD	CX,AX");
	ASM_INLINE("POP	AX");
	ASM_INLINE("CALLF	font_put3_, SEG font_put3_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("INC	DI");
	ASM_INLINE("POP	CX");
	ASM_INLINE("POP	DX");
ASM_INLINE("_86E24:");
	ASM_INLINE("CMP	DI,0x0002");
	ASM_INLINE("JL	_86DEB");
	ASM_INLINE("INC	DX");
ASM_INLINE("_86E2A:");
	ASM_INLINE("CMP	DX,0x0003");
	ASM_INLINE("JL	_86DE7");
	ASM_INLINE("JMP	_86F6B");
ASM_INLINE("_86E32:");
	ASM_INLINE("XOR	DX,DX");
	ASM_INLINE("JMP	_86E79");
ASM_INLINE("_86E36:");
	ASM_INLINE("XOR	DI,DI");
	ASM_INLINE("JMP	_86E73");
ASM_INLINE("_86E3A:");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	BX,G_AU2_char_adr_");
	ASM_INLINE("MOV	AX,SEG G_AU2_char_adr_");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,CX");
	ASM_INLINE("SUB	AX,0x0014");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("ADD	AX,DI");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	BX,0x0004");
	ASM_INLINE("ADD	BX,DX");
	ASM_INLINE("MOV	AX,DX");
	ASM_INLINE("MOV	CX,0x001C");
	ASM_INLINE("MUL	CX");
	ASM_INLINE("ADD	AX,0x0070");
	ASM_INLINE("MOV	CX,SI");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("ADD	CX,DI");
	ASM_INLINE("ADD	CX,AX");
	ASM_INLINE("POP	AX");
	ASM_INLINE("CALLF	font_put3_, SEG font_put3_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("INC	DI");
	ASM_INLINE("POP	CX");
	ASM_INLINE("POP	DX");
ASM_INLINE("_86E73:");
	ASM_INLINE("CMP	DI,0x0002");
	ASM_INLINE("JL	_86E3A");
	ASM_INLINE("INC	DX");
ASM_INLINE("_86E79:");
	ASM_INLINE("CMP	DX,0x0003");
	ASM_INLINE("JL	_86E36");
	ASM_INLINE("XOR	DX,DX");
	ASM_INLINE("JMP	_86EC8");
ASM_INLINE("_86E82:");
	ASM_INLINE("XOR	DI,DI");
	ASM_INLINE("JMP	_86EC2");
ASM_INLINE("_86E86:");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	BX,G_AU2_char_adr_");
	ASM_INLINE("MOV	AX,SEG G_AU2_char_adr_");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,CX");
	ASM_INLINE("SUB	AX,0x0014");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("ADD	AX,DI");
	ASM_INLINE("ADD	AX,0x0002");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	BX,0x0004");
	ASM_INLINE("ADD	BX,DX");
	ASM_INLINE("MOV	AX,DX");
	ASM_INLINE("MOV	DX,0x001C");
	ASM_INLINE("MUL	DX");
	ASM_INLINE("ADD	AX,0x00C4");
	ASM_INLINE("MOV	CX,SI");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("ADD	CX,DI");
	ASM_INLINE("ADD	CX,AX");
	ASM_INLINE("POP	AX");
	ASM_INLINE("CALLF	font_put3_, SEG font_put3_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("INC	DI");
	ASM_INLINE("POP	CX");
	ASM_INLINE("POP	DX");
ASM_INLINE("_86EC2:");
	ASM_INLINE("CMP	DI,0x0002");
	ASM_INLINE("JL	_86E86");
	ASM_INLINE("INC	DX");
ASM_INLINE("_86EC8:");
	ASM_INLINE("CMP	DX,0x0003");
	ASM_INLINE("JL	_86E82");
	ASM_INLINE("JMP	_86F6B");
ASM_INLINE("_86ED0:");
	ASM_INLINE("XOR	DX,DX");
	ASM_INLINE("JMP	_86F17");
ASM_INLINE("_86ED4:");
	ASM_INLINE("XOR	DI,DI");
	ASM_INLINE("JMP	_86F11");
ASM_INLINE("_86ED8:");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	BX,G_AU3_char_adr_");
	ASM_INLINE("MOV	AX,SEG G_AU3_char_adr_");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,CX");
	ASM_INLINE("SUB	AX,0x0028");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("ADD	AX,DI");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	BX,0x0004");
	ASM_INLINE("ADD	BX,DX");
	ASM_INLINE("MOV	AX,DX");
	ASM_INLINE("MOV	DX,0x001C");
	ASM_INLINE("MUL	DX");
	ASM_INLINE("ADD	AX,0x0070");
	ASM_INLINE("MOV	CX,SI");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("ADD	CX,DI");
	ASM_INLINE("ADD	CX,AX");
	ASM_INLINE("POP	AX");
	ASM_INLINE("CALLF	font_put3_, SEG font_put3_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("INC	DI");
	ASM_INLINE("POP	CX");
	ASM_INLINE("POP	DX");
ASM_INLINE("_86F11:");
	ASM_INLINE("CMP	DI,0x0002");
	ASM_INLINE("JL	_86ED8");
	ASM_INLINE("INC	DX");
ASM_INLINE("_86F17:");
	ASM_INLINE("CMP	DX,0x0003");
	ASM_INLINE("JL	_86ED4");
	ASM_INLINE("XOR	DX,DX");
	ASM_INLINE("JMP	_86F66");
ASM_INLINE("_86F20:");
	ASM_INLINE("XOR	DI,DI");
	ASM_INLINE("JMP	_86F60");
ASM_INLINE("_86F24:");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	BX,G_AU3_char_adr_");
	ASM_INLINE("MOV	AX,SEG G_AU3_char_adr_");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,CX");
	ASM_INLINE("SUB	AX,0x0028");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("ADD	AX,DI");
	ASM_INLINE("ADD	AX,0x0002");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	BX,0x0004");
	ASM_INLINE("ADD	BX,DX");
	ASM_INLINE("MOV	AX,DX");
	ASM_INLINE("MOV	DX,0x001C");
	ASM_INLINE("MUL	DX");
	ASM_INLINE("ADD	AX,0x00C4");
	ASM_INLINE("MOV	CX,SI");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("ADD	CX,DI");
	ASM_INLINE("ADD	CX,AX");
	ASM_INLINE("POP	AX");
	ASM_INLINE("CALLF	font_put3_, SEG font_put3_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("INC	DI");
	ASM_INLINE("POP	CX");
	ASM_INLINE("POP	DX");
ASM_INLINE("_86F60:");
	ASM_INLINE("CMP	DI,0x0002");
	ASM_INLINE("JL	_86F24");
	ASM_INLINE("INC	DX");
ASM_INLINE("_86F66:");
	ASM_INLINE("CMP	DX,0x0003");
	ASM_INLINE("JL	_86F20");
ASM_INLINE("_86F6B:");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
}

void put_au_small(u16 unk1, u16 unk2, u16 unk3, u16 unk4)
{
	s16 i;
	s16 j;

	for (i = 0; i < 3; i++)
	{
		for (j = 0; j < 2; j++)
		{
			put_sprite(
				(unk3 * 6) + 0x50 + (j + i * 2), 
				(j * 8) + unk1,
				(i * 8) + unk2 - 7,
				((unk3 * 2) + j + (0x70 + (unk4 * 3 + i) * 0x1c)) | 0x2000,
				4);
		}
	}
}

void field_fix()
{
	s16 i;
	s16 j;
	u16 val;
	u16 buf[4];
  
	for (i = 0; i < 2; i++)
	{
		for (j = 0; j < 2; j++)
		{
			buf[i * 2 + j] = (get_cell_no(j * 8, i * 8, 1) & 0xf1ff) | 0x800;
		}
	}
	for (i = 0; i < 8; i++)
	{
		for (j = 0; j < 8; j++)
		{
			put_cell_no(j * 16, i * 16, 1, buf[0]);
			put_cell_no(8 + j * 16, i * 16, 1, buf[1]);
			put_cell_no(j * 16, 8 + i * 16, 1, buf[2]);
			put_cell_no(8 + j * 16, 8 + i * 16, 1, buf[3]);
		}
	}
}

void field_test()
{
	s16 x;
	s16 y;

	for (y = 0; y < 0x10; y++)
	{
		for (x = 0; x < 0x10; x++)
		{
			put_cell_no(x * 8, y * 8, 1, ((y * 0x1c) + x) | 0x800);
		}
	}
}

void wall_space_make()
{
	memalloc; //Force include
	font_putN; //Force include
	get_bmp_cell_no; //Force include
	memfree; //Force include
	G_SPACE_char_adr; //Force include
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	AX,0x0060");
	ASM_INLINE("CALLF	memalloc_, SEG memalloc_");
	ASM_INLINE("MOV	SI,AX");
	ASM_INLINE("TEST	SI,SI");
	ASM_INLINE("JNZ	_87157");
	ASM_INLINE("JMP	_871FF");
ASM_INLINE("_87157:");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("JMP	_87184");
ASM_INLINE("_8715B:");
	ASM_INLINE("XOR	DI,DI");
	ASM_INLINE("JMP	_8717E");
ASM_INLINE("_8715F:");
	ASM_INLINE("MOV	AX,CX");
	ASM_INLINE("MOV	BX,0x001C");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("ADD	AX,0x016C");
	ASM_INLINE("ADD	AX,DI");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("ADD	BX,DI");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("ADD	BX,SI");
	ASM_INLINE("MOV	[BX].W,AX");
	ASM_INLINE("INC	DI");
ASM_INLINE("_8717E:");
	ASM_INLINE("CMP	DI,0x0010");
	ASM_INLINE("JL	_8715F");
	ASM_INLINE("INC	CX");
ASM_INLINE("_87184:");
	ASM_INLINE("CMP	CX,0x0003");
	ASM_INLINE("JL	_8715B");
	ASM_INLINE("XOR	DI,DI");
	ASM_INLINE("JMP	_871A3");
ASM_INLINE("_8718D:");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("ADD	BX,SI");
	ASM_INLINE("MOV	BX,[BX].W");
	ASM_INLINE("MOV	CX,G_SPACE_char_adr_");
	ASM_INLINE("MOV	DX,SEG G_SPACE_char_adr_");
	ASM_INLINE("CALLF	font_putN_, SEG font_putN_");
	ASM_INLINE("INC	DI");
ASM_INLINE("_871A3:");
	ASM_INLINE("CMP	DI,0x0030");
	ASM_INLINE("JL	_8718D");
	ASM_INLINE("XOR	DI,DI");
	ASM_INLINE("JMP	_871F3");
ASM_INLINE("_871AC:");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("JMP	_871ED");
ASM_INLINE("_871B0:");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("MOV	CX,G_SPACE_char_adr_");
	ASM_INLINE("MOV	DX,SEG G_SPACE_char_adr_");
	ASM_INLINE("CALLF	get_bmp_cell_no_, SEG get_bmp_cell_no_");
	ASM_INLINE("MOV	DX,AX");
	ASM_INLINE("MOV	BX,DX");
	ASM_INLINE("AND	BX,0x01FF");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("ADD	BX,SI");
	ASM_INLINE("AND	DX,0xC000");
	ASM_INLINE("OR	DX,0x0600");
	ASM_INLINE("OR	DX,[BX].W");
	ASM_INLINE("POP	AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("CALLF	put_cell_no_, SEG put_cell_no_");
	ASM_INLINE("POP	AX");
	ASM_INLINE("INC	AX");
ASM_INLINE("_871ED:");
	ASM_INLINE("CMP	AX,0x0020");
	ASM_INLINE("JL	_871B0");
	ASM_INLINE("INC	DI");
ASM_INLINE("_871F3:");
	ASM_INLINE("CMP	DI,0x0020");
	ASM_INLINE("JL	_871AC");
	ASM_INLINE("MOV	AX,SI");
	ASM_INLINE("CALLF	memfree_, SEG memfree_");
ASM_INLINE("_871FF:");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
}

void put_function(s16 *unk)
{
	s16 i;
	s16 val;

	for (i = 0; i < 4; i++)
	{
		val = *unk++;
		if (val != -1)
		{
			font_put2XY(8, val << 1, 2, 2, i * 2 + 0x14, 2, 1, G_FUNC_char_adr);
		}
	}
	
	for (i = 0; i < 4; i++)
	{
		val = *unk++;
		if (val != -1)
		{
			font_put2XY(8, val << 1, 2, 2, i * 2 + 0x14, 4, 1, G_FUNC_char_adr);
		}
	}
}

void put_function_cousor(u16 unk1, u16 unk2, u16 unk3, u16 unk4, u16 unk5, u16 unk6)
{
	if (unk6)
	{
		font_put2XY(10, unk5 << 1, 2, 2, unk1 * 2 + 0x14, unk2 * 2 + 2, 1, G_FUNC_char_adr);
	}
	else
	{
		font_put2XY(8, unk5 << 1, 2, 2, unk1 * 2 + 0x14, unk2 * 2 + 2, 1, G_FUNC_char_adr);
	}
}
static void near unk_872F8(u16 unk1, u16 unk2, u16 unk3)
{
	u16 val;

	val = 2 * (unk3 & 7) + 2 * (unk3 >> 3) * 0x1C | unk3 & 0xfe00;
	put_cell_no(unk1 << 4, unk2 << 4, 1, val);
	put_cell_no(unk1 * 0x10 + 8, unk2 << 4, 1, val + 1);
	put_cell_no(unk1 << 4, unk2 * 0x10 + 8, 1, val + 0x1c);
	put_cell_no(unk1 * 0x10 + 8, unk2 * 0x10 + 8, 1, val + 0x1d);
}

static void near unk_873AD(struct MGameWork *work, u16 unk1, u16 unk2)
{
/*	//FIX: Reg Alloc DX vs DI
	u8 *ptr;

	ptr = work->unkB4 + (unk2 * 8 + unk1);

	switch(*ptr >> 5)
	{
		case 7:
		{
			unk_872F8(unk1, unk2, 7);
			break;
		}
		case 6:
		{
			unk_872F8(unk1, unk2, 6);
			break;
		}
		case 5:
		{
			unk_872F8(unk1, unk2, 5);
			break;
		}
		case 4:
		{
			unk_872F8(unk1, unk2, 4);
			break;
		}
		case 3:
		{
			unk_872F8(unk1, unk2, 8);
			break;
		}
		case 2:
		{
			unk_872F8(unk1, unk2, 9);
			break;
		}
		case 1:
		{
			unk_872F8(unk1, unk2, 2);
			break;
		}
		case 0:
		{
			switch(*ptr >> 3)
			{
				case 3:
				{
					unk_872F8(unk1, unk2, 0x80a);
					break;
				}
				case 2:
				{
					unk_872F8(unk1, unk2, 0x80b);
					break;
				}
				case 1:
				{
					unk_872F8(unk1, unk2, 0x80d);
					break;
				}
				case 0:
				{
					switch(*ptr >> 1)
					{
						case 3:
						{
							unk_872F8(unk1, unk2, 1);
							break;
						}
						case 2:
						{
							unk_872F8(unk1, unk2, 2);
							break;
						}
						case 1:
						{
							unk_872F8(unk1, unk2, 3);
							break;
						}
						case 0:
						{
							switch(*ptr)
							{
								case 3:
								case 2:
								case 1:
								{
									unk_872F8(unk1, unk2, 2);
									break;
								}
								case 0:
								{
									unk_872F8(unk1, unk2, 0x800);
									break;
								}
							}
							break;
						}
					}
					break;
				}
			}
			break;
		}
	}
*/		
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	SI,AX");
	ASM_INLINE("MOV	AX,BX");
	ASM_INLINE("MOV	DI,CX");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("ADD	BX,AX");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("ADD	SI,0x00B4");
	ASM_INLINE("ADD	SI,BX");
	ASM_INLINE("MOV	BL,[SI].B");
	ASM_INLINE("MOV	CL,0x05");
	ASM_INLINE("SHR	BL,CL");
	ASM_INLINE("TEST	BL,BL");
	ASM_INLINE("JZ	_87445");
	ASM_INLINE("CMP	BL,0x01");
	ASM_INLINE("JZ	_8743A");
	ASM_INLINE("CMP	BL,0x02");
	ASM_INLINE("JZ	_8742F");
	ASM_INLINE("CMP	BL,0x03");
	ASM_INLINE("JZ	_87424");
	ASM_INLINE("CMP	BL,0x04");
	ASM_INLINE("JZ	_87419");
	ASM_INLINE("CMP	BL,0x05");
	ASM_INLINE("JZ	_8740E");
	ASM_INLINE("CMP	BL,0x06");
	ASM_INLINE("JZ	_87403");
	ASM_INLINE("CMP	BL,0x07");
	ASM_INLINE("JZ	_873F8");
	ASM_INLINE("JMP	_874DA");
ASM_INLINE("_873F8:");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("MOV	CX,0x0007");
	ASM_INLINE("CALL	unk_872F8_");
	ASM_INLINE("JMP	_874DA");
ASM_INLINE("_87403:");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("MOV	CX,0x0006");
	ASM_INLINE("CALL	unk_872F8_");
	ASM_INLINE("JMP	_874DA");
ASM_INLINE("_8740E:");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("MOV	CX,0x0005");
	ASM_INLINE("CALL	unk_872F8_");
	ASM_INLINE("JMP	_874DA");
ASM_INLINE("_87419:");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("MOV	CX,0x0004");
	ASM_INLINE("CALL	unk_872F8_");
	ASM_INLINE("JMP	_874DA");
ASM_INLINE("_87424:");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("MOV	CX,0x0008");
	ASM_INLINE("CALL	unk_872F8_");
	ASM_INLINE("JMP	_874DA");
ASM_INLINE("_8742F:");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("MOV	CX,0x0009");
	ASM_INLINE("CALL	unk_872F8_");
	ASM_INLINE("JMP	_874DA");
ASM_INLINE("_8743A:");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("MOV	CX,0x0002");
	ASM_INLINE("CALL	unk_872F8_");
	ASM_INLINE("JMP	_874DA");
ASM_INLINE("_87445:");
	ASM_INLINE("MOV	BL,[SI].B");
	ASM_INLINE("SHR	BL,1");
	ASM_INLINE("SHR	BL,1");
	ASM_INLINE("SHR	BL,1");
	ASM_INLINE("TEST	BL,BL");
	ASM_INLINE("JZ	_8747E");
	ASM_INLINE("CMP	BL,0x01");
	ASM_INLINE("JZ	_87474");
	ASM_INLINE("CMP	BL,0x02");
	ASM_INLINE("JZ	_8746A");
	ASM_INLINE("CMP	BL,0x03");
	ASM_INLINE("JNZ	_874DA");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("MOV	CX,0x080A");
	ASM_INLINE("CALL	unk_872F8_");
	ASM_INLINE("JMP	_874DA");
ASM_INLINE("_8746A:");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("MOV	CX,0x080B");
	ASM_INLINE("CALL	unk_872F8_");
	ASM_INLINE("JMP	_874DA");
ASM_INLINE("_87474:");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("MOV	CX,0x080D");
	ASM_INLINE("CALL	unk_872F8_");
	ASM_INLINE("JMP	_874DA");
ASM_INLINE("_8747E:");
	ASM_INLINE("MOV	BL,[SI].B");
	ASM_INLINE("SHR	BL,1");
	ASM_INLINE("TEST	BL,BL");
	ASM_INLINE("JZ	_874B3");
	ASM_INLINE("CMP	BL,0x01");
	ASM_INLINE("JZ	_874A9");
	ASM_INLINE("CMP	BL,0x02");
	ASM_INLINE("JZ	_8749F");
	ASM_INLINE("CMP	BL,0x03");
	ASM_INLINE("JNZ	_874DA");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("CALL	unk_872F8_");
	ASM_INLINE("JMP	_874DA");
ASM_INLINE("_8749F:");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("MOV	CX,0x0002");
	ASM_INLINE("CALL	unk_872F8_");
	ASM_INLINE("JMP	_874DA");
ASM_INLINE("_874A9:");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("MOV	CX,0x0003");
	ASM_INLINE("CALL	unk_872F8_");
	ASM_INLINE("JMP	_874DA");
ASM_INLINE("_874B3:");
	ASM_INLINE("MOV	BL,[SI].B");
	ASM_INLINE("TEST	BL,BL");
	ASM_INLINE("JZ	_874D2");
	ASM_INLINE("CMP	BL,0x01");
	ASM_INLINE("JZ	_874C8");
	ASM_INLINE("CMP	BL,0x02");
	ASM_INLINE("JZ	_874C8");
	ASM_INLINE("CMP	BL,0x03");
	ASM_INLINE("JNZ	_874DA");
ASM_INLINE("_874C8:");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("MOV	CX,0x0002");
	ASM_INLINE("CALL	unk_872F8_");
	ASM_INLINE("JMP	_874DA");
ASM_INLINE("_874D2:");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("MOV	CX,0x0800");
	ASM_INLINE("CALL	unk_872F8_");
ASM_INLINE("_874DA:");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	CX");
}

static void near unk_874DE(struct MGameWork *work, s16 unk1, s16 unk2, s16 unk3)
{
	u8 *ptr;
	s16 val1;
	s16 val3;
	u16 val2;

	ptr = (u8 *)(work->unkB4 + (unk2 * 8 + unk1)) + 1;
	val1 = *ptr & 0x7f;
	val2 = unk3 & 0x1ff;
	if ((val2 < 4) && ((*ptr & 0x80) != 0))
	{
		if (val1 < 10)
		{
			val2 *= 20;
			val2 += 0x10;
			val2 += val1;
		}
		else
		{
			val3 = val1 / 10;
			val2 *= 20;
			val2 += 0x1A;
			val2 += val3;
		}
	}
	font_put2XY(val2 & 0xf, (val2 / 16) + 10, 1, 1, 20 + unk1, 8 + unk2, 1, G_GAME_char_adr);
}

static void near unk_87577(struct MGameWork *work, s16 unk1, s16 unk2)
{
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	DI,CX");
	ASM_INLINE("MOV	CX,DI");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("ADD	CX,BX");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("MOV	SI,AX");
	ASM_INLINE("ADD	SI,0x00B4");
	ASM_INLINE("ADD	SI,CX");
	ASM_INLINE("MOV	DL,[SI].B");
	ASM_INLINE("MOV	CL,0x05");
	ASM_INLINE("SHR	DL,CL");
	ASM_INLINE("TEST	DL,DL");
	ASM_INLINE("JZ	_8760E");
	ASM_INLINE("CMP	DL,0x01");
	ASM_INLINE("JZ	_87603");
	ASM_INLINE("CMP	DL,0x02");
	ASM_INLINE("JZ	_875F8");
	ASM_INLINE("CMP	DL,0x03");
	ASM_INLINE("JZ	_875ED");
	ASM_INLINE("CMP	DL,0x04");
	ASM_INLINE("JZ	_875E2");
	ASM_INLINE("CMP	DL,0x05");
	ASM_INLINE("JZ	_875D7");
	ASM_INLINE("CMP	DL,0x06");
	ASM_INLINE("JZ	_875CC");
	ASM_INLINE("CMP	DL,0x07");
	ASM_INLINE("JZ	_875C1");
	ASM_INLINE("JMP	_876A2");
ASM_INLINE("_875C1:");
	ASM_INLINE("MOV	CX,DI");
	ASM_INLINE("MOV	DX,0x0007");
	ASM_INLINE("CALL	unk_874DE_");
	ASM_INLINE("JMP	_876A2");
ASM_INLINE("_875CC:");
	ASM_INLINE("MOV	CX,DI");
	ASM_INLINE("MOV	DX,0x0006");
	ASM_INLINE("CALL	unk_874DE_");
	ASM_INLINE("JMP	_876A2");
ASM_INLINE("_875D7:");
	ASM_INLINE("MOV	CX,DI");
	ASM_INLINE("MOV	DX,0x0005");
	ASM_INLINE("CALL	unk_874DE_");
	ASM_INLINE("JMP	_876A2");
ASM_INLINE("_875E2:");
	ASM_INLINE("MOV	CX,DI");
	ASM_INLINE("MOV	DX,0x0004");
	ASM_INLINE("CALL	unk_874DE_");
	ASM_INLINE("JMP	_876A2");
ASM_INLINE("_875ED:");
	ASM_INLINE("MOV	CX,DI");
	ASM_INLINE("MOV	DX,0x0008");
	ASM_INLINE("CALL	unk_874DE_");
	ASM_INLINE("JMP	_876A2");
ASM_INLINE("_875F8:");
	ASM_INLINE("MOV	CX,DI");
	ASM_INLINE("MOV	DX,0x0009");
	ASM_INLINE("CALL	unk_874DE_");
	ASM_INLINE("JMP	_876A2");
ASM_INLINE("_87603:");
	ASM_INLINE("MOV	CX,DI");
	ASM_INLINE("MOV	DX,0x0002");
	ASM_INLINE("CALL	unk_874DE_");
	ASM_INLINE("JMP	_876A2");
ASM_INLINE("_8760E:");
	ASM_INLINE("MOV	CL,[SI].B");
	ASM_INLINE("SHR	CL,1");
	ASM_INLINE("SHR	CL,1");
	ASM_INLINE("SHR	CL,1");
	ASM_INLINE("TEST	CL,CL");
	ASM_INLINE("JZ	_87647");
	ASM_INLINE("CMP	CL,0x01");
	ASM_INLINE("JZ	_8763D");
	ASM_INLINE("CMP	CL,0x02");
	ASM_INLINE("JZ	_87633");
	ASM_INLINE("CMP	CL,0x03");
	ASM_INLINE("JNZ	_876A2");
	ASM_INLINE("MOV	CX,DI");
	ASM_INLINE("MOV	DX,0x000A");
	ASM_INLINE("CALL	unk_874DE_");
	ASM_INLINE("JMP	_876A2");
ASM_INLINE("_87633:");
	ASM_INLINE("MOV	CX,DI");
	ASM_INLINE("MOV	DX,0x000B");
	ASM_INLINE("CALL	unk_874DE_");
	ASM_INLINE("JMP	_876A2");
ASM_INLINE("_8763D:");
	ASM_INLINE("MOV	CX,DI");
	ASM_INLINE("MOV	DX,0x000D");
	ASM_INLINE("CALL	unk_874DE_");
	ASM_INLINE("JMP	_876A2");
ASM_INLINE("_87647:");
	ASM_INLINE("MOV	CL,[SI].B");
	ASM_INLINE("SHR	CL,1");
	ASM_INLINE("TEST	CL,CL");
	ASM_INLINE("JZ	_8767C");
	ASM_INLINE("CMP	CL,0x01");
	ASM_INLINE("JZ	_87672");
	ASM_INLINE("CMP	CL,0x02");
	ASM_INLINE("JZ	_87668");
	ASM_INLINE("CMP	CL,0x03");
	ASM_INLINE("JNZ	_876A2");
	ASM_INLINE("MOV	CX,DI");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALL	unk_874DE_");
	ASM_INLINE("JMP	_876A2");
ASM_INLINE("_87668:");
	ASM_INLINE("MOV	CX,DI");
	ASM_INLINE("MOV	DX,0x0002");
	ASM_INLINE("CALL	unk_874DE_");
	ASM_INLINE("JMP	_876A2");
ASM_INLINE("_87672:");
	ASM_INLINE("MOV	CX,DI");
	ASM_INLINE("MOV	DX,0x0003");
	ASM_INLINE("CALL	unk_874DE_");
	ASM_INLINE("JMP	_876A2");
ASM_INLINE("_8767C:");
	ASM_INLINE("MOV	CL,[SI].B");
	ASM_INLINE("TEST	CL,CL");
	ASM_INLINE("JZ	_8769B");
	ASM_INLINE("CMP	CL,0x01");
	ASM_INLINE("JZ	_87691");
	ASM_INLINE("CMP	CL,0x02");
	ASM_INLINE("JZ	_87691");
	ASM_INLINE("CMP	CL,0x03");
	ASM_INLINE("JNZ	_876A2");
ASM_INLINE("_87691:");
	ASM_INLINE("MOV	CX,DI");
	ASM_INLINE("MOV	DX,0x0002");
	ASM_INLINE("CALL	unk_874DE_");
	ASM_INLINE("JMP	_876A2");
ASM_INLINE("_8769B:");
	ASM_INLINE("MOV	CX,DI");
	ASM_INLINE("XOR	DX,DX");
	ASM_INLINE("CALL	unk_874DE_");
ASM_INLINE("_876A2:");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
}

void put_rader_cousor(struct MGameWork *work, s16 unk1, s16 unk2, s16 unk3, s16 unk4)
{
/*	u8 *ptr;
	u16 val;

	ptr = (u8 *)(work->unkB4 + (unk2 * 8 + unk1));
	if (unk3 != -1)
	{
		if (unk4)
		{
			*ptr |= unk3;
		}
		else
		{
			*ptr &= ‾unk3;
		}
		unk_873AD(work, unk1, unk2);
	}
	unk_87577(work, unk1, unk2);
*/
	ASM_INLINE("PUSH	BP");
	ASM_INLINE("MOV	BP,SP");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	DI,AX");
	ASM_INLINE("MOV	SI,BX");
	ASM_INLINE("MOV	AX,CX");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("ADD	AX,SI");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("ADD	BX,0x00B4");
	ASM_INLINE("ADD	BX,AX");
	ASM_INLINE("CMP	DX,-0x0001");
	ASM_INLINE("JZ	_876E0");
	ASM_INLINE("CMP	[BP+0x06].W,0x0000");
	ASM_INLINE("JZ	_876D3");
	ASM_INLINE("OR	[BX].B,DL");
	ASM_INLINE("JMP	_876D9");
ASM_INLINE("_876D3:");
	ASM_INLINE("MOV	AX,DX");
	ASM_INLINE("NOT	AX");
	ASM_INLINE("AND	[BX].B,AL");
ASM_INLINE("_876D9:");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("CALL	unk_873AD_");
ASM_INLINE("_876E0:");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("CALL	unk_87577_");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	BP");
}

void put_lange_cousor()
{
	put_rader_cousor; //Force include
	lange_tbl; //Force include
	ASM_INLINE("PUSH	BP");
	ASM_INLINE("MOV	BP,SP");
	ASM_INLINE("SUB	SP,0x0004");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	SI,AX");
	ASM_INLINE("MOV	DI,BX");
	ASM_INLINE("MOV	AX,CX");
	ASM_INLINE("MOV	BX,DX");
	ASM_INLINE("MOV	CX,SEG lange_tbl_");
	ASM_INLINE("MOV	ES,CX");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	//ASM_INLINE("MOV	CX,ES:[BX+0x0004].W");
	ASM_OP5(0x26,0x8B,0x8F,0x04,0x00);
	//ASM_INLINE("MOV	BX,ES:[BX+0x0006].W");
	ASM_OP5(0x26,0x8B,0x9F,0x06,0x00);
	ASM_INLINE("MOV	[BP-0x04].W,CX");
	ASM_INLINE("MOV	[BP-0x02].W,BX");
	ASM_INLINE("XOR	DX,DX");
	ASM_INLINE("JMP	_87764");
ASM_INLINE("_8771A:");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("JMP	_8775E");
ASM_INLINE("_8771E:");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	CX,DX");
	ASM_INLINE("SUB	CX,AX");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("ADD	CX,0x0070");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("ADD	BX,CX");
	ASM_INLINE("POP	CX");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("SUB	CX,DI");
	ASM_INLINE("ADD	CX,0x0007");
	ASM_INLINE("ADD	BX,CX");
	ASM_INLINE("CMP	ES:[BX].B,0x00");
	ASM_INLINE("POP	CX");
	ASM_INLINE("JZ	_8775C");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	[BP+0x06].W");
	ASM_INLINE("MOV	AX,SI");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("MOV	CX,DX");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALLF	put_rader_cousor_, SEG put_rader_cousor_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
ASM_INLINE("_8775C:");
	ASM_INLINE("INC	CX");
	ASM_INLINE("POP	AX");
ASM_INLINE("_8775E:");
	ASM_INLINE("CMP	CX,0x0008");
	ASM_INLINE("JL	_8771E");
	ASM_INLINE("INC	DX");
ASM_INLINE("_87764:");
	ASM_INLINE("CMP	DX,0x0008");
	ASM_INLINE("JL	_8771A");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
	ASM_INLINE("MOV	SP,BP");
	ASM_INLINE("POP	BP");
}

void put_atack_cousor()
{
	atack_tbl; //Force include
	ASM_INLINE("PUSH	BP");
	ASM_INLINE("MOV	BP,SP");
	ASM_INLINE("SUB	SP,0x0004");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	DI,AX");
	ASM_INLINE("MOV	SI,BX");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	BX,DX");
	ASM_INLINE("MOV	AX,SEG atack_tbl_");
	ASM_INLINE("MOV	ES,AX");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	//ASM_INLINE("MOV	AX,ES:[BX+0x0008].W");
	ASM_OP5(0x26,0x8B,0x87,0x08,0x00);
	//ASM_INLINE("MOV	CX,ES:[BX+0x000A].W");
	ASM_OP5(0x26,0x8B,0x8F,0x0A,0x00);
	ASM_INLINE("MOV	[BP-0x04].W,AX");
	ASM_INLINE("MOV	[BP-0x02].W,CX");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("POP	BX");
	ASM_INLINE("JMP	_8781B");
ASM_INLINE("_877A2:");
	ASM_INLINE("XOR	DX,DX");
	ASM_INLINE("JMP	_87815");
ASM_INLINE("_877A6:");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,CX");
	ASM_INLINE("SUB	AX,BX");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("ADD	AX,0x0070");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("ADD	BX,AX");
	ASM_INLINE("MOV	AX,DX");
	ASM_INLINE("SUB	AX,SI");
	ASM_INLINE("ADD	AX,0x0007");
	ASM_INLINE("ADD	BX,AX");
	ASM_INLINE("MOV	AL,ES:[BX].B");
	ASM_INLINE("CMP	AL,0x03");
	ASM_INLINE("JZ	_877FF");
	ASM_INLINE("CMP	AL,0x02");
	ASM_INLINE("JZ	_877E9");
	ASM_INLINE("CMP	AL,0x01");
	ASM_INLINE("JNZ	_87813");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	[BP+0x06].W");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("MOV	BX,DX");
	ASM_INLINE("MOV	DX,0x0006");
	ASM_INLINE("CALLF	put_rader_cousor_, SEG put_rader_cousor_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("POP	DX");
	ASM_INLINE("JMP	_87813");
ASM_INLINE("_877E9:");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	[BP+0x06].W");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("MOV	BX,DX");
	ASM_INLINE("MOV	DX,0x0004");
	ASM_INLINE("CALLF	put_rader_cousor_, SEG put_rader_cousor_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("POP	DX");
	ASM_INLINE("JMP	_87813");
ASM_INLINE("_877FF:");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	[BP+0x06].W");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("MOV	BX,DX");
	ASM_INLINE("MOV	DX,0x0002");
	ASM_INLINE("CALLF	put_rader_cousor_, SEG put_rader_cousor_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("POP	DX");
ASM_INLINE("_87813:");
	ASM_INLINE("INC	DX");
	ASM_INLINE("POP	BX");
ASM_INLINE("_87815:");
	ASM_INLINE("CMP	DX,0x0008");
	ASM_INLINE("JL	_877A6");
	ASM_INLINE("INC	CX");
ASM_INLINE("_8781B:");
	ASM_INLINE("CMP	CX,0x0008");
	ASM_INLINE("JL	_877A2");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
	ASM_INLINE("MOV	SP,BP");
	ASM_INLINE("POP	BP");
}

void put_atack_cousorON()
{
	ASM_INLINE("PUSH	BP");
	ASM_INLINE("MOV	BP,SP");
	ASM_INLINE("SUB	SP,0x0004");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	DI,AX");
	ASM_INLINE("MOV	SI,BX");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	BX,DX");
	ASM_INLINE("MOV	AX,SEG atack_tbl_");
	ASM_INLINE("MOV	ES,AX");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	//ASM_INLINE("MOV	AX,ES:[BX+0x0008].W");
	ASM_OP5(0x26,0x8B,0x87,0x08,0x00);
	//ASM_INLINE("MOV	CX,ES:[BX+0x000A].W");
	ASM_OP5(0x26,0x8B,0x8F,0x0A,0x00);
	ASM_INLINE("MOV	[BP-0x04].W,AX");
	ASM_INLINE("MOV	[BP-0x02].W,CX");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("POP	BX");
	ASM_INLINE("JMP	_878D2");
ASM_INLINE("_87859:");
	ASM_INLINE("XOR	DX,DX");
	ASM_INLINE("JMP	_878CC");
ASM_INLINE("_8785D:");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,CX");
	ASM_INLINE("SUB	AX,BX");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("ADD	AX,0x0070");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("ADD	BX,AX");
	ASM_INLINE("MOV	AX,DX");
	ASM_INLINE("SUB	AX,SI");
	ASM_INLINE("ADD	AX,0x0007");
	ASM_INLINE("ADD	BX,AX");
	ASM_INLINE("MOV	AL,ES:[BX].B");
	ASM_INLINE("CMP	AL,0x03");
	ASM_INLINE("JZ	_878B6");
	ASM_INLINE("CMP	AL,0x02");
	ASM_INLINE("JZ	_878A0");
	ASM_INLINE("CMP	AL,0x01");
	ASM_INLINE("JNZ	_878CA");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	[BP+0x06].W");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("MOV	BX,DX");
	ASM_INLINE("MOV	DX,0x0018");
	ASM_INLINE("CALLF	put_rader_cousor_, SEG put_rader_cousor_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("POP	DX");
	ASM_INLINE("JMP	_878CA");
ASM_INLINE("_878A0:");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	[BP+0x06].W");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("MOV	BX,DX");
	ASM_INLINE("MOV	DX,0x0010");
	ASM_INLINE("CALLF	put_rader_cousor_, SEG put_rader_cousor_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("POP	DX");
	ASM_INLINE("JMP	_878CA");
ASM_INLINE("_878B6:");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	[BP+0x06].W");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("MOV	BX,DX");
	ASM_INLINE("MOV	DX,0x0008");
	ASM_INLINE("CALLF	put_rader_cousor_, SEG put_rader_cousor_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("POP	DX");
ASM_INLINE("_878CA:");
	ASM_INLINE("INC	DX");
	ASM_INLINE("POP	BX");
ASM_INLINE("_878CC:");
	ASM_INLINE("CMP	DX,0x0008");
	ASM_INLINE("JL	_8785D");
	ASM_INLINE("INC	CX");
ASM_INLINE("_878D2:");
	ASM_INLINE("CMP	CX,0x0008");
	ASM_INLINE("JL	_87859");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
	ASM_INLINE("MOV	SP,BP");
	ASM_INLINE("POP	BP");
}

void put_move_cousor(struct MGameWork *work, s16 unk1, s16 unk2, s16 unk3, s16 unk4)
{
	s16 i;

	for (i = 0; i < unk3; i++)
	{
		if (i < unk1)
		{
			put_rader_cousor(work,unk1 - (i + 1),unk2,0x80,unk4);
		}
		if (unk1 < 7 - i)
		{
			put_rader_cousor(work,i + 1 + unk1,unk2,0xa0,unk4);
		}
		if (i < unk2)
		{
			put_rader_cousor(work,unk1,unk2 - (i + 1),0xc0,unk4);
		}
		if (unk2 < 7 - i)
		{
			put_rader_cousor(work,unk1,i + 1 + unk2,0xe0,unk4);
		}
	}
}

void put_search_cousor()
{
	search_tbl; //Force include
	ASM_INLINE("PUSH	BP");
	ASM_INLINE("MOV	BP,SP");
	ASM_INLINE("SUB	SP,0x0006");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	SI,AX");
	ASM_INLINE("MOV	DI,BX");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	BX,DX");
	ASM_INLINE("MOV	AX,SEG search_tbl_");
	ASM_INLINE("MOV	ES,AX");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	//ASM_INLINE("MOV	AX,ES:[BX+0x000C].W");
	ASM_OP5(0x26,0x8B,0x87,0x0C,0x00);
	//ASM_INLINE("MOV	CX,ES:[BX+0x000E].W");
	ASM_OP5(0x26,0x8B,0x8F,0x0E,0x00);
	ASM_INLINE("MOV	[BP-0x04].W,AX");
	ASM_INLINE("MOV	[BP-0x02].W,CX");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("POP	BX");
	ASM_INLINE("JMP	_87A02");
ASM_INLINE("_879B2:");
	ASM_INLINE("MOV	[BP-0x06].W,0x0000");
	ASM_INLINE("JMP	_879FB");
ASM_INLINE("_879B9:");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	AX,CX");
	ASM_INLINE("SUB	AX,BX");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("ADD	AX,0x0070");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("ADD	BX,AX");
	ASM_INLINE("MOV	AX,[BP-0x06].W");
	ASM_INLINE("SUB	AX,DI");
	ASM_INLINE("ADD	AX,0x0007");
	ASM_INLINE("ADD	BX,AX");
	ASM_INLINE("MOV	DL,ES:[BX].B");
	ASM_INLINE("MOV	CL,0x05");
	ASM_INLINE("SHL	DL,CL");
	ASM_INLINE("TEST	DL,DL");
	ASM_INLINE("POP	CX");
	ASM_INLINE("JZ	_879F7");
	ASM_INLINE("PUSH	[BP+0x06].W");
	ASM_INLINE("MOV	AX,SI");
	ASM_INLINE("MOV	BX,[BP-0x06].W");
	ASM_INLINE("XOR	DH,DH");
	ASM_INLINE("CALLF	put_rader_cousor_, SEG put_rader_cousor_");
	ASM_INLINE("ADD	SP,0x0002");
ASM_INLINE("_879F7:");
	ASM_INLINE("INC	[BP-0x06].W");
	ASM_INLINE("POP	BX");
ASM_INLINE("_879FB:");
	ASM_INLINE("CMP	[BP-0x06].W,0x0008");
	ASM_INLINE("JL	_879B9");
	ASM_INLINE("INC	CX");
ASM_INLINE("_87A02:");
	ASM_INLINE("CMP	CX,0x0008");
	ASM_INLINE("JL	_879B2");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
	ASM_INLINE("MOV	SP,BP");
	ASM_INLINE("POP	BP");
}

s16 get_lange_test(u16 unk1, u16 unk2, u16 unk3, u16 unk4, u16 unk5)
{
	/*s16 ret;

	if (lange_tbl[unk5][ (unk4 - unk2) * 0x10 + (unk3 - unk1)] == 0)
	{
		ret = -1;
	}
	else
	{
		ret = 0;
	}
	return ret;*/
	ASM_INLINE("PUSH	BP");
	ASM_INLINE("MOV	BP,SP");
	ASM_INLINE("SUB	SP,0x0004");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	DI,AX");
	ASM_INLINE("MOV	SI,BX");
	ASM_INLINE("MOV	AX,SEG lange_tbl_");
	ASM_INLINE("MOV	ES,AX");
	ASM_INLINE("MOV	BX,[BP+0x06].W");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	//ASM_INLINE("MOV	AX,ES:[BX+0x0004].W");
	ASM_OP5(0x26,0x8B,0x87,0x04,0x00);
	//ASM_INLINE("MOV	BX,ES:[BX+0x0006].W");
	ASM_OP5(0x26,0x8B,0x9F,0x06,0x00);
	ASM_INLINE("MOV	[BP-0x04].W,AX");
	ASM_INLINE("MOV	[BP-0x02].W,BX");
	ASM_INLINE("SUB	DX,SI");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("ADD	DX,0x0070");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("ADD	BX,DX");
	ASM_INLINE("SUB	CX,DI");
	ASM_INLINE("ADD	CX,0x0007");
	ASM_INLINE("ADD	BX,CX");
	ASM_INLINE("CMP	ES:[BX].B,0x00");
	ASM_INLINE("JZ	_87A5C");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("JMP	_87A5F");
ASM_INLINE("_87A5C:");
	ASM_INLINE("MOV	AX,0xFFFF");
ASM_INLINE("_87A5F:");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
	ASM_INLINE("MOV	SP,BP");
	ASM_INLINE("POP	BP");
}

void put_search_hit_check()
{
	rand; //Force include
	ASM_INLINE("PUSH	BP");
	ASM_INLINE("MOV	BP,SP");
	ASM_INLINE("SUB	SP,0x0008");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	DI,AX");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	SI,0x0000");
	ASM_INLINE("MOV	AX,SEG functbl_");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("ADD	SI,DX");
	ASM_INLINE("MOV	[BP-0x04].W,SI");
	ASM_INLINE("MOV	[BP-0x02].W,AX");
	ASM_INLINE("LES	SI,[BP-0x04]");
	ASM_INLINE("MOV	SI,ES:[SI+0x06].W");
	ASM_INLINE("AND	SI,0x00FF");
	ASM_INLINE("SHL	SI,1");
	ASM_INLINE("SHL	SI,1");
	ASM_INLINE("MOV	DX,SEG search_tbl_");
	ASM_INLINE("MOV	ES,DX");
	//ASM_INLINE("MOV	AX,ES:[SI+0x000C].W");
	ASM_OP5(0x26,0x8B,0x84,0x0C,0x00);
	//ASM_INLINE("MOV	DX,ES:[SI+0x000E].W");
	ASM_OP5(0x26,0x8B,0x94,0x0E,0x00);
	ASM_INLINE("MOV	[BP-0x08].W,AX");
	ASM_INLINE("MOV	[BP-0x06].W,DX");
	ASM_INLINE("XOR	SI,SI");
	ASM_INLINE("POP	AX");
	ASM_INLINE("JMP	_87B1C");
ASM_INLINE("_87AB4:");
	ASM_INLINE("XOR	DX,DX");
	ASM_INLINE("JMP	_87B16");
ASM_INLINE("_87AB8:");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("SUB	DX,BX");
	ASM_INLINE("ADD	DX,0x0007");
	ASM_INLINE("MOV	AX,SI");
	ASM_INLINE("SUB	AX,CX");
	ASM_INLINE("ADD	AX,0x0007");
	ASM_INLINE("LES	SI,[BP-0x08]");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("ADD	SI,AX");
	ASM_INLINE("ADD	SI,DX");
	ASM_INLINE("CMP	ES:[SI].B,0x00");
	ASM_INLINE("POP	AX");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("JZ	_87B15");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AL,[DI+0x016F].B");
	ASM_INLINE("XOR	AH,AH");
	ASM_INLINE("CMP	DX,AX");
	ASM_INLINE("POP	AX");
	ASM_INLINE("JNZ	_87AFA");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AL,[DI+0x0170].B");
	ASM_INLINE("XOR	AH,AH");
	ASM_INLINE("CMP	SI,AX");
	ASM_INLINE("POP	AX");
	ASM_INLINE("JNZ	_87AFA");
	ASM_INLINE("OR	AX,0x0010");
ASM_INLINE("_87AFA:");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AL,[DI+0x0172].B");
	ASM_INLINE("XOR	AH,AH");
	ASM_INLINE("CMP	DX,AX");
	ASM_INLINE("POP	AX");
	ASM_INLINE("JNZ	_87B15");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AL,[DI+0x0173].B");
	ASM_INLINE("XOR	AH,AH");
	ASM_INLINE("CMP	SI,AX");
	ASM_INLINE("POP	AX");
	ASM_INLINE("JNZ	_87B15");
	ASM_INLINE("OR	AX,0x0008");
ASM_INLINE("_87B15:");
	ASM_INLINE("INC	DX");
ASM_INLINE("_87B16:");
	ASM_INLINE("CMP	DX,0x0008");
	ASM_INLINE("JL	_87AB8");
	ASM_INLINE("INC	SI");
ASM_INLINE("_87B1C:");
	ASM_INLINE("CMP	SI,0x0008");
	ASM_INLINE("JL	_87AB4");
	ASM_INLINE("XOR	DX,DX");
	ASM_INLINE("JMP	_87BC7");
ASM_INLINE("_87B26:");
	ASM_INLINE("XOR	SI,SI");
	ASM_INLINE("JMP	_87BBE");
ASM_INLINE("_87B2B:");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("MOV	DI,SI");
	ASM_INLINE("SUB	DI,BX");
	ASM_INLINE("ADD	DI,0x0007");
	ASM_INLINE("SUB	DX,CX");
	ASM_INLINE("ADD	DX,0x0007");
	ASM_INLINE("LES	SI,[BP-0x08]");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("ADD	SI,DX");
	ASM_INLINE("ADD	SI,DI");
	ASM_INLINE("CMP	ES:[SI].B,0x00");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	SI");
	ASM_INLINE("JZ	_87BBD");
	ASM_INLINE("CMP	SI,[BP+0x06].W");
	ASM_INLINE("JNZ	_87BBD");
	ASM_INLINE("CMP	DX,[BP+0x08].W");
	ASM_INLINE("JNZ	_87BBD");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("MOV	BX,ES:[BX+0x08].W");
	ASM_INLINE("AND	BX,0x0003");
	ASM_INLINE("CMP	BX,0x0003");
	ASM_INLINE("JZ	_87B87");
	ASM_INLINE("CMP	BX,0x0002");
	ASM_INLINE("JZ	_87B82");
	ASM_INLINE("CMP	BX,0x0001");
	ASM_INLINE("JZ	_87B7D");
	ASM_INLINE("TEST	BX,BX");
	ASM_INLINE("JNZ	_87BAD");
	ASM_INLINE("OR	AX,0x0000");
	ASM_INLINE("JMP	_87BAD");
ASM_INLINE("_87B7D:");
	ASM_INLINE("OR	AX,0x0001");
	ASM_INLINE("JMP	_87BAD");
ASM_INLINE("_87B82:");
	ASM_INLINE("OR	AX,0x0002");
	ASM_INLINE("JMP	_87BAD");
ASM_INLINE("_87B87:");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("CALLF	rand_, SEG rand_");
	ASM_INLINE("AND	AX,0x0007");
	ASM_INLINE("CMP	AX,0x0000");
	ASM_INLINE("POP	AX");
	ASM_INLINE("JG	_87B9B");
	ASM_INLINE("OR	AX,0x0001");
	ASM_INLINE("JMP	_87BAD");
ASM_INLINE("_87B9B:");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("CALLF	rand_, SEG rand_");
	ASM_INLINE("AND	AX,0x0007");
	ASM_INLINE("CMP	AX,0x0002");
	ASM_INLINE("POP	AX");
	ASM_INLINE("JG	_87BAD");
	ASM_INLINE("OR	AX,0x0002");
ASM_INLINE("_87BAD:");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("TEST	ES:[BX+0x08].W,0x0004");
	ASM_INLINE("JZ	_87BCF");
	ASM_INLINE("OR	AX,0x0004");
	ASM_INLINE("JMP	_87BCF");
ASM_INLINE("_87BBD:");
	ASM_INLINE("INC	SI");
ASM_INLINE("_87BBE:");
	ASM_INLINE("CMP	SI,0x0008");
	ASM_INLINE("JGE	_87BC6");
	ASM_INLINE("JMP	_87B2B");
ASM_INLINE("_87BC6:");
	ASM_INLINE("INC	DX");
ASM_INLINE("_87BC7:");
	ASM_INLINE("CMP	DX,0x0008");
	ASM_INLINE("JGE	_87BCF");
	ASM_INLINE("JMP	_87B26");
ASM_INLINE("_87BCF:");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("MOV	SP,BP");
	ASM_INLINE("POP	BP");
}

u16 put_atack_hit_check()
{
	ASM_INLINE("PUSH	BP");
	ASM_INLINE("MOV	BP,SP");
	ASM_INLINE("SUB	SP,0x0008");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	DI,AX");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	SI,0x0000");
	ASM_INLINE("MOV	AX,SEG functbl_");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("ADD	SI,DX");
	ASM_INLINE("MOV	[BP-0x04].W,SI");
	ASM_INLINE("MOV	[BP-0x02].W,AX");
	ASM_INLINE("LES	SI,[BP-0x04]");
	ASM_INLINE("MOV	SI,ES:[SI+0x06].W");
	ASM_INLINE("AND	SI,0x00FF");
	ASM_INLINE("SHL	SI,1");
	ASM_INLINE("SHL	SI,1");
	ASM_INLINE("MOV	DX,SEG atack_tbl_");
	ASM_INLINE("MOV	ES,DX");
	//ASM_INLINE("MOV	AX,ES:[SI+0x0008].W");
	ASM_OP5(0x26,0x8B,0x84,0x08,0x00);
	//ASM_INLINE("MOV	DX,ES:[SI+0x000A].W");
	ASM_OP5(0x26,0x8B,0x94,0x0A,0x00);
	ASM_INLINE("MOV	[BP-0x08].W,AX");
	ASM_INLINE("MOV	[BP-0x06].W,DX");
	ASM_INLINE("XOR	SI,SI");
	ASM_INLINE("POP	AX");
	ASM_INLINE("JMP	_87C8B");
ASM_INLINE("_87C23:");
	ASM_INLINE("XOR	DX,DX");
	ASM_INLINE("JMP	_87C85");
ASM_INLINE("_87C27:");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("SUB	DX,BX");
	ASM_INLINE("ADD	DX,0x0007");
	ASM_INLINE("MOV	AX,SI");
	ASM_INLINE("SUB	AX,CX");
	ASM_INLINE("ADD	AX,0x0007");
	ASM_INLINE("LES	SI,[BP-0x08]");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("ADD	SI,AX");
	ASM_INLINE("ADD	SI,DX");
	ASM_INLINE("CMP	ES:[SI].B,0x00");
	ASM_INLINE("POP	AX");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("JZ	_87C84");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AL,[DI+0x016F].B");
	ASM_INLINE("XOR	AH,AH");
	ASM_INLINE("CMP	DX,AX");
	ASM_INLINE("POP	AX");
	ASM_INLINE("JNZ	_87C69");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AL,[DI+0x0170].B");
	ASM_INLINE("XOR	AH,AH");
	ASM_INLINE("CMP	SI,AX");
	ASM_INLINE("POP	AX");
	ASM_INLINE("JNZ	_87C69");
	ASM_INLINE("OR	AX,0x0010");
ASM_INLINE("_87C69:");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AL,[DI+0x0172].B");
	ASM_INLINE("XOR	AH,AH");
	ASM_INLINE("CMP	DX,AX");
	ASM_INLINE("POP	AX");
	ASM_INLINE("JNZ	_87C84");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AL,[DI+0x0173].B");
	ASM_INLINE("XOR	AH,AH");
	ASM_INLINE("CMP	SI,AX");
	ASM_INLINE("POP	AX");
	ASM_INLINE("JNZ	_87C84");
	ASM_INLINE("OR	AX,0x0008");
ASM_INLINE("_87C84:");
	ASM_INLINE("INC	DX");
ASM_INLINE("_87C85:");
	ASM_INLINE("CMP	DX,0x0008");
	ASM_INLINE("JL	_87C27");
	ASM_INLINE("INC	SI");
ASM_INLINE("_87C8B:");
	ASM_INLINE("CMP	SI,0x0008");
	ASM_INLINE("JL	_87C23");
	ASM_INLINE("XOR	DX,DX");
	ASM_INLINE("JMP	_87D36");
ASM_INLINE("_87C95:");
	ASM_INLINE("XOR	SI,SI");
	ASM_INLINE("JMP	_87D2D");
ASM_INLINE("_87C9A:");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("MOV	DI,SI");
	ASM_INLINE("SUB	DI,BX");
	ASM_INLINE("ADD	DI,0x0007");
	ASM_INLINE("SUB	DX,CX");
	ASM_INLINE("ADD	DX,0x0007");
	ASM_INLINE("LES	SI,[BP-0x08]");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("ADD	SI,DX");
	ASM_INLINE("ADD	SI,DI");
	ASM_INLINE("CMP	ES:[SI].B,0x00");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	SI");
	ASM_INLINE("JZ	_87D2C");
	ASM_INLINE("CMP	SI,[BP+0x06].W");
	ASM_INLINE("JNZ	_87D2C");
	ASM_INLINE("CMP	DX,[BP+0x08].W");
	ASM_INLINE("JNZ	_87D2C");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("MOV	BX,ES:[BX+0x08].W");
	ASM_INLINE("AND	BX,0x0003");
	ASM_INLINE("CMP	BX,0x0003");
	ASM_INLINE("JZ	_87CF6");
	ASM_INLINE("CMP	BX,0x0002");
	ASM_INLINE("JZ	_87CF1");
	ASM_INLINE("CMP	BX,0x0001");
	ASM_INLINE("JZ	_87CEC");
	ASM_INLINE("TEST	BX,BX");
	ASM_INLINE("JNZ	_87D1C");
	ASM_INLINE("OR	AX,0x0000");
	ASM_INLINE("JMP	_87D1C");
ASM_INLINE("_87CEC:");
	ASM_INLINE("OR	AX,0x0001");
	ASM_INLINE("JMP	_87D1C");
ASM_INLINE("_87CF1:");
	ASM_INLINE("OR	AX,0x0002");
	ASM_INLINE("JMP	_87D1C");
ASM_INLINE("_87CF6:");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("CALLF	rand_, SEG rand_");
	ASM_INLINE("AND	AX,0x0007");
	ASM_INLINE("CMP	AX,0x0000");
	ASM_INLINE("POP	AX");
	ASM_INLINE("JG	_87D0A");
	ASM_INLINE("OR	AX,0x0001");
	ASM_INLINE("JMP	_87D1C");
ASM_INLINE("_87D0A:");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("CALLF	rand_, SEG rand_");
	ASM_INLINE("AND	AX,0x0007");
	ASM_INLINE("CMP	AX,0x0002");
	ASM_INLINE("POP	AX");
	ASM_INLINE("JG	_87D1C");
	ASM_INLINE("OR	AX,0x0002");
ASM_INLINE("_87D1C:");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("TEST	ES:[BX+0x08].W,0x0004");
	ASM_INLINE("JZ	_87D3E");
	ASM_INLINE("OR	AX,0x0004");
	ASM_INLINE("JMP	_87D3E");
ASM_INLINE("_87D2C:");
	ASM_INLINE("INC	SI");
ASM_INLINE("_87D2D:");
	ASM_INLINE("CMP	SI,0x0008");
	ASM_INLINE("JGE	_87D35");
	ASM_INLINE("JMP	_87C9A");
ASM_INLINE("_87D35:");
	ASM_INLINE("INC	DX");
ASM_INLINE("_87D36:");
	ASM_INLINE("CMP	DX,0x0008");
	ASM_INLINE("JGE	_87D3E");
	ASM_INLINE("JMP	_87C95");
ASM_INLINE("_87D3E:");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("MOV	SP,BP");
	ASM_INLINE("POP	BP");
}

void set_effect_task()
{
	ASM_INLINE("PUSH	BP");
	ASM_INLINE("MOV	BP,SP");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("MOV	SI,AX");
	ASM_INLINE("ADD	SI,0x013B");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("JMP	_87D78");
ASM_INLINE("_87D53:");
	ASM_INLINE("CMP	[SI+0x04].W,0x0000");
	ASM_INLINE("JGE	_87D74");
	ASM_INLINE("MOV	[SI+0x02].W,DX");
	ASM_INLINE("MOV	[SI+0x04].W,0x0000");
	ASM_INLINE("MOV	[SI+0x06].W,0xFFFF");
	ASM_INLINE("MOV	[SI+0x08].W,BX");
	ASM_INLINE("MOV	[SI+0x0A].W,CX");
	ASM_INLINE("MOV	AX,[BP+0x06].W");
	ASM_INLINE("MOV	[SI+0x0E].W,AX");
	ASM_INLINE("JMP	_87D7D");
ASM_INLINE("_87D74:");
	ASM_INLINE("INC	AX");
	ASM_INLINE("ADD	SI,0x0010");
ASM_INLINE("_87D78:");
	ASM_INLINE("CMP	AX,0x0003");
	ASM_INLINE("JL	_87D53");
ASM_INLINE("_87D7D:");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	BP");
}

void run_effect_task()
{
	put_atack_cousorON; //Force include
	ASM_INLINE("PUSH	BP");
	ASM_INLINE("MOV	BP,SP");
	ASM_INLINE("SUB	SP,0x0008");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	DI,AX");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("ADD	BX,0x013B");
	ASM_INLINE("MOV	AX,0xFFFF");
	ASM_INLINE("MOV	CX,0xFFFF");
	ASM_INLINE("MOV	[BP-0x02].W,0x0000");
	ASM_INLINE("JMP	_87DB0");
ASM_INLINE("_87D9F:");
	ASM_INLINE("CMP	AX,[BX+0x04].W");
	ASM_INLINE("JGE	_87DAA");
	ASM_INLINE("MOV	AX,[BX+0x04].W");
	ASM_INLINE("MOV	CX,[BP-0x02].W");
ASM_INLINE("_87DAA:");
	ASM_INLINE("INC	[BP-0x02].W");
	ASM_INLINE("ADD	BX,0x0010");
ASM_INLINE("_87DB0:");
	ASM_INLINE("CMP	[BP-0x02].W,0x0003");
	ASM_INLINE("JL	_87D9F");
	ASM_INLINE("CMP	CX,-0x0001");
	ASM_INLINE("JNZ	_87DBE");
	ASM_INLINE("JMP	_87F8D");
ASM_INLINE("_87DBE:");
	ASM_INLINE("MOV	SI,DI");
	ASM_INLINE("ADD	SI,0x013B");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("ADD	SI,CX");
	ASM_INLINE("CMP	[SI+0x04].W,0x0000");
	ASM_INLINE("JGE	_87DD7");
	ASM_INLINE("JMP	_87F8D");
ASM_INLINE("_87DD7:");
	ASM_INLINE("CMP	[SI+0x06].W,-0x0001");
	ASM_INLINE("JNZ	_87DF9");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("MOV	BX,[SI+0x08].W");
	ASM_INLINE("MOV	CX,[SI+0x0A].W");
	ASM_INLINE("MOV	DX,[SI+0x0E].W");
	ASM_INLINE("CALLF	put_atack_cousorON_, SEG put_atack_cousorON_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("MOV	[SI+0x06].W,0x0000");
ASM_INLINE("_87DF9:");
	ASM_INLINE("MOV	AX,[SI+0x02].W");
	ASM_INLINE("MOV	BX,0x000C");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("ADD	AX,0x0600");
	ASM_INLINE("MOV	[BP-0x06].W,AX");
	ASM_INLINE("MOV	[BP-0x04].W,DS");
	ASM_INLINE("MOV	AX,[SI+0x04].W");
	ASM_INLINE("LES	BX,[BP-0x06]");
	ASM_INLINE("CMP	AX,ES:[BX+0x06].W");
	ASM_INLINE("JL	_87E19");
	ASM_INLINE("JMP	_87F48");
ASM_INLINE("_87E19:");
	ASM_INLINE("DEC	[SI+0x06].W");
	ASM_INLINE("CMP	[SI+0x06].W,0x0000");
	ASM_INLINE("JLE	_87E25");
	ASM_INLINE("JMP	_87F8D");
ASM_INLINE("_87E25:");
	ASM_INLINE("MOV	[SI+0x06].W,0x0005");
	ASM_INLINE("XOR	DI,DI");
	ASM_INLINE("JMP	_87F2F");
ASM_INLINE("_87E2F:");
	ASM_INLINE("MOV	[BP-0x02].W,0x0000");
	ASM_INLINE("JMP	_87F1A");
ASM_INLINE("_87E37:");
	ASM_INLINE("MOV	AX,[SI].W");
	ASM_INLINE("MOV	[BP-0x08].W,AX");
	ASM_INLINE("MOV	AX,[SI].W");
	ASM_INLINE("INC	AX");
	ASM_INLINE("MOV	BX,0x0030");
	ASM_INLINE("CWD");
	ASM_INLINE("IDIV	BX");
	ASM_INLINE("MOV	[SI].W,DX");
	ASM_INLINE("LES	BX,[BP-0x06]");
	ASM_INLINE("PUSH	ES:[BX+0x0A].W");
	ASM_INLINE("PUSH	ES:[BX+0x08].W");
	ASM_INLINE("LES	BX,[BP-0x06]");
	ASM_INLINE("MOV	AX,ES:[BX].W");
	ASM_INLINE("SAR	AX,1");
	ASM_INLINE("SAR	AX,1");
	ASM_INLINE("SAR	AX,1");
	ASM_INLINE("MUL	[SI+0x04].W");
	ASM_INLINE("ADD	AX,[BP-0x02].W");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("MOV	AX,[BP-0x08].W");
	ASM_INLINE("SHR	AX,1");
	ASM_INLINE("SHR	AX,1");
	ASM_INLINE("SHR	AX,1");
	ASM_INLINE("SHR	AX,1");
	ASM_INLINE("MOV	CX,0x001C");
	ASM_INLINE("MUL	CX");
	ASM_INLINE("MOV	CX,[BP-0x08].W");
	ASM_INLINE("AND	CX,0x000F");
	ASM_INLINE("ADD	CX,AX");
	ASM_INLINE("ADD	CX,0x0118");
	ASM_INLINE("POP	AX");
	ASM_INLINE("CALLF	font_put3_, SEG font_put3_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("LES	BX,[BP-0x06]");
	ASM_INLINE("MOV	AX,ES:[BX].W");
	ASM_INLINE("MOV	BX,0x0002");
	ASM_INLINE("CWD");
	ASM_INLINE("IDIV	BX");
	ASM_INLINE("MOV	CX,[SI+0x08].W");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SUB	CX,AX");
	ASM_INLINE("ADD	CX,0x0008");
	ASM_INLINE("LES	BX,[BP-0x06]");
	ASM_INLINE("MOV	AX,ES:[BX+0x02].W");
	ASM_INLINE("MOV	BX,0x0002");
	ASM_INLINE("CWD");
	ASM_INLINE("IDIV	BX");
	ASM_INLINE("MOV	DX,[SI+0x0A].W");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("SUB	DX,AX");
	ASM_INLINE("ADD	DX,0x0008");
	ASM_INLINE("LES	BX,[BP-0x06]");
	ASM_INLINE("SUB	DX,ES:[BX+0x04].W");
	ASM_INLINE("MOV	AX,0x0004");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x0020");
	ASM_INLINE("ADD	AX,[BP-0x08].W");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	BX,[BP-0x02].W");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("ADD	BX,CX");
	ASM_INLINE("MOV	CX,DI");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("ADD	CX,DX");
	ASM_INLINE("MOV	AX,[BP-0x08].W");
	ASM_INLINE("SHR	AX,1");
	ASM_INLINE("SHR	AX,1");
	ASM_INLINE("SHR	AX,1");
	ASM_INLINE("SHR	AX,1");
	ASM_INLINE("MOV	DX,0x001C");
	ASM_INLINE("MUL	DX");
	ASM_INLINE("MOV	DX,[BP-0x08].W");
	ASM_INLINE("AND	DX,0x000F");
	ASM_INLINE("ADD	DX,AX");
	ASM_INLINE("ADD	DX,0x0118");
	ASM_INLINE("OR	DX,0x2000");
	ASM_INLINE("POP	AX");
	ASM_INLINE("CALLF	put_sprite_, SEG put_sprite_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("INC	[BP-0x02].W");
ASM_INLINE("_87F1A:");
	ASM_INLINE("LES	BX,[BP-0x06]");
	ASM_INLINE("MOV	AX,ES:[BX].W");
	ASM_INLINE("SAR	AX,1");
	ASM_INLINE("SAR	AX,1");
	ASM_INLINE("SAR	AX,1");
	ASM_INLINE("CMP	AX,[BP-0x02].W");
	ASM_INLINE("JLE	_87F2E");
	ASM_INLINE("JMP	_87E37");
ASM_INLINE("_87F2E:");
	ASM_INLINE("INC	DI");
ASM_INLINE("_87F2F:");
	ASM_INLINE("LES	BX,[BP-0x06]");
	ASM_INLINE("MOV	AX,ES:[BX+0x02].W");
	ASM_INLINE("SAR	AX,1");
	ASM_INLINE("SAR	AX,1");
	ASM_INLINE("SAR	AX,1");
	ASM_INLINE("CMP	DI,AX");
	ASM_INLINE("JGE	_87F43");
	ASM_INLINE("JMP	_87E2F");
ASM_INLINE("_87F43:");
	ASM_INLINE("INC	[SI+0x04].W");
	ASM_INLINE("JMP	_87F8D");
ASM_INLINE("_87F48:");
	ASM_INLINE("MOV	[BP-0x08].W,0x0000");
	ASM_INLINE("JMP	_87F6C");
ASM_INLINE("_87F4F:");
	ASM_INLINE("MOV	AX,0x0004");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x0020");
	ASM_INLINE("ADD	AX,[BP-0x08].W");
	ASM_INLINE("MOV	BX,0x00E0");
	ASM_INLINE("MOV	CX,0x0090");
	ASM_INLINE("XOR	DX,DX");
	ASM_INLINE("CALLF	put_sprite_, SEG put_sprite_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("INC	[BP-0x08].W");
ASM_INLINE("_87F6C:");
	ASM_INLINE("CMP	[BP-0x08].W,0x0030");
	ASM_INLINE("JB	_87F4F");
	ASM_INLINE("MOV	[SI+0x04].W,0xFFFF");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("MOV	BX,[SI+0x08].W");
	ASM_INLINE("MOV	CX,[SI+0x0A].W");
	ASM_INLINE("MOV	DX,[SI+0x0E].W");
	ASM_INLINE("CALLF	put_atack_cousorON_, SEG put_atack_cousorON_");
	ASM_INLINE("ADD	SP,0x0002");
ASM_INLINE("_87F8D:");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
	ASM_INLINE("MOV	SP,BP");
	ASM_INLINE("POP	BP");
}

void wall_sprite()
{
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	BX,AX");
	ASM_INLINE("MOV	CX,BX");
	ASM_INLINE("ADD	CX,0x0005");
	ASM_INLINE("XOR	DI,DI");
	ASM_INLINE("JMP	_8815A");
ASM_INLINE("_87FA5:");
	ASM_INLINE("MOV	SI,CX");
	ASM_INLINE("CMP	[SI].W,0x8000");
	ASM_INLINE("JBE	_87FB5");
	ASM_INLINE("MOV	SI,CX");
	ASM_INLINE("CMP	[SI].W,0xEE00");
	ASM_INLINE("JB	_87FCD");
ASM_INLINE("_87FB5:");
	ASM_INLINE("MOV	SI,CX");
	ASM_INLINE("CMP	[SI+0x02].W,0x8000");
	ASM_INLINE("JA	_87FC1");
	ASM_INLINE("JMP	_88070");
ASM_INLINE("_87FC1:");
	ASM_INLINE("MOV	SI,CX");
	ASM_INLINE("CMP	[SI+0x02].W,0xEE00");
	ASM_INLINE("JB	_87FCD");
	ASM_INLINE("JMP	_88070");
ASM_INLINE("_87FCD:");
	ASM_INLINE("CMP	DI,0x000F");
	ASM_INLINE("JNZ	_88028");
	ASM_INLINE("CMP	[BX+0x04].B,0x00");
	ASM_INLINE("JNZ	_87FDB");
	ASM_INLINE("JMP	_880A9");
ASM_INLINE("_87FDB:");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	[BX+0x04].B,0x00");
	ASM_INLINE("CALLF	rand_, SEG rand_");
	ASM_INLINE("TEST	AX,0x0001");
	ASM_INLINE("JZ	_88008");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("CALLF	rand_, SEG rand_");
	ASM_INLINE("MOV	SI,0x0080");
	ASM_INLINE("CWD");
	ASM_INLINE("IDIV	SI");
	ASM_INLINE("MOV	CL,0x08");
	ASM_INLINE("SHL	DX,CL");
	ASM_INLINE("POP	CX");
	ASM_INLINE("MOV	SI,CX");
	ASM_INLINE("MOV	[SI].W,DX");
	ASM_INLINE("MOV	SI,CX");
	ASM_INLINE("MOV	[SI+0x02].W,0x8000");
	ASM_INLINE("JMP	_88024");
ASM_INLINE("_88008:");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	SI,CX");
	ASM_INLINE("MOV	[SI].W,0x8000");
	ASM_INLINE("CALLF	rand_, SEG rand_");
	ASM_INLINE("MOV	SI,0x0080");
	ASM_INLINE("CWD");
	ASM_INLINE("IDIV	SI");
	ASM_INLINE("MOV	CL,0x08");
	ASM_INLINE("SHL	DX,CL");
	ASM_INLINE("POP	CX");
	ASM_INLINE("MOV	SI,CX");
	ASM_INLINE("MOV	[SI+0x02].W,DX");
ASM_INLINE("_88024:");
	ASM_INLINE("POP	BX");
	ASM_INLINE("JMP	_880A9");
ASM_INLINE("_88028:");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("CALLF	rand_, SEG rand_");
	ASM_INLINE("TEST	AX,0x0001");
	ASM_INLINE("JZ	_88051");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("CALLF	rand_, SEG rand_");
	ASM_INLINE("MOV	SI,0x0080");
	ASM_INLINE("CWD");
	ASM_INLINE("IDIV	SI");
	ASM_INLINE("MOV	CL,0x08");
	ASM_INLINE("SHL	DX,CL");
	ASM_INLINE("POP	CX");
	ASM_INLINE("MOV	SI,CX");
	ASM_INLINE("MOV	[SI].W,DX");
	ASM_INLINE("MOV	SI,CX");
	ASM_INLINE("MOV	[SI+0x02].W,0x8000");
	ASM_INLINE("JMP	_8806D");
ASM_INLINE("_88051:");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	SI,CX");
	ASM_INLINE("MOV	[SI].W,0x8000");
	ASM_INLINE("CALLF	rand_, SEG rand_");
	ASM_INLINE("MOV	SI,0x0080");
	ASM_INLINE("CWD");
	ASM_INLINE("IDIV	SI");
	ASM_INLINE("MOV	CL,0x08");
	ASM_INLINE("SHL	DX,CL");
	ASM_INLINE("POP	CX");
	ASM_INLINE("MOV	SI,CX");
	ASM_INLINE("MOV	[SI+0x02].W,DX");
ASM_INLINE("_8806D:");
	ASM_INLINE("POP	BX");
	ASM_INLINE("JMP	_880A9");
ASM_INLINE("_88070:");
	ASM_INLINE("CMP	DI,0x000F");
	ASM_INLINE("JNZ	_88084");
	ASM_INLINE("MOV	SI,CX");
	ASM_INLINE("SUB	[SI].W,0x0300");
	ASM_INLINE("MOV	SI,CX");
	ASM_INLINE("SUB	[SI+0x02].W,0x0300");
	ASM_INLINE("JMP	_880A9");
ASM_INLINE("_88084:");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("AND	AX,0x0003");
	ASM_INLINE("ADD	AX,0x0004");
	ASM_INLINE("MOV	CL,0x07");
	ASM_INLINE("SHL	AX,CL");
	ASM_INLINE("POP	CX");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	SI,CX");
	ASM_INLINE("SUB	[SI].W,AX");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("AND	AX,0x0003");
	ASM_INLINE("ADD	AX,0x0004");
	ASM_INLINE("MOV	CL,0x06");
	ASM_INLINE("SHL	AX,CL");
	ASM_INLINE("POP	CX");
	ASM_INLINE("MOV	SI,CX");
	ASM_INLINE("SUB	[SI+0x02].W,AX");
ASM_INLINE("_880A9:");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("CMP	DI,0x000F");
	ASM_INLINE("JNZ	_8811C");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("XOR	DI,DI");
	ASM_INLINE("JMP	_88114");
ASM_INLINE("_880B4:");
	ASM_INLINE("XOR	SI,SI");
	ASM_INLINE("JMP	_8810E");
ASM_INLINE("_880B8:");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("MOV	AX,0x0004");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	AX,0x006B");
	ASM_INLINE("ADD	AX,SI");
	ASM_INLINE("MOV	DX,DI");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("ADD	AX,DX");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("MOV	BX,[BX].W");
	ASM_INLINE("MOV	CL,0x08");
	ASM_INLINE("SAR	BX,CL");
	ASM_INLINE("MOV	DX,SI");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("ADD	BX,DX");
	ASM_INLINE("POP	CX");
	ASM_INLINE("MOV	SI,CX");
	ASM_INLINE("MOV	DX,[SI+0x02].W");
	ASM_INLINE("MOV	CL,0x08");
	ASM_INLINE("SAR	DX,CL");
	ASM_INLINE("MOV	CX,DI");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("ADD	DX,CX");
	ASM_INLINE("MOV	CX,DX");
	ASM_INLINE("MOV	DX,0x000C");
	ASM_INLINE("POP	SI");
	ASM_INLINE("ADD	DX,SI");
	ASM_INLINE("MOV	SI,DI");
	ASM_INLINE("SHL	SI,1");
	ASM_INLINE("ADD	DX,SI");
	ASM_INLINE("ADD	DX,0x01A4");
	ASM_INLINE("CALLF	put_sprite_, SEG put_sprite_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("POP	SI");
	ASM_INLINE("INC	SI");
	ASM_INLINE("POP	CX");
ASM_INLINE("_8810E:");
	ASM_INLINE("CMP	SI,0x0002");
	ASM_INLINE("JL	_880B8");
	ASM_INLINE("INC	DI");
ASM_INLINE("_88114:");
	ASM_INLINE("CMP	DI,0x0002");
	ASM_INLINE("JL	_880B4");
	ASM_INLINE("POP	DI");
	ASM_INLINE("JMP	_88155");
ASM_INLINE("_8811C:");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	AX,0x0004");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x005C");
	ASM_INLINE("ADD	AX,DI");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	SI,CX");
	ASM_INLINE("MOV	BX,[SI].W");
	ASM_INLINE("MOV	CL,0x08");
	ASM_INLINE("SAR	BX,CL");
	ASM_INLINE("POP	CX");
	ASM_INLINE("MOV	SI,CX");
	ASM_INLINE("MOV	DX,[SI+0x02].W");
	ASM_INLINE("MOV	CL,0x08");
	ASM_INLINE("SAR	DX,CL");
	ASM_INLINE("MOV	CX,DX");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("MOV	SI,0x0003");
	ASM_INLINE("CWD");
	ASM_INLINE("IDIV	SI");
	ASM_INLINE("ADD	DX,0x0009");
	ASM_INLINE("ADD	DX,0x01A4");
	ASM_INLINE("POP	AX");
	ASM_INLINE("CALLF	put_sprite_, SEG put_sprite_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("POP	CX");
ASM_INLINE("_88155:");
	ASM_INLINE("INC	DI");
	ASM_INLINE("ADD	CX,0x0004");
	ASM_INLINE("POP	BX");
ASM_INLINE("_8815A:");
	ASM_INLINE("CMP	DI,0x0010");
	ASM_INLINE("JGE	_88162");
	ASM_INLINE("JMP	_87FA5");
ASM_INLINE("_88162:");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
}

void win_icon_sprite(struct MGameWork *work)
{
	s16 i;
	u8 val;

	val = work->unk0 >> 8;
	for (i = 0; i < work->unk45[0].unk06; i++)
	{
		put_sprite(0x1c + i, 0x80 + i * 8 + 2, 2, 0xC + (val & 3) + 0xFC | 0x2000, 4);
	}

	for (; i < 2; i++)
	{
		put_sprite(0x1c + i, 0x80 + i * 8 + 2, 2, 0x209b, 4);
	}

	for (i = 0; i < work->unk45[1].unk06; i++)
	{
		put_sprite(0x1e + i, 0x80 + i * 8 + 2, 0x52, 0xC + (val & 3) + 0xFC | 0x2000, 4);
	}

	for (; i < 2; i++)
	{
		put_sprite(0x1e + i, 0x80 + i * 8 + 2, 0x52, 0x209b, 4);
	}
}

void pause_put()
{
	ASM_INLINE("PUSH	BP");
	ASM_INLINE("MOV	BP,SP");
	ASM_INLINE("SUB	SP,0x0006");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	SI,AX");
	ASM_INLINE("XOR	DI,DI");
	ASM_INLINE("MOV	AX,SEG unk_1_"); //unk_1
	ASM_INLINE("MOV	ES,AX");
	//ASM_INLINE("MOV	AL,ES:[SI+0x0004].B"); //unk_1
	ASM_OP5(0x26,0x8A,0x84,0x04,0x00);
	ASM_INLINE("CBW");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	CX,SEG str_all_"); //str_all
	ASM_INLINE("MOV	ES,CX");
	ASM_INLINE("SHL	SI,1");
	ASM_INLINE("SHL	SI,1");
	//ASM_INLINE("MOV	CX,ES:[SI+0x000C].W");
	ASM_OP5(0x26,0x8B,0x8C,0x0C,0x00);
	//ASM_INLINE("MOV	DX,ES:[SI+0x000E].W");
	ASM_OP5(0x26,0x8B,0x94,0x0E,0x00);
	ASM_INLINE("MOV	[BP-0x04].W,CX");
	ASM_INLINE("MOV	[BP-0x02].W,DX");
	ASM_INLINE("MOV	SI,0x0038");
	ASM_INLINE("MOV	CX,AX");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SUB	SI,CX");
	ASM_INLINE("MOV	DX,0x0034");
	ASM_INLINE("TEST	BX,BX");
	ASM_INLINE("JNZ	_882A2");
	ASM_INLINE("MOV	DX,0x0090");
ASM_INLINE("_882A2:");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("MOV	[BP-0x06].W,0x0000");
	ASM_INLINE("MOV	CX,0x0004");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	AX,0xFFFF");
	ASM_INLINE("INC	DI");
	ASM_INLINE("ADD	AX,DI");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("ADD	BX,SI");
	ASM_INLINE("MOV	CX,[BP-0x06].W");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("ADD	CX,DX");
	ASM_INLINE("MOV	DX,0x2097");
	ASM_INLINE("CALLF	put_sprite_, SEG put_sprite_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("MOV	BX,0x0001");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	AX");
	ASM_INLINE("JMP	_88308");
ASM_INLINE("_882D9:");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	CX,0x0004");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	AX,0xFFFF");
	ASM_INLINE("INC	DI");
	ASM_INLINE("ADD	AX,DI");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("ADD	BX,SI");
	ASM_INLINE("MOV	CX,[BP-0x06].W");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("ADD	CX,DX");
	ASM_INLINE("MOV	DX,0x2098");
	ASM_INLINE("CALLF	put_sprite_, SEG put_sprite_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("POP	BX");
	ASM_INLINE("INC	BX");
	ASM_INLINE("POP	AX");
	ASM_INLINE("POP	DX");
ASM_INLINE("_88308:");
	ASM_INLINE("MOV	CX,AX");
	ASM_INLINE("INC	CX");
	ASM_INLINE("CMP	BX,CX");
	ASM_INLINE("JL	_882D9");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("MOV	CX,0x0004");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	AX,0xFFFF");
	ASM_INLINE("INC	DI");
	ASM_INLINE("ADD	AX,DI");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("ADD	BX,SI");
	ASM_INLINE("MOV	CX,[BP-0x06].W");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("ADD	CX,DX");
	ASM_INLINE("MOV	DX,0x6097");
	ASM_INLINE("CALLF	put_sprite_, SEG put_sprite_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("POP	DX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("INC	[BP-0x06].W");
	ASM_INLINE("MOV	CX,0x0004");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	AX,0xFFFF");
	ASM_INLINE("INC	DI");
	ASM_INLINE("ADD	AX,DI");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("ADD	BX,SI");
	ASM_INLINE("MOV	CX,[BP-0x06].W");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("ADD	CX,DX");
	ASM_INLINE("MOV	DX,0x2099");
	ASM_INLINE("CALLF	put_sprite_, SEG put_sprite_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("POP	BX");
	ASM_INLINE("INC	BX");
	ASM_INLINE("POP	DX");
	ASM_INLINE("JMP	_883CE");
ASM_INLINE("_8836E:");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	CX,0x0004");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	AX,0xFFFF");
	ASM_INLINE("INC	DI");
	ASM_INLINE("ADD	AX,DI");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("ADD	BX,SI");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	CX,[BP-0x06].W");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("ADD	CX,DX");
	ASM_INLINE("LES	SI,[BP-0x04]");
	ASM_INLINE("MOV	AL,ES:[SI].B");
	ASM_INLINE("XOR	AH,AH");
	ASM_INLINE("SUB	AX,0x0010");
	ASM_INLINE("SHR	AX,1");
	ASM_INLINE("SHR	AX,1");
	ASM_INLINE("SHR	AX,1");
	ASM_INLINE("MOV	DX,0x001C");
	ASM_INLINE("MUL	DX");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("MOV	DL,ES:[BX].B");
	ASM_INLINE("SUB	DL,0x10");
	ASM_INLINE("AND	DL,0x07");
	ASM_INLINE("XOR	DH,DH");
	ASM_INLINE("ADD	DX,0x0008");
	ASM_INLINE("ADD	DX,AX");
	ASM_INLINE("OR	DX,0x2000");
	ASM_INLINE("POP	BX");
	ASM_INLINE("POP	AX");
	ASM_INLINE("CALLF	put_sprite_, SEG put_sprite_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("INC	[BP-0x04].W");
	ASM_INLINE("POP	BX");
	ASM_INLINE("INC	BX");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
ASM_INLINE("_883CE:");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("CMP	ES:[BX].B,0x00");
	ASM_INLINE("POP	BX");
	ASM_INLINE("JNZ	_8836E");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("MOV	CX,0x0004");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	AX,0xFFFF");
	ASM_INLINE("INC	DI");
	ASM_INLINE("ADD	AX,DI");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("ADD	BX,SI");
	ASM_INLINE("MOV	CX,[BP-0x06].W");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("ADD	CX,DX");
	ASM_INLINE("MOV	DX,0x2099");
	ASM_INLINE("CALLF	put_sprite_, SEG put_sprite_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("INC	[BP-0x06].W");
	ASM_INLINE("MOV	CX,0x0004");
	ASM_INLINE("POP	DX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	AX,0xFFFF");
	ASM_INLINE("INC	DI");
	ASM_INLINE("ADD	AX,DI");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("ADD	BX,SI");
	ASM_INLINE("MOV	CX,[BP-0x06].W");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("ADD	CX,DX");
	ASM_INLINE("MOV	DX,0xA097");
	ASM_INLINE("CALLF	put_sprite_, SEG put_sprite_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("MOV	BX,0x0001");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	AX");
	ASM_INLINE("JMP	_88467");
ASM_INLINE("_88438:");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	CX,0x0004");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	AX,0xFFFF");
	ASM_INLINE("INC	DI");
	ASM_INLINE("ADD	AX,DI");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("ADD	BX,SI");
	ASM_INLINE("MOV	CX,[BP-0x06].W");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("ADD	CX,DX");
	ASM_INLINE("MOV	DX,0x2098");
	ASM_INLINE("CALLF	put_sprite_, SEG put_sprite_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("POP	BX");
	ASM_INLINE("INC	BX");
	ASM_INLINE("POP	AX");
	ASM_INLINE("POP	DX");
ASM_INLINE("_88467:");
	ASM_INLINE("MOV	CX,AX");
	ASM_INLINE("INC	CX");
	ASM_INLINE("CMP	BX,CX");
	ASM_INLINE("JL	_88438");
	ASM_INLINE("MOV	AX,0x0004");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0xFFFF");
	ASM_INLINE("INC	DI");
	ASM_INLINE("ADD	AX,DI");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("ADD	BX,SI");
	ASM_INLINE("MOV	CX,[BP-0x06].W");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("ADD	CX,DX");
	ASM_INLINE("MOV	DX,0xE097");
	ASM_INLINE("CALLF	put_sprite_, SEG put_sprite_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
	ASM_INLINE("MOV	SP,BP");
	ASM_INLINE("POP	BP");
}

void screen_effect_run(struct MGameWork *work)
{
	if (work->unk16D)
	{
		nbg_scroll(1, (rand() & 1) ? 1 : -1, (rand() & 1) ? 1 : -1);
		work->unk16D--;
	}
	else
	{
		nbg_scroll(1, 0, 0);
	}
}

void decoy_put()
{
	ASM_INLINE("PUSH	BP");
	ASM_INLINE("MOV	BP,SP");
	ASM_INLINE("SUB	SP,0x0006");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	SI,AX");
	ASM_INLINE("MOV	[BP-0x02].W,0x0000");
	ASM_INLINE("MOV	BX,[SI].W");
	ASM_INLINE("MOV	CL,0x09");
	ASM_INLINE("SHR	BX,CL");
	ASM_INLINE("CMP	[SI+0x0171].B,0x00");
	ASM_INLINE("JNZ	_8850F");
	ASM_INLINE("JMP	_885C7");
ASM_INLINE("_8850F:");
	ASM_INLINE("MOV	DI,unk_1_");
	ASM_INLINE("MOV	AX,SEG unk_1_");
	ASM_INLINE("MOV	ES,AX");
	ASM_INLINE("XOR	BH,BH");
	ASM_INLINE("MOV	AX,BX");
	ASM_INLINE("MOV	BX,0x0003");
	ASM_INLINE("CWD");
	ASM_INLINE("IDIV	BX");
	ASM_INLINE("MOV	BX,DX");
	//ASM_INLINE("MOV	DL,ES:[BX+0x000A].B");
	ASM_OP5(0x26,0x8A,0x97,0x0A,0x00);
	ASM_INLINE("XOR	DH,DH");
	ASM_INLINE("MOV	[BP-0x04].W,0x0000");
	ASM_INLINE("JMP	_885A6");
ASM_INLINE("_88531:");
	ASM_INLINE("MOV	[BP-0x06].W,0x0000");
	ASM_INLINE("JMP	_8859D");
ASM_INLINE("_88538:");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("MOV	AX,0x0004");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x0017");
	ASM_INLINE("INC	[BP-0x02].W");
	ASM_INLINE("ADD	AX,[BP-0x02].W");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("MOV	BX,[BP-0x06].W");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("MOV	CL,[SI+0x016F].B");
	ASM_INLINE("XOR	CH,CH");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("ADD	BX,CX");
	ASM_INLINE("MOV	CX,[BP-0x04].W");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("MOV	DL,[SI+0x0170].B");
	ASM_INLINE("XOR	DH,DH");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("ADD	CX,DX");
	ASM_INLINE("POP	DX");
	ASM_INLINE("MOV	AX,DX");
	ASM_INLINE("ADD	AX,[BP-0x04].W");
	ASM_INLINE("MOV	DX,0x001C");
	ASM_INLINE("MUL	DX");
	ASM_INLINE("MOV	DX,DI");
	ASM_INLINE("ADD	DX,[BP-0x06].W");
	ASM_INLINE("ADD	DX,AX");
	ASM_INLINE("OR	DX,0x2000");
	ASM_INLINE("POP	AX");
	ASM_INLINE("CALLF	put_sprite_, SEG put_sprite_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("INC	[BP-0x06].W");
	ASM_INLINE("POP	DX");
ASM_INLINE("_8859D:");
	ASM_INLINE("CMP	[BP-0x06].W,0x0002");
	ASM_INLINE("JL	_88538");
	ASM_INLINE("INC	[BP-0x04].W");
ASM_INLINE("_885A6:");
	ASM_INLINE("CMP	[BP-0x04].W,0x0002");
	ASM_INLINE("JL	_88531");
	ASM_INLINE("DEC	[SI+0x0171].B");
	ASM_INLINE("CMP	[SI+0x0171].B,0x00");
	ASM_INLINE("JZ	_885BA");
	ASM_INLINE("JMP	_886A4");
ASM_INLINE("_885BA:");
	ASM_INLINE("MOV	[SI+0x016F].B,0x0F");
	ASM_INLINE("MOV	[SI+0x0170].B,0x0F");
	ASM_INLINE("JMP	_886A4");
ASM_INLINE("_885C7:");
	ASM_INLINE("CMP	[SI+0x016F].B,0x0F");
	ASM_INLINE("JNZ	_8860E");
	ASM_INLINE("MOV	[BP-0x04].W,0x0000");
	ASM_INLINE("JMP	_88605");
ASM_INLINE("_885D5:");
	ASM_INLINE("MOV	[BP-0x06].W,0x0000");
	ASM_INLINE("JMP	_885FC");
ASM_INLINE("_885DC:");
	ASM_INLINE("MOV	AX,0x0004");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x0017");
	ASM_INLINE("INC	[BP-0x02].W");
	ASM_INLINE("ADD	AX,[BP-0x02].W");
	ASM_INLINE("MOV	BX,0x00E0");
	ASM_INLINE("MOV	CX,0x0090");
	ASM_INLINE("XOR	DX,DX");
	ASM_INLINE("CALLF	put_sprite_, SEG put_sprite_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("INC	[BP-0x06].W");
ASM_INLINE("_885FC:");
	ASM_INLINE("CMP	[BP-0x06].W,0x0002");
	ASM_INLINE("JL	_885DC");
	ASM_INLINE("INC	[BP-0x04].W");
ASM_INLINE("_88605:");
	ASM_INLINE("CMP	[BP-0x04].W,0x0002");
	ASM_INLINE("JL	_885D5");
	ASM_INLINE("JMP	_886A4");
ASM_INLINE("_8860E:");
	ASM_INLINE("MOV	DI,unk_2_");
	ASM_INLINE("MOV	AX,SEG unk_2_");
	ASM_INLINE("MOV	ES,AX");
	ASM_INLINE("AND	BL,0x03");
	ASM_INLINE("XOR	BH,BH");
	//ASM_INLINE("MOV	DL,ES:[BX+0x0006].B");
	ASM_OP5(0x26,0x8A,0x97,0x06,0x00);
	ASM_INLINE("XOR	DH,DH");
	ASM_INLINE("MOV	[BP-0x04].W,0x0000");
	ASM_INLINE("JMP	_8869E");
ASM_INLINE("_88629:");
	ASM_INLINE("MOV	[BP-0x06].W,0x0000");
	ASM_INLINE("JMP	_88695");
ASM_INLINE("_88630:");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("MOV	AX,0x0004");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x0017");
	ASM_INLINE("INC	[BP-0x02].W");
	ASM_INLINE("ADD	AX,[BP-0x02].W");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("MOV	BX,[BP-0x06].W");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("MOV	CL,[SI+0x016F].B");
	ASM_INLINE("XOR	CH,CH");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("ADD	BX,CX");
	ASM_INLINE("MOV	CX,[BP-0x04].W");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("MOV	DL,[SI+0x0170].B");
	ASM_INLINE("XOR	DH,DH");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("ADD	CX,DX");
	ASM_INLINE("POP	DX");
	ASM_INLINE("MOV	AX,DX");
	ASM_INLINE("ADD	AX,[BP-0x04].W");
	ASM_INLINE("MOV	DX,0x001C");
	ASM_INLINE("MUL	DX");
	ASM_INLINE("MOV	DX,DI");
	ASM_INLINE("ADD	DX,[BP-0x06].W");
	ASM_INLINE("ADD	DX,AX");
	ASM_INLINE("OR	DX,0x2000");
	ASM_INLINE("POP	AX");
	ASM_INLINE("CALLF	put_sprite_, SEG put_sprite_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("INC	[BP-0x06].W");
	ASM_INLINE("POP	DX");
ASM_INLINE("_88695:");
	ASM_INLINE("CMP	[BP-0x06].W,0x0002");
	ASM_INLINE("JL	_88630");
	ASM_INLINE("INC	[BP-0x04].W");
ASM_INLINE("_8869E:");
	ASM_INLINE("CMP	[BP-0x04].W,0x0002");
	ASM_INLINE("JL	_88629");
ASM_INLINE("_886A4:");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
	ASM_INLINE("MOV	SP,BP");
	ASM_INLINE("POP	BP");
}

