
#include <machine.h>
#include "types.h"
#include "m_weapon.h"
#include "m_sub.h"
#include "m_game.h"
#include "SERIAL.h"
#include "func_tbl.h"
#include "SWAN_L_C.h"
#include "SWANMAIN.h"
#include "SPRINTF.h"
#include "SYSTEM.h"
#include "SOUND_CODE.h"
#include "MEMORY.h"
#include "PAD.h"
#include "story.h"
#include "IP_MES.h"
#include "PUT_TEXT.h"
#include "m_cpu2p.h"
#include "tuneup.h"
#include "ASM.h"

static u8 m_weapon_data[] = {
	0x08, 0x02, 0xA8, 0xC0,
	0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00,
	0x05, 0x00,
};

static u8 m_weapon_data2[] = {
	0x07, 0x02, 0xA8, 0xC0,
	0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00,
	0x05, 0x00,
};

void m_game_main_weapon_i_sub()
{
	put_lange_cousor; //Force include
	m_game_main_lange_sub; //Force include
	put_message; //Force include
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	SI,AX");
	ASM_INLINE("MOV	AX,0xA711");
	ASM_INLINE("MOV	ES,AX");
	ASM_INLINE("MOV	DI,0x0000");
	ASM_INLINE("MOV	AX,[SI+0x00A9].W");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("ADD	AX,[SI+0x00A7].W");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("ADD	BX,0x005C");
	ASM_INLINE("ADD	BX,AX");
	ASM_INLINE("MOV	AX,[BX].W");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("ADD	DI,AX");
	ASM_INLINE("MOV	DX,ES:[DI+0x04].W");
	ASM_INLINE("AND	DX,0x00FF");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("MOV	AX,[BX+0x50].W");
	ASM_INLINE("MOV	[SI+0x00AD].W,AX");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("MOV	AX,[SI+0x52].W");
	ASM_INLINE("MOV	[BX+0x00AF].W,AX");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,SI");
	ASM_INLINE("MOV	BX,[SI+0x50].W");
	ASM_INLINE("MOV	CX,[SI+0x52].W");
	ASM_INLINE("CALLF	put_lange_cousor_, SEG put_lange_cousor_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("MOV	AX,SI");
	ASM_INLINE("MOV	BX,0x0001");
	ASM_INLINE("CALLF	m_game_main_lange_sub_, SEG m_game_main_lange_sub_");
	ASM_INLINE("MOV	AX,0x8007");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("CALLF	put_message_, SEG put_message_");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
}

void m_game_main_weapon_m_sub()
{
	sereq; //Force include
	get_lange_test; //Force include
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	DI,AX");
	ASM_INLINE("MOV	CX,DI");
	ASM_INLINE("ADD	CX,0x0045");
	ASM_INLINE("MOV	SI,DI");
	ASM_INLINE("ADD	SI,0x00AD");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("MOV	AX,0xA711");
	ASM_INLINE("MOV	ES,AX");
	ASM_INLINE("MOV	SI,0x0000");
	ASM_INLINE("MOV	AX,[DI+0x00A9].W");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("ADD	AX,[DI+0x00A7].W");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("ADD	BX,0x0017");
	ASM_INLINE("ADD	BX,AX");
	ASM_INLINE("MOV	AX,[BX].W");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("ADD	SI,AX");
	ASM_INLINE("MOV	DX,ES:[SI+0x04].W");
	ASM_INLINE("AND	DX,0x00FF");
	ASM_INLINE("TEST	[0x0956].W,0x0100");
	ASM_INLINE("POP	SI");
	ASM_INLINE("JZ	_887B7");
	ASM_INLINE("MOV	AL,0x0C");
	ASM_INLINE("CALLF	sereq_, SEG sereq_");
	ASM_INLINE("CMP	[SI+0x02].W,0x0000");
	ASM_INLINE("JG	_8877E");
	ASM_INLINE("JMP	_88803");
ASM_INLINE("_8877E:");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("MOV	AX,[BX+0x0B].W");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("MOV	BX,[BX+0x0D].W");
	ASM_INLINE("MOV	CX,[SI].W");
	ASM_INLINE("MOV	DX,[SI+0x02].W");
	ASM_INLINE("DEC	DX");
	ASM_INLINE("CALLF	get_lange_test_, SEG get_lange_test_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("TEST	AX,AX");
	ASM_INLINE("JNZ	_887B3");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("CALLF	m_game_main_lange_sub_, SEG m_game_main_lange_sub_");
	ASM_INLINE("DEC	[SI+0x02].W");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("MOV	BX,0x0001");
	ASM_INLINE("CALLF	m_game_main_lange_sub_, SEG m_game_main_lange_sub_");
ASM_INLINE("_887B3:");
	ASM_INLINE("POP	CX");
	ASM_INLINE("POP	DX");
	ASM_INLINE("JMP	_88803");
ASM_INLINE("_887B7:");
	ASM_INLINE("TEST	[0x0956].W,0x0400");
	ASM_INLINE("JZ	_88803");
	ASM_INLINE("MOV	AL,0x0C");
	ASM_INLINE("CALLF	sereq_, SEG sereq_");
	ASM_INLINE("CMP	[SI+0x02].W,0x0007");
	ASM_INLINE("JGE	_88803");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("MOV	AX,[BX+0x0B].W");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("MOV	BX,[BX+0x0D].W");
	ASM_INLINE("MOV	CX,[SI].W");
	ASM_INLINE("MOV	DX,[SI+0x02].W");
	ASM_INLINE("INC	DX");
	ASM_INLINE("CALLF	get_lange_test_, SEG get_lange_test_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("TEST	AX,AX");
	ASM_INLINE("JNZ	_88801");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("CALLF	m_game_main_lange_sub_, SEG m_game_main_lange_sub_");
	ASM_INLINE("INC	[SI+0x02].W");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("MOV	BX,0x0001");
	ASM_INLINE("CALLF	m_game_main_lange_sub_, SEG m_game_main_lange_sub_");
ASM_INLINE("_88801:");
	ASM_INLINE("POP	CX");
	ASM_INLINE("POP	DX");
ASM_INLINE("_88803:");
	ASM_INLINE("TEST	[0x0956].W,0x0800");
	ASM_INLINE("JZ	_8884B");
	ASM_INLINE("MOV	AL,0x0C");
	ASM_INLINE("CALLF	sereq_, SEG sereq_");
	ASM_INLINE("CMP	[SI].W,0x0000");
	ASM_INLINE("JLE	_88891");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("MOV	AX,[BX+0x0B].W");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("MOV	BX,[BX+0x0D].W");
	ASM_INLINE("MOV	CX,[SI].W");
	ASM_INLINE("DEC	CX");
	ASM_INLINE("MOV	DX,[SI+0x02].W");
	ASM_INLINE("CALLF	get_lange_test_, SEG get_lange_test_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("TEST	AX,AX");
	ASM_INLINE("JNZ	_88891");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("CALLF	m_game_main_lange_sub_, SEG m_game_main_lange_sub_");
	ASM_INLINE("DEC	[SI].W");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("MOV	BX,0x0001");
	ASM_INLINE("CALLF	m_game_main_lange_sub_, SEG m_game_main_lange_sub_");
	ASM_INLINE("JMP	_88891");
ASM_INLINE("_8884B:");
	ASM_INLINE("TEST	[0x0956].W,0x0200");
	ASM_INLINE("JZ	_88891");
	ASM_INLINE("MOV	AL,0x0C");
	ASM_INLINE("CALLF	sereq_, SEG sereq_");
	ASM_INLINE("CMP	[SI].W,0x0007");
	ASM_INLINE("JGE	_88891");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("MOV	AX,[BX+0x0B].W");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("MOV	BX,[BX+0x0D].W");
	ASM_INLINE("MOV	CX,[SI].W");
	ASM_INLINE("INC	CX");
	ASM_INLINE("MOV	DX,[SI+0x02].W");
	ASM_INLINE("CALLF	get_lange_test_, SEG get_lange_test_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("TEST	AX,AX");
	ASM_INLINE("JNZ	_88891");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("CALLF	m_game_main_lange_sub_, SEG m_game_main_lange_sub_");
	ASM_INLINE("INC	[SI].W");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("MOV	BX,0x0001");
	ASM_INLINE("CALLF	m_game_main_lange_sub_, SEG m_game_main_lange_sub_");
ASM_INLINE("_88891:");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
}

void m_game_main_weapon_i_type15()
{
	m_game_main_weapon_i_sub();
}

void m_game_main_weapon_m_type15()
{
	item_used_create; //Force include
	item_used_se; //Force include
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	DI,AX");
	ASM_INLINE("MOV	CX,DI");
	ASM_INLINE("ADD	CX,0x0045");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("ADD	BX,0x00AD");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,0xA711");
	ASM_INLINE("MOV	ES,AX");
	ASM_INLINE("MOV	SI,0x0000");
	ASM_INLINE("MOV	AX,[DI+0x00A9].W");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("ADD	AX,[DI+0x00A7].W");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("ADD	BX,0x0017");
	ASM_INLINE("ADD	BX,AX");
	ASM_INLINE("MOV	AX,[BX].W");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("ADD	SI,AX");
	ASM_INLINE("MOV	DX,ES:[SI+0x04].W");
	ASM_INLINE("AND	DX,0x00FF");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("CALLF	m_game_main_weapon_m_sub_, SEG m_game_main_weapon_m_sub_");
	ASM_INLINE("TEST	[0x0956].W,0x0004");
	ASM_INLINE("POP	BX");
	ASM_INLINE("JZ	_8893F");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	AL,0x0A");
	ASM_INLINE("CALLF	sereq_, SEG sereq_");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("CALLF	m_game_main_lange_sub_, SEG m_game_main_lange_sub_");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("MOV	BX,[BX+0x0B].W");
	ASM_INLINE("MOV	SI,CX");
	ASM_INLINE("MOV	CX,[SI+0x0D].W");
	ASM_INLINE("CALLF	put_lange_cousor_, SEG put_lange_cousor_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("MOV	[DI+0x00B1].W,0x0000");
	ASM_INLINE("POP	CX");
	ASM_INLINE("MOV	SI,CX");
	ASM_INLINE("POP	BX");
	ASM_INLINE("MOV	AX,[BX].W");
	ASM_INLINE("MOV	[SI+0x0B].W,AX");
	ASM_INLINE("MOV	SI,CX");
	ASM_INLINE("MOV	AX,[BX+0x02].W");
	ASM_INLINE("MOV	[SI+0x0D].W,AX");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("CALLF	item_used_create_, SEG item_used_create_");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("CALLF	item_used_se_, SEG item_used_se_");
	ASM_INLINE("JMP	_88974");
ASM_INLINE("_8893F:");
	ASM_INLINE("TEST	[0x0956].W,0x0008");
	ASM_INLINE("JZ	_88974");
	ASM_INLINE("MOV	AL,0x0B");
	ASM_INLINE("CALLF	sereq_, SEG sereq_");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("CALLF	m_game_main_lange_sub_, SEG m_game_main_lange_sub_");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("MOV	BX,[BX+0x0B].W");
	ASM_INLINE("MOV	SI,CX");
	ASM_INLINE("MOV	CX,[SI+0x0D].W");
	ASM_INLINE("CALLF	put_lange_cousor_, SEG put_lange_cousor_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("MOV	[DI+0x00B1].W,0x0000");
ASM_INLINE("_88974:");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
}

void m_game_main_weapon_i_type16(struct MGameWork *work)
{
	put_move_cousor(work, work->unk45[0].unk0B, work->unk45[0].unk0D, 2, 1);
}

void m_game_main_weapon_m_type16()
{
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	BX,AX");
	ASM_INLINE("MOV	SI,BX");
	ASM_INLINE("ADD	SI,0x0045");
	ASM_INLINE("MOV	DI,BX");
	ASM_INLINE("ADD	DI,0x006C");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("TEST	[0x0956].W,0x0100");
	ASM_INLINE("JZ	_88A1D");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AL,0x0C");
	ASM_INLINE("CALLF	sereq_, SEG sereq_");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("POP	BX");
	ASM_INLINE("JMP	_889F8");
ASM_INLINE("_889C0:");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("CMP	[SI+0x0D].W,0x0000");
	ASM_INLINE("JLE	_889F6");
	ASM_INLINE("MOV	DX,[SI+0x0D].W");
	ASM_INLINE("DEC	DX");
	ASM_INLINE("CMP	DX,[DI+0x0D].W");
	ASM_INLINE("JNZ	_889D8");
	ASM_INLINE("MOV	DX,[SI+0x0B].W");
	ASM_INLINE("CMP	DX,[DI+0x0B].W");
	ASM_INLINE("JZ	_889F6");
ASM_INLINE("_889D8:");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	AX,BX");
	ASM_INLINE("MOV	BX,[SI+0x0B].W");
	ASM_INLINE("MOV	CX,[SI+0x0D].W");
	ASM_INLINE("MOV	DX,0x0002");
	ASM_INLINE("CALLF	put_move_cousor_, SEG put_move_cousor_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("DEC	[SI+0x0D].W");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("POP	BX");
ASM_INLINE("_889F6:");
	ASM_INLINE("POP	AX");
	ASM_INLINE("INC	AX");
ASM_INLINE("_889F8:");
	ASM_INLINE("CMP	AX,0x0002");
	ASM_INLINE("JL	_889C0");
	ASM_INLINE("TEST	CX,CX");
	ASM_INLINE("JNZ	_88A04");
	ASM_INLINE("JMP	_88BAF");
ASM_INLINE("_88A04:");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	[BX+0x00B1].W,0x0000");
	ASM_INLINE("MOV	AX,BX");
	ASM_INLINE("CALLF	item_used_create_, SEG item_used_create_");
	ASM_INLINE("POP	BX");
	ASM_INLINE("MOV	AX,BX");
	ASM_INLINE("CALLF	item_used_se_, SEG item_used_se_");
	ASM_INLINE("JMP	_88BAF");
ASM_INLINE("_88A1D:");
	ASM_INLINE("TEST	[0x0956].W,0x0400");
	ASM_INLINE("JZ	_88A8F");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AL,0x0C");
	ASM_INLINE("CALLF	sereq_, SEG sereq_");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("POP	BX");
	ASM_INLINE("JMP	_88A6A");
ASM_INLINE("_88A32:");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("CMP	[SI+0x0D].W,0x0007");
	ASM_INLINE("JGE	_88A68");
	ASM_INLINE("MOV	DX,[SI+0x0D].W");
	ASM_INLINE("INC	DX");
	ASM_INLINE("CMP	DX,[DI+0x0D].W");
	ASM_INLINE("JNZ	_88A4A");
	ASM_INLINE("MOV	DX,[SI+0x0B].W");
	ASM_INLINE("CMP	DX,[DI+0x0B].W");
	ASM_INLINE("JZ	_88A68");
ASM_INLINE("_88A4A:");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	AX,BX");
	ASM_INLINE("MOV	BX,[SI+0x0B].W");
	ASM_INLINE("MOV	CX,[SI+0x0D].W");
	ASM_INLINE("MOV	DX,0x0002");
	ASM_INLINE("CALLF	put_move_cousor_, SEG put_move_cousor_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("INC	[SI+0x0D].W");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("POP	BX");
ASM_INLINE("_88A68:");
	ASM_INLINE("POP	AX");
	ASM_INLINE("INC	AX");
ASM_INLINE("_88A6A:");
	ASM_INLINE("CMP	AX,0x0002");
	ASM_INLINE("JL	_88A32");
	ASM_INLINE("TEST	CX,CX");
	ASM_INLINE("JNZ	_88A76");
	ASM_INLINE("JMP	_88BAF");
ASM_INLINE("_88A76:");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	[BX+0x00B1].W,0x0000");
	ASM_INLINE("MOV	AX,BX");
	ASM_INLINE("CALLF	item_used_create_, SEG item_used_create_");
	ASM_INLINE("POP	BX");
	ASM_INLINE("MOV	AX,BX");
	ASM_INLINE("CALLF	item_used_se_, SEG item_used_se_");
	ASM_INLINE("JMP	_88BAF");
ASM_INLINE("_88A8F:");
	ASM_INLINE("TEST	[0x0956].W,0x0800");
	ASM_INLINE("JZ	_88B01");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AL,0x0C");
	ASM_INLINE("CALLF	sereq_, SEG sereq_");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("POP	BX");
	ASM_INLINE("JMP	_88ADC");
ASM_INLINE("_88AA4:");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("CMP	[SI+0x0B].W,0x0000");
	ASM_INLINE("JLE	_88ADA");
	ASM_INLINE("MOV	DX,[SI+0x0D].W");
	ASM_INLINE("CMP	DX,[DI+0x0D].W");
	ASM_INLINE("JNZ	_88ABC");
	ASM_INLINE("MOV	DX,[SI+0x0B].W");
	ASM_INLINE("DEC	DX");
	ASM_INLINE("CMP	DX,[DI+0x0B].W");
	ASM_INLINE("JZ	_88ADA");
ASM_INLINE("_88ABC:");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	AX,BX");
	ASM_INLINE("MOV	BX,[SI+0x0B].W");
	ASM_INLINE("MOV	CX,[SI+0x0D].W");
	ASM_INLINE("MOV	DX,0x0002");
	ASM_INLINE("CALLF	put_move_cousor_, SEG put_move_cousor_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("DEC	[SI+0x0B].W");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("POP	BX");
ASM_INLINE("_88ADA:");
	ASM_INLINE("POP	AX");
	ASM_INLINE("INC	AX");
ASM_INLINE("_88ADC:");
	ASM_INLINE("CMP	AX,0x0002");
	ASM_INLINE("JL	_88AA4");
	ASM_INLINE("TEST	CX,CX");
	ASM_INLINE("JNZ	_88AE8");
	ASM_INLINE("JMP	_88BAF");
ASM_INLINE("_88AE8:");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	[BX+0x00B1].W,0x0000");
	ASM_INLINE("MOV	AX,BX");
	ASM_INLINE("CALLF	item_used_create_, SEG item_used_create_");
	ASM_INLINE("POP	BX");
	ASM_INLINE("MOV	AX,BX");
	ASM_INLINE("CALLF	item_used_se_, SEG item_used_se_");
	ASM_INLINE("JMP	_88BAF");
ASM_INLINE("_88B01:");
	ASM_INLINE("TEST	[0x0956].W,0x0200");
	ASM_INLINE("JZ	_88B6F");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AL,0x0C");
	ASM_INLINE("CALLF	sereq_, SEG sereq_");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("POP	BX");
	ASM_INLINE("JMP	_88B4E");
ASM_INLINE("_88B16:");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("CMP	[SI+0x0B].W,0x0007");
	ASM_INLINE("JGE	_88B4C");
	ASM_INLINE("MOV	DX,[SI+0x0D].W");
	ASM_INLINE("CMP	DX,[DI+0x0D].W");
	ASM_INLINE("JNZ	_88B2E");
	ASM_INLINE("MOV	DX,[SI+0x0B].W");
	ASM_INLINE("INC	DX");
	ASM_INLINE("CMP	DX,[DI+0x0B].W");
	ASM_INLINE("JZ	_88B4C");
ASM_INLINE("_88B2E:");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	AX,BX");
	ASM_INLINE("MOV	BX,[SI+0x0B].W");
	ASM_INLINE("MOV	CX,[SI+0x0D].W");
	ASM_INLINE("MOV	DX,0x0002");
	ASM_INLINE("CALLF	put_move_cousor_, SEG put_move_cousor_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("INC	[SI+0x0B].W");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("POP	BX");
ASM_INLINE("_88B4C:");
	ASM_INLINE("POP	AX");
	ASM_INLINE("INC	AX");
ASM_INLINE("_88B4E:");
	ASM_INLINE("CMP	AX,0x0002");
	ASM_INLINE("JL	_88B16");
	ASM_INLINE("TEST	CX,CX");
	ASM_INLINE("JZ	_88BAF");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	[BX+0x00B1].W,0x0000");
	ASM_INLINE("MOV	AX,BX");
	ASM_INLINE("CALLF	item_used_create_, SEG item_used_create_");
	ASM_INLINE("POP	BX");
	ASM_INLINE("MOV	AX,BX");
	ASM_INLINE("CALLF	item_used_se_, SEG item_used_se_");
	ASM_INLINE("JMP	_88BAF");
ASM_INLINE("_88B6F:");
	ASM_INLINE("TEST	[0x0956].W,0x0004");
	ASM_INLINE("JZ	_88B80");
	ASM_INLINE("MOV	AL,0x0A");
	ASM_INLINE("CALLF	sereq_, SEG sereq_");
	ASM_INLINE("JMP	_88BAF");
ASM_INLINE("_88B80:");
	ASM_INLINE("TEST	[0x0956].W,0x0008");
	ASM_INLINE("JZ	_88BAF");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AL,0x0B");
	ASM_INLINE("CALLF	sereq_, SEG sereq_");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("POP	BX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,BX");
	ASM_INLINE("MOV	BX,[SI+0x0B].W");
	ASM_INLINE("MOV	CX,[SI+0x0D].W");
	ASM_INLINE("MOV	DX,0x0002");
	ASM_INLINE("CALLF	put_move_cousor_, SEG put_move_cousor_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("POP	BX");
	ASM_INLINE("MOV	[BX+0x00B1].W,0x0000");
ASM_INLINE("_88BAF:");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
}

void m_game_main_weapon_i_type17(struct MGameWork *work)
{
	struct MGameWorkSub *ptr = &work->unk45[0];
	ptr->unk13 += 0x0F;
}

void m_game_main_weapon_m_type17(struct MGameWork *work)
{
	work->unkB1 = 0;
	item_used_create(work);
	item_used_se(work);
}

void m_game_main_weapon_i_type18()
{
	m_game_main_weapon_i_sub();
}

void m_game_main_weapon_m_type18()
{
	put_atack_hit_check; //Force include
	ASM_INLINE("PUSH	BP");
	ASM_INLINE("MOV	BP,SP");
	ASM_INLINE("SUB	SP,0x0016");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	DI,AX");
	ASM_INLINE("MOV	CX,DI");
	ASM_INLINE("ADD	CX,0x0045");
	ASM_INLINE("MOV	SI,DI");
	ASM_INLINE("ADD	SI,0x00AD");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("MOV	AX,0xA711");
	ASM_INLINE("MOV	ES,AX");
	ASM_INLINE("MOV	SI,0x0000");
	ASM_INLINE("MOV	AX,[DI+0x00A9].W");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("ADD	AX,[DI+0x00A7].W");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("ADD	BX,0x0017");
	ASM_INLINE("ADD	BX,AX");
	ASM_INLINE("MOV	AX,[BX].W");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("ADD	SI,AX");
	ASM_INLINE("MOV	DX,ES:[SI+0x04].W");
	ASM_INLINE("AND	DX,0x00FF");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("CALLF	m_game_main_weapon_m_sub_, SEG m_game_main_weapon_m_sub_");
	ASM_INLINE("TEST	[0x0956].W,0x0004");
	ASM_INLINE("POP	SI");
	ASM_INLINE("JNZ	_88C39");
	ASM_INLINE("JMP	_88CD6");
ASM_INLINE("_88C39:");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("MOV	AL,0x0A");
	ASM_INLINE("CALLF	sereq_, SEG sereq_");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("CALLF	m_game_main_lange_sub_, SEG m_game_main_lange_sub_");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("MOV	BX,[BX+0x0B].W");
	ASM_INLINE("MOV	SI,CX");
	ASM_INLINE("MOV	CX,[SI+0x0D].W");
	ASM_INLINE("CALLF	put_lange_cousor_, SEG put_lange_cousor_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("MOV	[DI+0x00B1].W,0x0000");
	ASM_INLINE("POP	SI");
	ASM_INLINE("PUSH	[DI+0x79].W");
	ASM_INLINE("PUSH	[DI+0x77].W");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("MOV	BX,[SI].W");
	ASM_INLINE("MOV	CX,[SI+0x02].W");
	ASM_INLINE("MOV	DX,[DI+0x00A9].W");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("ADD	DX,[DI+0x00A7].W");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("MOV	SI,DI");
	ASM_INLINE("ADD	SI,0x005C");
	ASM_INLINE("ADD	SI,DX");
	ASM_INLINE("MOV	DX,[SI].W");
	ASM_INLINE("CALLF	put_atack_hit_check_, SEG put_atack_hit_check_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("TEST	AX,0x0004");
	ASM_INLINE("JZ	_88D0B");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("LEA	DI,[BP-0x16].B");
	ASM_INLINE("MOV	SI,m_weapon_data_");
	ASM_INLINE("MOV	CX,0x0016");
	ASM_INLINE("PUSH	DS");
	ASM_INLINE("POP	ES");
	ASM_INLINE("CLD");
	ASM_INLINE("REP MOVSB");
	ASM_INLINE("MOV	AL,[0x1E07].B");
	ASM_INLINE("CMP	AL,0x03");
	ASM_INLINE("JZ	_88CC5");
	ASM_INLINE("CMP	AL,0x02");
	ASM_INLINE("JZ	_88CBD");
	ASM_INLINE("CMP	AL,0x01");
	ASM_INLINE("JZ	_88CC5");
	ASM_INLINE("TEST	AL,AL");
	ASM_INLINE("JZ	_88CC5");
	ASM_INLINE("JMP	_88CC5");
ASM_INLINE("_88CBD:");
	ASM_INLINE("LEA	AX,[BP-0x16].B");
	ASM_INLINE("CALLF	ip_w_, SEG ip_w_");
ASM_INLINE("_88CC5:");
	ASM_INLINE("POP	DI");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("CALLF	item_used_create_, SEG item_used_create_");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("CALLF	item_used_se_, SEG item_used_se_");
	ASM_INLINE("JMP	_88D0B");
ASM_INLINE("_88CD6:");
	ASM_INLINE("TEST	[0x0956].W,0x0008");
	ASM_INLINE("JZ	_88D0B");
	ASM_INLINE("MOV	AL,0x0B");
	ASM_INLINE("CALLF	sereq_, SEG sereq_");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("CALLF	m_game_main_lange_sub_, SEG m_game_main_lange_sub_");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("MOV	BX,[BX+0x0B].W");
	ASM_INLINE("MOV	SI,CX");
	ASM_INLINE("MOV	CX,[SI+0x0D].W");
	ASM_INLINE("CALLF	put_lange_cousor_, SEG put_lange_cousor_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("MOV	[DI+0x00B1].W,0x0000");
ASM_INLINE("_88D0B:");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
	ASM_INLINE("MOV	SP,BP");
	ASM_INLINE("POP	BP");
}

void m_game_main_weapon_i_type19()
{
	m_game_main_weapon_i_sub();
}

void m_game_main_weapon_m_type19()
{
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	DI,AX");
	ASM_INLINE("MOV	CX,DI");
	ASM_INLINE("ADD	CX,0x0045");
	ASM_INLINE("MOV	SI,DI");
	ASM_INLINE("ADD	SI,0x00AD");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("MOV	AX,0xA711");
	ASM_INLINE("MOV	ES,AX");
	ASM_INLINE("MOV	SI,0x0000");
	ASM_INLINE("MOV	AX,[DI+0x00A9].W");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("ADD	AX,[DI+0x00A7].W");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("ADD	BX,0x0017");
	ASM_INLINE("ADD	BX,AX");
	ASM_INLINE("MOV	AX,[BX].W");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("ADD	SI,AX");
	ASM_INLINE("MOV	DX,ES:[SI+0x04].W");
	ASM_INLINE("AND	DX,0x00FF");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("CALLF	m_game_main_weapon_m_sub_, SEG m_game_main_weapon_m_sub_");
	ASM_INLINE("TEST	[0x0956].W,0x0004");
	ASM_INLINE("POP	SI");
	ASM_INLINE("JZ	_88DE1");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("MOV	AL,0x0A");
	ASM_INLINE("CALLF	sereq_, SEG sereq_");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("CALLF	m_game_main_lange_sub_, SEG m_game_main_lange_sub_");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("MOV	BX,[BX+0x0B].W");
	ASM_INLINE("MOV	SI,CX");
	ASM_INLINE("MOV	CX,[SI+0x0D].W");
	ASM_INLINE("CALLF	put_lange_cousor_, SEG put_lange_cousor_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("MOV	[DI+0x00B1].W,0x0000");
	ASM_INLINE("POP	SI");
	ASM_INLINE("PUSH	[DI+0x79].W");
	ASM_INLINE("PUSH	[DI+0x77].W");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("MOV	BX,[SI].W");
	ASM_INLINE("MOV	CX,[SI+0x02].W");
	ASM_INLINE("MOV	DX,[DI+0x00A9].W");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("ADD	DX,[DI+0x00A7].W");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("MOV	SI,DI");
	ASM_INLINE("ADD	SI,0x005C");
	ASM_INLINE("ADD	SI,DX");
	ASM_INLINE("MOV	DX,[SI].W");
	ASM_INLINE("CALLF	put_atack_hit_check_, SEG put_atack_hit_check_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("TEST	AX,0x0004");
	ASM_INLINE("JZ	_88DD1");
	ASM_INLINE("MOV	[DI+0x016E].B,0x01");
ASM_INLINE("_88DD1:");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("CALLF	item_used_create_, SEG item_used_create_");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("CALLF	item_used_se_, SEG item_used_se_");
	ASM_INLINE("JMP	_88E16");
ASM_INLINE("_88DE1:");
	ASM_INLINE("TEST	[0x0956].W,0x0008");
	ASM_INLINE("JZ	_88E16");
	ASM_INLINE("MOV	AL,0x0B");
	ASM_INLINE("CALLF	sereq_, SEG sereq_");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("CALLF	m_game_main_lange_sub_, SEG m_game_main_lange_sub_");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("MOV	BX,[BX+0x0B].W");
	ASM_INLINE("MOV	SI,CX");
	ASM_INLINE("MOV	CX,[SI+0x0D].W");
	ASM_INLINE("CALLF	put_lange_cousor_, SEG put_lange_cousor_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("MOV	[DI+0x00B1].W,0x0000");
ASM_INLINE("_88E16:");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
}

void m_game_main_weapon_i_type20()
{
	m_game_main_weapon_i_sub();
}

void m_game_main_weapon_m_type20()
{
	ip_w; //Force include
	ASM_INLINE("PUSH	BP");
	ASM_INLINE("MOV	BP,SP");
	ASM_INLINE("SUB	SP,0x0016");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	DI,AX");
	ASM_INLINE("MOV	CX,DI");
	ASM_INLINE("ADD	CX,0x0045");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("ADD	BX,0x00AD");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,0xA711");
	ASM_INLINE("MOV	ES,AX");
	ASM_INLINE("MOV	SI,0x0000");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("MOV	AX,[BX+0x00A9].W");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("ADD	AX,[BX+0x00A7].W");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("ADD	BX,0x0017");
	ASM_INLINE("ADD	BX,AX");
	ASM_INLINE("MOV	AX,[BX].W");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("ADD	SI,AX");
	ASM_INLINE("MOV	DX,ES:[SI+0x04].W");
	ASM_INLINE("AND	DX,0x00FF");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("CALLF	m_game_main_weapon_m_sub_, SEG m_game_main_weapon_m_sub_");
	ASM_INLINE("TEST	[0x0956].W,0x0004");
	ASM_INLINE("POP	BX");
	ASM_INLINE("JNZ	_88E81");
	ASM_INLINE("JMP	_88F2B");
ASM_INLINE("_88E81:");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AL,0x0A");
	ASM_INLINE("CALLF	sereq_, SEG sereq_");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("CALLF	m_game_main_lange_sub_, SEG m_game_main_lange_sub_");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("MOV	BX,[BX+0x0B].W");
	ASM_INLINE("MOV	SI,CX");
	ASM_INLINE("MOV	CX,[SI+0x0D].W");
	ASM_INLINE("CALLF	put_lange_cousor_, SEG put_lange_cousor_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("MOV	SI,DI");
	ASM_INLINE("MOV	[SI+0x00B1].W,0x0000");
	ASM_INLINE("MOV	SI,DI");
	ASM_INLINE("POP	BX");
	ASM_INLINE("MOV	AX,[BX].W");
	ASM_INLINE("MOV	[SI+0x016F].B,AL");
	ASM_INLINE("MOV	SI,DI");
	ASM_INLINE("MOV	AX,[BX+0x02].W");
	ASM_INLINE("MOV	[SI+0x0170].B,AL");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("MOV	[BX+0x0171].B,0x00");
	ASM_INLINE("LEA	DI,[BP-0x16].B");
	ASM_INLINE("MOV	SI,m_weapon_data2_");
	ASM_INLINE("MOV	CX,0x0016");
	ASM_INLINE("PUSH	DS");
	ASM_INLINE("POP	ES");
	ASM_INLINE("CLD");
	ASM_INLINE("REP MOVSB");
	ASM_INLINE("MOV	AL,[0x1E07].B");
	ASM_INLINE("CMP	AL,0x03");
	ASM_INLINE("POP	DI");
	ASM_INLINE("JZ	_88F1B");
	ASM_INLINE("CMP	AL,0x02");
	ASM_INLINE("JZ	_88EEF");
	ASM_INLINE("CMP	AL,0x01");
	ASM_INLINE("JZ	_88F1B");
	ASM_INLINE("TEST	AL,AL");
	ASM_INLINE("JZ	_88F1B");
	ASM_INLINE("JMP	_88F1B");
ASM_INLINE("_88EEF:");
	ASM_INLINE("MOV	[BP-0x12].B,0x01");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("MOV	AL,[BX+0x016F].B");
	ASM_INLINE("SHL	AL,1");
	ASM_INLINE("SHL	AL,1");
	ASM_INLINE("SHL	AL,1");
	ASM_INLINE("SHL	AL,1");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("OR	AL,[BX+0x0170].B");
	ASM_INLINE("MOV	[BP-0x11].B,AL");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("MOV	AL,[BX+0x0171].B");
	ASM_INLINE("MOV	[BP-0x10].B,AL");
	ASM_INLINE("LEA	AX,[BP-0x16].B");
	ASM_INLINE("CALLF	ip_w_, SEG ip_w_");
ASM_INLINE("_88F1B:");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("CALLF	item_used_create_, SEG item_used_create_");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("CALLF	item_used_se_, SEG item_used_se_");
	ASM_INLINE("JMP	_88F62");
ASM_INLINE("_88F2B:");
	ASM_INLINE("TEST	[0x0956].W,0x0008");
	ASM_INLINE("JZ	_88F62");
	ASM_INLINE("MOV	AL,0x0B");
	ASM_INLINE("CALLF	sereq_, SEG sereq_");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("CALLF	m_game_main_lange_sub_, SEG m_game_main_lange_sub_");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("MOV	BX,[BX+0x0B].W");
	ASM_INLINE("MOV	SI,CX");
	ASM_INLINE("MOV	CX,[SI+0x0D].W");
	ASM_INLINE("CALLF	put_lange_cousor_, SEG put_lange_cousor_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("MOV	[BX+0x00B1].W,0x0000");
ASM_INLINE("_88F62:");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
	ASM_INLINE("MOV	SP,BP");
	ASM_INLINE("POP	BP");
}

void m_game_main_weapon_i_type21()
{
	m_game_main_weapon_i_sub();
}

void m_game_main_weapon_m_type21()
{
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	DI,AX");
	ASM_INLINE("MOV	CX,DI");
	ASM_INLINE("ADD	CX,0x0045");
	ASM_INLINE("MOV	SI,DI");
	ASM_INLINE("ADD	SI,0x00AD");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("MOV	AX,0xA711");
	ASM_INLINE("MOV	ES,AX");
	ASM_INLINE("MOV	SI,0x0000");
	ASM_INLINE("MOV	AX,[DI+0x00A9].W");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("ADD	AX,[DI+0x00A7].W");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("ADD	BX,0x0017");
	ASM_INLINE("ADD	BX,AX");
	ASM_INLINE("MOV	AX,[BX].W");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("ADD	SI,AX");
	ASM_INLINE("MOV	DX,ES:[SI+0x04].W");
	ASM_INLINE("AND	DX,0x00FF");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("CALLF	m_game_main_weapon_m_sub_, SEG m_game_main_weapon_m_sub_");
	ASM_INLINE("TEST	[0x0956].W,0x0004");
	ASM_INLINE("POP	SI");
	ASM_INLINE("JZ	_89038");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("MOV	AL,0x0A");
	ASM_INLINE("CALLF	sereq_, SEG sereq_");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("CALLF	m_game_main_lange_sub_, SEG m_game_main_lange_sub_");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("MOV	BX,[BX+0x0B].W");
	ASM_INLINE("MOV	SI,CX");
	ASM_INLINE("MOV	CX,[SI+0x0D].W");
	ASM_INLINE("CALLF	put_lange_cousor_, SEG put_lange_cousor_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("MOV	[DI+0x00B1].W,0x0000");
	ASM_INLINE("POP	SI");
	ASM_INLINE("PUSH	[DI+0x79].W");
	ASM_INLINE("PUSH	[DI+0x77].W");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("MOV	BX,[SI].W");
	ASM_INLINE("MOV	CX,[SI+0x02].W");
	ASM_INLINE("MOV	DX,[DI+0x00A9].W");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("ADD	DX,[DI+0x00A7].W");
	ASM_INLINE("SHL	DX,1");
	ASM_INLINE("MOV	SI,DI");
	ASM_INLINE("ADD	SI,0x005C");
	ASM_INLINE("ADD	SI,DX");
	ASM_INLINE("MOV	DX,[SI].W");
	ASM_INLINE("CALLF	put_atack_hit_check_, SEG put_atack_hit_check_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("TEST	AX,0x0004");
	ASM_INLINE("JZ	_89028");
	ASM_INLINE("MOV	[DI+0x016E].B,0x05");
ASM_INLINE("_89028:");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("CALLF	item_used_create_, SEG item_used_create_");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("CALLF	item_used_se_, SEG item_used_se_");
	ASM_INLINE("JMP	_8906D");
ASM_INLINE("_89038:");
	ASM_INLINE("TEST	[0x0956].W,0x0008");
	ASM_INLINE("JZ	_8906D");
	ASM_INLINE("MOV	AL,0x0B");
	ASM_INLINE("CALLF	sereq_, SEG sereq_");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("CALLF	m_game_main_lange_sub_, SEG m_game_main_lange_sub_");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("MOV	BX,[BX+0x0B].W");
	ASM_INLINE("MOV	SI,CX");
	ASM_INLINE("MOV	CX,[SI+0x0D].W");
	ASM_INLINE("CALLF	put_lange_cousor_, SEG put_lange_cousor_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("MOV	[DI+0x00B1].W,0x0000");
ASM_INLINE("_8906D:");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
}

