#include <machine.h>
#include "types.h"
#include "MEMORY.h"
#include "SWAN_L_C.h"
#include "SWANMAIN.h"
#include "SPRINTF.h"
#include "SYSTEM.h"

extern u8 far KEYBOARD_char_adr[];

memory_node_t memory_alloc_work[128]; /*096E*/
static memory_test_t memory_test; /*0D6E*/

static u8 memory_stuff[] = {
	0xA8, 0xC0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00
};

static char str0[] = "%04X:";
static char str1[] = "FAST:";
static char str2[] = "err.:";
static char str3[] = "%04X:";
static char str4[] = "err.:";
static char str5[] = "END.:";
static char str6[] = "%04X:";
static char str7[] = "%04X:";
static char str8[] = "FREE";
static char str9[] = "USE.";
static char str10[] = "err.";
static char str11[] = ">--=[  Memory Init. ]==--<";
static char str12[] = ".";
static char str13[] = "%1d.%02d";
static char str14[] = "%03d";

static const char far fstr1[] = "Memory test program";
static const char far fstr2[] = "                 level1.00";
static const char far fstr3[] = "memory-size:%dbytes";
static const char far fstr4[] = "SRAMaddress:%04Xh";
static const char far fstr5[] = "entry memory:%dbytes";
static const char far fstr6[] = "free  memory:%dbytes";
static const char far fstr7[] = "Initialize RIGHT+LEFT+A";
static const char far fstr8[] = "button push";

void meminit()
{
	u8 *p = (u8*)memory_alloc_work;
	memory_node_t *m;
	s16 i;
	for (i = sizeof(memory_alloc_work); i; i--)
	{
		*p++ = 0;
	}

	m = &memory_alloc_work[0];
	m->unk0 = (memory_node_t *)MEMORY_FLAG_FF41;
	m->unk2 = &memory_alloc_work[1];
	m->unk4 = 0;
	m->unk6 = MEMORY_FLAG_FF55;

	m = &memory_alloc_work[1];
	m->unk0 = &memory_alloc_work[0];
	m->unk2 = &memory_alloc_work[127];
	m->unk4 = 1000;
	m->unk6 = MEMORY_FLAG_FF46;
	
	m = &memory_alloc_work[127];
	m->unk0 = &memory_alloc_work[1];
	m->unk2 = (memory_node_t *)MEMORY_FLAG_FF42;
	m->unk4 = 0;
	m->unk6 = MEMORY_FLAG_FF55;
}

void *memalloc(u16 size)
{
	memory_node_t *m = memory_alloc_work;
	memory_node_t *n;
	memory_node_t *o;
	
	while(m->unk2 != (memory_node_t *)MEMORY_FLAG_FF42)
	{
		if(m->unk6 == MEMORY_FLAG_FF46 && ((8 + size) <= m->unk4))
		{
			n = (memory_node_t*)((u16)(m+1) + size);
			o = m->unk2;
			n->unk0 = m;
			n->unk2 = o;
			n->unk4 = m->unk4 - (8 + size);
			n->unk6 = MEMORY_FLAG_FF46;

			m->unk2 = n;
			m->unk4 = size;
			m->unk6 = MEMORY_FLAG_FF55;
			o->unk0 = n;

			return m+1;
		}
		m = m->unk2;
	}
	return 0;
}

static void near unk_81589(memory_node_t *n)
{
	memory_node_t *a, *b;

	a = n->unk2;
	b = a->unk2;
	if(a->unk6 == MEMORY_FLAG_FF46)
	{
		n->unk2 = a->unk2;
		b->unk0 = a->unk0;
		n->unk4 += a->unk4 + sizeof(memory_node_t);

	}
}

static void near unk_815B0(memory_node_t *n)
{
	n = n->unk0;
	if(n->unk6 == MEMORY_FLAG_FF46)
	{
		unk_81589(n);
	}
}

void memfree(memory_node_t *n)
{
	n--;
	n->unk6 = MEMORY_FLAG_FF46;
	unk_81589(n);
	unk_815B0(n);
}

void memory_test_init()
{
	task_delete; //Force include
	task_append; //Force include
	font_load; //Force include
	cls; //Force include
	print; //Force include
	hsprintf; //Force include
	nbg_ddf; //Force include
	ASM_INLINE("PUSH	BP");
	ASM_INLINE("MOV	BP,SP");
	ASM_INLINE("SUB	SP,0x0204");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("XOR	DI,DI");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("CALLF	task_delete_, SEG task_delete_");
	ASM_INLINE("MOV	AX,unk_81A34_");
	ASM_INLINE("MOV	BX,SEG unk_81A34_");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("CALLF	task_append_, SEG task_append_");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("MOV	CX,0x0000");
	ASM_INLINE("MOV	DX,0xA000");
	ASM_INLINE("CALLF	font_load_, SEG font_load_");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("CALLF	cls_, SEG cls_");
	ASM_INLINE("MOV	[BP-0x04].W,0x0000");
	ASM_INLINE("MOV	[BP-0x02].W,0xA075");
	ASM_INLINE("LEA	SI,[BP-0x0104].B");
ASM_INLINE("_8161E:");
	ASM_INLINE("INC	[BP-0x04].W");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("DEC	BX");
	ASM_INLINE("MOV	BL,ES:[BX].B");
	ASM_INLINE("MOV	[SI].B,BL");
	ASM_INLINE("INC	SI");
	ASM_INLINE("TEST	BL,BL");
	ASM_INLINE("JNZ	_8161E");
	ASM_INLINE("MOV	CX,0x0000");
	ASM_INLINE("MOV	BX,0xA000");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("MOV	BX,0x0001");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("LEA	DX,[BP-0x0104].B");
	ASM_INLINE("CALLF	print_, SEG print_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("MOV	[BP-0x04].W,0x0004");
	ASM_INLINE("MOV	[BP-0x02].W,0xA076");
	ASM_INLINE("LEA	SI,[BP-0x0104].B");
ASM_INLINE("_8165A:");
	ASM_INLINE("INC	[BP-0x04].W");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("DEC	BX");
	ASM_INLINE("MOV	BL,ES:[BX].B");
	ASM_INLINE("MOV	[SI].B,BL");
	ASM_INLINE("INC	SI");
	ASM_INLINE("TEST	BL,BL");
	ASM_INLINE("JNZ	_8165A");
	ASM_INLINE("MOV	CX,0x0000");
	ASM_INLINE("MOV	BX,0xA000");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("MOV	BX,0x0002");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("LEA	DX,[BP-0x0104].B");
	ASM_INLINE("CALLF	print_, SEG print_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("MOV	[BP-0x04].W,0x0000");
	ASM_INLINE("MOV	[BP-0x02].W,0xA078");
	ASM_INLINE("LEA	SI,[BP-0x0104].B");
ASM_INLINE("_81696:");
	ASM_INLINE("INC	[BP-0x04].W");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("DEC	BX");
	ASM_INLINE("MOV	BL,ES:[BX].B");
	ASM_INLINE("MOV	[SI].B,BL");
	ASM_INLINE("INC	SI");
	ASM_INLINE("TEST	BL,BL");
	ASM_INLINE("JNZ	_81696");
	ASM_INLINE("MOV	BX,0x0400");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("LEA	BX,[BP-0x0104].B");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("LEA	BX,[BP-0x0204].B");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("CALLF	hsprintf_, SEG hsprintf_");
	ASM_INLINE("ADD	SP,0x0006");
	ASM_INLINE("MOV	CX,0x0000");
	ASM_INLINE("MOV	BX,0xA000");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("MOV	BX,0x0003");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("LEA	DX,[BP-0x0204].B");
	ASM_INLINE("CALLF	print_, SEG print_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("MOV	[BP-0x04].W,0x0004");
	ASM_INLINE("MOV	[BP-0x02].W,0xA079");
	ASM_INLINE("LEA	SI,[BP-0x0104].B");
ASM_INLINE("_816E8:");
	ASM_INLINE("INC	[BP-0x04].W");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("DEC	BX");
	ASM_INLINE("MOV	BL,ES:[BX].B");
	ASM_INLINE("MOV	[SI].B,BL");
	ASM_INLINE("INC	SI");
	ASM_INLINE("TEST	BL,BL");
	ASM_INLINE("JNZ	_816E8");
	ASM_INLINE("MOV	BX,0x096E");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("LEA	BX,[BP-0x0104].B");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("LEA	BX,[BP-0x0204].B");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("CALLF	hsprintf_, SEG hsprintf_");
	ASM_INLINE("ADD	SP,0x0006");
	ASM_INLINE("MOV	CX,0x0000");
	ASM_INLINE("MOV	BX,0xA000");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("MOV	BX,0x0004");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("LEA	DX,[BP-0x0204].B");
	ASM_INLINE("CALLF	print_, SEG print_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("MOV	BX,0x0001");
	ASM_INLINE("CALLF	nbg_ddf_, SEG nbg_ddf_");
	ASM_INLINE("MOV	SI,0x0005");
	ASM_INLINE("MOV	BX,0x096E");
	ASM_INLINE("POP	AX");
ASM_INLINE("_8173E:");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	CX,BX");
	ASM_INLINE("SUB	CX,0x096E");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	CX,0x011A");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("LEA	CX,[BP-0x0204].B");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("CALLF	hsprintf_, SEG hsprintf_");
	ASM_INLINE("ADD	SP,0x0006");
	ASM_INLINE("MOV	DX,0x0000");
	ASM_INLINE("MOV	CX,0xA000");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("LEA	DX,[BP-0x0204].B");
	ASM_INLINE("CALLF	print_, SEG print_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("POP	BX");
	ASM_INLINE("MOV	CX,[BX].W");
	ASM_INLINE("CMP	CX,0xFF42");
	ASM_INLINE("JZ	_81798");
	ASM_INLINE("CMP	CX,0xFF41");
	ASM_INLINE("JNZ	_817AD");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	CX,0x0120");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("LEA	CX,[BP-0x0204].B");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("CALLF	hsprintf_, SEG hsprintf_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("POP	BX");
	ASM_INLINE("JMP	_817C7");
ASM_INLINE("_81798:");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	CX,0x0126");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("LEA	CX,[BP-0x0204].B");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("CALLF	hsprintf_, SEG hsprintf_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("POP	BX");
	ASM_INLINE("JMP	_817C7");
ASM_INLINE("_817AD:");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	CX,[BX].W");
	ASM_INLINE("SUB	CX,0x096E");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	CX,0x012C");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("LEA	CX,[BP-0x0204].B");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("CALLF	hsprintf_, SEG hsprintf_");
	ASM_INLINE("ADD	SP,0x0006");
	ASM_INLINE("POP	BX");
ASM_INLINE("_817C7:");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	DX,0x0000");
	ASM_INLINE("MOV	CX,0xA000");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("MOV	AX,0x0006");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("LEA	DX,[BP-0x0204].B");
	ASM_INLINE("CALLF	print_, SEG print_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("POP	BX");
	ASM_INLINE("MOV	CX,[BX+0x02].W");
	ASM_INLINE("CMP	CX,0xFF42");
	ASM_INLINE("JZ	_81809");
	ASM_INLINE("CMP	CX,0xFF41");
	ASM_INLINE("JNZ	_8181E");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	CX,0x0132");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("LEA	CX,[BP-0x0204].B");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("CALLF	hsprintf_, SEG hsprintf_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("POP	BX");
	ASM_INLINE("JMP	_81839");
ASM_INLINE("_81809:");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	CX,0x0138");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("LEA	CX,[BP-0x0204].B");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("CALLF	hsprintf_, SEG hsprintf_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("POP	BX");
	ASM_INLINE("JMP	_81839");
ASM_INLINE("_8181E:");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	CX,[BX+0x02].W");
	ASM_INLINE("SUB	CX,0x096E");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	CX,0x013E");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("LEA	CX,[BP-0x0204].B");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("CALLF	hsprintf_, SEG hsprintf_");
	ASM_INLINE("ADD	SP,0x0006");
	ASM_INLINE("POP	BX");
ASM_INLINE("_81839:");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	DX,0x0000");
	ASM_INLINE("MOV	CX,0xA000");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("MOV	AX,0x000B");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("LEA	DX,[BP-0x0204].B");
	ASM_INLINE("CALLF	print_, SEG print_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("POP	BX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("PUSH	[BX+0x04].W");
	ASM_INLINE("MOV	CX,0x0144");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("LEA	CX,[BP-0x0204].B");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("CALLF	hsprintf_, SEG hsprintf_");
	ASM_INLINE("ADD	SP,0x0006");
	ASM_INLINE("MOV	DX,0x0000");
	ASM_INLINE("MOV	CX,0xA000");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("MOV	AX,0x0010");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("LEA	DX,[BP-0x0204].B");
	ASM_INLINE("CALLF	print_, SEG print_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("POP	BX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	CX,[BX+0x06].W");
	ASM_INLINE("CMP	CX,0xFF55");
	ASM_INLINE("JZ	_818AC");
	ASM_INLINE("CMP	CX,0xFF46");
	ASM_INLINE("JNZ	_818BF");
	ASM_INLINE("MOV	CX,0x014A");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("LEA	CX,[BP-0x0204].B");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("CALLF	hsprintf_, SEG hsprintf_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("JMP	_818D0");
ASM_INLINE("_818AC:");
	ASM_INLINE("MOV	CX,0x0150");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("LEA	CX,[BP-0x0204].B");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("CALLF	hsprintf_, SEG hsprintf_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("JMP	_818D0");
ASM_INLINE("_818BF:");
	ASM_INLINE("MOV	CX,0x0156");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("LEA	CX,[BP-0x0204].B");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("CALLF	hsprintf_, SEG hsprintf_");
	ASM_INLINE("ADD	SP,0x0004");
ASM_INLINE("_818D0:");
	ASM_INLINE("MOV	DX,0x0000");
	ASM_INLINE("MOV	CX,0xA000");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("MOV	AX,0x0015");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("LEA	DX,[BP-0x0204].B");
	ASM_INLINE("CALLF	print_, SEG print_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("POP	BX");
	ASM_INLINE("MOV	CX,[BX+0x06].W");
	ASM_INLINE("CMP	CX,0xFF55");
	ASM_INLINE("POP	AX");
	ASM_INLINE("JZ	_81902");
	ASM_INLINE("CMP	CX,0xFF46");
	ASM_INLINE("JNZ	_81905");
	ASM_INLINE("ADD	AX,[BX+0x04].W");
	ASM_INLINE("JMP	_81905");
ASM_INLINE("_81902:");
	ASM_INLINE("ADD	DI,[BX+0x04].W");
ASM_INLINE("_81905:");
	ASM_INLINE("INC	SI");
	ASM_INLINE("CMP	[BX+0x02].W,0xFF42");
	ASM_INLINE("JZ	_81913");
	ASM_INLINE("MOV	BX,[BX+0x02].W");
	ASM_INLINE("JMP	_8173E");
ASM_INLINE("_81913:");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	[BP-0x04].W,0x0006");
	ASM_INLINE("MOV	[BP-0x02].W,0xA07A");
	ASM_INLINE("LEA	DI,[BP-0x0104].B");
ASM_INLINE("_81923:");
	ASM_INLINE("INC	[BP-0x04].W");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("DEC	BX");
	ASM_INLINE("MOV	AL,ES:[BX].B");
	ASM_INLINE("MOV	[DI].B,AL");
	ASM_INLINE("INC	DI");
	ASM_INLINE("TEST	AL,AL");
	ASM_INLINE("JNZ	_81923");
	ASM_INLINE("POP	DI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("LEA	BX,[BP-0x0104].B");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("LEA	BX,[BP-0x0204].B");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("CALLF	hsprintf_, SEG hsprintf_");
	ASM_INLINE("ADD	SP,0x0006");
	ASM_INLINE("MOV	CX,0x0000");
	ASM_INLINE("MOV	BX,0xA000");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("LEA	DX,[BP-0x0204].B");
	ASM_INLINE("CALLF	print_, SEG print_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("INC	SI");
	ASM_INLINE("MOV	[BP-0x04].W,0x000C");
	ASM_INLINE("MOV	[BP-0x02].W,0xA07B");
	ASM_INLINE("LEA	DI,[BP-0x0104].B");
ASM_INLINE("_81973:");
	ASM_INLINE("INC	[BP-0x04].W");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("DEC	BX");
	ASM_INLINE("MOV	BL,ES:[BX].B");
	ASM_INLINE("MOV	[DI].B,BL");
	ASM_INLINE("INC	DI");
	ASM_INLINE("TEST	BL,BL");
	ASM_INLINE("JNZ	_81973");
	ASM_INLINE("POP	AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("LEA	AX,[BP-0x0104].B");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("LEA	AX,[BP-0x0204].B");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("CALLF	hsprintf_, SEG hsprintf_");
	ASM_INLINE("ADD	SP,0x0006");
	ASM_INLINE("MOV	BX,0x0000");
	ASM_INLINE("MOV	AX,0xA000");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("LEA	DX,[BP-0x0204].B");
	ASM_INLINE("CALLF	print_, SEG print_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("INC	SI");
	ASM_INLINE("MOV	[BP-0x04].W,0x0002");
	ASM_INLINE("MOV	[BP-0x02].W,0xA07D");
	ASM_INLINE("LEA	DI,[BP-0x0104].B");
ASM_INLINE("_819C3:");
	ASM_INLINE("INC	[BP-0x04].W");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("DEC	BX");
	ASM_INLINE("MOV	AL,ES:[BX].B");
	ASM_INLINE("MOV	[DI].B,AL");
	ASM_INLINE("INC	DI");
	ASM_INLINE("TEST	AL,AL");
	ASM_INLINE("JNZ	_819C3");
	ASM_INLINE("MOV	BX,0x0000");
	ASM_INLINE("MOV	AX,0xA000");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("LEA	DX,[BP-0x0104].B");
	ASM_INLINE("CALLF	print_, SEG print_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("INC	SI");
	ASM_INLINE("MOV	[BP-0x04].W,0x000A");
	ASM_INLINE("MOV	[BP-0x02].W,0xA07E");
	ASM_INLINE("LEA	DI,[BP-0x0104].B");
ASM_INLINE("_819FF:");
	ASM_INLINE("INC	[BP-0x04].W");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("DEC	BX");
	ASM_INLINE("MOV	AL,ES:[BX].B");
	ASM_INLINE("MOV	[DI].B,AL");
	ASM_INLINE("INC	DI");
	ASM_INLINE("TEST	AL,AL");
	ASM_INLINE("JNZ	_819FF");
	ASM_INLINE("MOV	BX,0x0000");
	ASM_INLINE("MOV	AX,0xA000");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("LEA	DX,[BP-0x0104].B");
	ASM_INLINE("CALLF	print_, SEG print_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
	ASM_INLINE("MOV	SP,BP");
	ASM_INLINE("POP	BP");
}

static void unk_81A34()
{
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("TEST	[0x0952].W,0x0800");
	ASM_INLINE("JZ	_81A6E");
	ASM_INLINE("TEST	[0x0952].W,0x0200");
	ASM_INLINE("JZ	_81A6E");
	ASM_INLINE("TEST	[0x0956].W,0x0004");
	ASM_INLINE("JZ	_81A6E");
	ASM_INLINE("MOV	BX,0x0000");
	ASM_INLINE("MOV	AX,0xA000");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("MOV	DX,0x015C");
	ASM_INLINE("CALLF	print_, SEG print_");
	ASM_INLINE("ADD	SP,0x0004");
	ASM_INLINE("CALLF	meminit_, SEG meminit_");
ASM_INLINE("_81A6E:");
	ASM_INLINE("TEST	[0x0952].W,0x8000");
	ASM_INLINE("JZ	_81A98");
	ASM_INLINE("TEST	[0x0952].W,0x2000");
	ASM_INLINE("JZ	_81A98");
	ASM_INLINE("TEST	[0x0956].W,0x0004");
	ASM_INLINE("JZ	_81A98");
	ASM_INLINE("CALLF	task_delete_, SEG task_delete_");
	ASM_INLINE("MOV	AX,memory_dump_init_");
	ASM_INLINE("MOV	BX,SEG memory_dump_init_");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("CALLF	task_append_, SEG task_append_");
ASM_INLINE("_81A98:");
	ASM_INLINE("TEST	[0x0952].W,0x1000");
	ASM_INLINE("JZ	_81AA6");
	ASM_INLINE("MOV	[0x0110].W,0x0000");
ASM_INLINE("_81AA6:");
	ASM_INLINE("TEST	[0x0952].W,0x4000");
	ASM_INLINE("JZ	_81AB4");
	ASM_INLINE("MOV	[0x0110].W,0x0001");
ASM_INLINE("_81AB4:");
	ASM_INLINE("CMP	[0x0110].W,0x0000");
	ASM_INLINE("JZ	_81AF4");
	ASM_INLINE("CALLF	0x0007, 0x91D2");
	ASM_INLINE("AND	AX,0x0003");
	ASM_INLINE("CMP	AX,0x0003");
	ASM_INLINE("JZ	_81AEE");
	ASM_INLINE("CMP	AX,0x0002");
	ASM_INLINE("JZ	_81AE6");
	ASM_INLINE("CMP	AX,0x0001");
	ASM_INLINE("JZ	_81ADE");
	ASM_INLINE("TEST	AX,AX");
	ASM_INLINE("JNZ	_81AF4");
	ASM_INLINE("OR	[0x0956].W,0x0100");
	ASM_INLINE("JMP	_81AF4");
ASM_INLINE("_81ADE:");
	ASM_INLINE("OR	[0x0956].W,0x0200");
	ASM_INLINE("JMP	_81AF4");
ASM_INLINE("_81AE6:");
	ASM_INLINE("OR	[0x0956].W,0x0400");
	ASM_INLINE("JMP	_81AF4");
ASM_INLINE("_81AEE:");
	ASM_INLINE("OR	[0x0956].W,0x0800");
ASM_INLINE("_81AF4:");
	ASM_INLINE("TEST	[0x0956].W,0x0100");
	ASM_INLINE("JZ	_81B30");
	ASM_INLINE("CMP	[0x0112].W,0x0000");
	ASM_INLINE("JZ	_81B13");
	ASM_INLINE("MOV	AX,[0x0112].W");
	ASM_INLINE("CALLF	memfree_, SEG memfree_");
	ASM_INLINE("MOV	[0x0112].W,0x0000");
	ASM_INLINE("JMP	_81B1E");
ASM_INLINE("_81B13:");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("CALLF	memalloc_, SEG memalloc_");
	ASM_INLINE("MOV	[0x0112].W,AX");
ASM_INLINE("_81B1E:");
	ASM_INLINE("CALLF	task_delete_, SEG task_delete_");
	ASM_INLINE("MOV	AX,memory_test_init_");
	ASM_INLINE("MOV	BX,SEG memory_test_init_ ");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("CALLF	task_append_, SEG task_append_");
ASM_INLINE("_81B30:");
	ASM_INLINE("TEST	[0x0956].W,0x0200");
	ASM_INLINE("JZ	_81B6C");
	ASM_INLINE("CMP	[0x0114].W,0x0000");
	ASM_INLINE("JZ	_81B4F");
	ASM_INLINE("MOV	AX,[0x0114].W");
	ASM_INLINE("CALLF	memfree_, SEG memfree_");
	ASM_INLINE("MOV	[0x0114].W,0x0000");
	ASM_INLINE("JMP	_81B5A");
ASM_INLINE("_81B4F:");
	ASM_INLINE("MOV	AX,0x0002");
	ASM_INLINE("CALLF	memalloc_, SEG memalloc_");
	ASM_INLINE("MOV	[0x0114].W,AX");
ASM_INLINE("_81B5A:");
	ASM_INLINE("CALLF	task_delete_, SEG task_delete_");
	ASM_INLINE("MOV	AX,memory_test_init_");
	ASM_INLINE("MOV	BX,SEG memory_test_init_");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("CALLF	task_append_, SEG task_append_");
ASM_INLINE("_81B6C:");
	ASM_INLINE("TEST	[0x0956].W,0x0400");
	ASM_INLINE("JZ	_81BA8");
	ASM_INLINE("CMP	[0x0116].W,0x0000");
	ASM_INLINE("JZ	_81B8B");
	ASM_INLINE("MOV	AX,[0x0116].W");
	ASM_INLINE("CALLF	memfree_, SEG memfree_");
	ASM_INLINE("MOV	[0x0116].W,0x0000");
	ASM_INLINE("JMP	_81B96");
ASM_INLINE("_81B8B:");
	ASM_INLINE("MOV	AX,0x0003");
	ASM_INLINE("CALLF	memalloc_, SEG memalloc_");
	ASM_INLINE("MOV	[0x0116].W,AX");
ASM_INLINE("_81B96:");
	ASM_INLINE("CALLF	task_delete_, SEG task_delete_");
	ASM_INLINE("MOV	AX,memory_test_init_");
	ASM_INLINE("MOV	BX,SEG memory_test_init_");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("CALLF	task_append_, SEG task_append_");
ASM_INLINE("_81BA8:");
	ASM_INLINE("TEST	[0x0956].W,0x0800");
	ASM_INLINE("JZ	_81BE4");
	ASM_INLINE("CMP	[0x0118].W,0x0000");
	ASM_INLINE("JZ	_81BC7");
	ASM_INLINE("MOV	AX,[0x0118].W");
	ASM_INLINE("CALLF	memfree_, SEG memfree_");
	ASM_INLINE("MOV	[0x0118].W,0x0000");
	ASM_INLINE("JMP	_81BD2");
ASM_INLINE("_81BC7:");
	ASM_INLINE("MOV	AX,0x0004");
	ASM_INLINE("CALLF	memalloc_, SEG memalloc_");
	ASM_INLINE("MOV	[0x0118].W,AX");
ASM_INLINE("_81BD2:");
	ASM_INLINE("CALLF	task_delete_, SEG task_delete_");
	ASM_INLINE("MOV	AX,memory_test_init_");
	ASM_INLINE("MOV	BX,SEG memory_test_init_");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("CALLF	task_append_, SEG task_append_");
ASM_INLINE("_81BE4:");
	ASM_INLINE("TEST	[0x0956].W,0x0002");
	ASM_INLINE("JZ	_81BF1");
	ASM_INLINE("CALLF	task_delete_, SEG task_delete_");
ASM_INLINE("_81BF1:");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
}

static void unk_81BF4(s16 unk, s16 unk2, u16 unk3)
{
	font_putXY(unk3,8,1,1,unk>>3,unk2>>3,0,KEYBOARD_char_adr);
}

static void unk_81C27(u16 unk)
{
	font_putXY(0x10,2+unk,3,1,3,0,0,KEYBOARD_char_adr);
}

static void unk_81C56(u16 unk)
{
	unk_81BF4(0x50,0,(unk >> 12) & 0xf);
	unk_81BF4(0x58,0,(unk >>  8) & 0xf);
	unk_81BF4(0x60,0,(unk >>  4) & 0xf);
	unk_81BF4(0x68,0,(unk >>  0) & 0xf);
}

static void unk_81CB3(u16 unk)
{
	unk_81BF4(0x88,0,(unk >> 12) & 0xf);
	unk_81BF4(0x90,0,(unk >>  8) & 0xf);
	unk_81BF4(0x98,0,(unk >>  4) & 0xf);
	unk_81BF4(0xA0,0,(unk >>  0) & 0xf);
}

static void unk_81D10(s16 unk)
{
	unk_81BF4(0xC0,0,(unk >>  4) & 0xf);
	unk_81BF4(0xC8,0,(unk >>  0) & 0xf);
}

static void unk_81D3F(u16 unk, u16 unk2, u16 unk3, u16 unk4)
{
	/*u16 iVar2;
	u16 iVar3;
	u8 *local_6;

	local_6 = unk3;
	switch(unk)
	{
		case 0:
			break;
		case 1:
			break;
		case 2:
		{
			for (iVar2 = 0; iVar2 < 8; iVar2++)
			{
				unk_81BF4(0x00, iVar2 * 8 + 0x10, ((u16)local_6 >> 12) & 0xf);
				unk_81BF4(0x08, iVar2 * 8 + 0x10, ((u16)local_6 >>  8) & 0xf);
				unk_81BF4(0x10, iVar2 * 8 + 0x10, ((u16)local_6 >>  4) & 0xf);
				unk_81BF4(0x18, iVar2 * 8 + 0x10, ((u16)local_6 >>  0) & 0xf);
				for (iVar3 = 0; iVar3 < 8; iVar3++)
				{
					unk_81BF4(iVar3 * 0x18 + 0x28, iVar2 * 8 + 0x10, ((*local_6 >> 4) & 0xf));
					unk_81BF4(iVar3 * 0x18 + 0x30, iVar2 * 8 + 0x10, ((*local_6 >> 0) & 0xf));
					local_6++;
				}
			}
			break;
		}
		case 3:
			break;
	}*/
	ASM_INLINE("PUSH	BP");
	ASM_INLINE("MOV	BP,SP");
	ASM_INLINE("SUB	SP,0x0004");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("XOR	DX,DX");
	ASM_INLINE("MOV	BX,BX");
	ASM_INLINE("XOR	DX,DX");
	ASM_INLINE("XOR	SI,SI");
	ASM_INLINE("OR	DX,CX");
	ASM_INLINE("OR	BX,SI");
	ASM_INLINE("MOV	[BP-0x04].W,DX");
	ASM_INLINE("MOV	[BP-0x02].W,BX");
	ASM_INLINE("CMP	AX,0x0003");
	ASM_INLINE("JNZ	_81D63");
	ASM_INLINE("JMP	_81E5B");
ASM_INLINE("_81D63:");
	ASM_INLINE("CMP	AX,0x0002");
	ASM_INLINE("JZ	_81D7A");
	ASM_INLINE("CMP	AX,0x0001");
	ASM_INLINE("JNZ	_81D70");
	ASM_INLINE("JMP	_81E5B");
ASM_INLINE("_81D70:");
	ASM_INLINE("TEST	AX,AX");
	ASM_INLINE("JNZ	_81D77");
	ASM_INLINE("JMP	_81E5B");
ASM_INLINE("_81D77:");
	ASM_INLINE("JMP	_81E5B");
ASM_INLINE("_81D7A:");
	ASM_INLINE("XOR	SI,SI");
	ASM_INLINE("JMP	_81E53");
ASM_INLINE("_81D7F:");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("ADD	BX,0x0010");
	ASM_INLINE("MOV	DX,[BP-0x04].W");
	ASM_INLINE("MOV	CL,0x0C");
	ASM_INLINE("SHR	DX,CL");
	ASM_INLINE("AND	DX,0x000F");
	ASM_INLINE("MOV	CX,DX");
	ASM_INLINE("CALLF	unk_81BF4_, SEG unk_81BF4_");
	ASM_INLINE("MOV	AX,0x0008");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("ADD	BX,0x0010");
	ASM_INLINE("MOV	DX,[BP-0x04].W");
	ASM_INLINE("MOV	CL,0x08");
	ASM_INLINE("SHR	DX,CL");
	ASM_INLINE("AND	DX,0x000F");
	ASM_INLINE("MOV	CX,DX");
	ASM_INLINE("CALLF	unk_81BF4_, SEG unk_81BF4_");
	ASM_INLINE("MOV	AX,0x0010");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("ADD	BX,0x0010");
	ASM_INLINE("MOV	CX,[BP-0x04].W");
	ASM_INLINE("SHR	CX,1");
	ASM_INLINE("SHR	CX,1");
	ASM_INLINE("SHR	CX,1");
	ASM_INLINE("SHR	CX,1");
	ASM_INLINE("AND	CX,0x000F");
	ASM_INLINE("CALLF	unk_81BF4_, SEG unk_81BF4_");
	ASM_INLINE("MOV	AX,0x0018");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("ADD	BX,0x0010");
	ASM_INLINE("MOV	CX,[BP-0x04].W");
	ASM_INLINE("AND	CX,0x000F");
	ASM_INLINE("CALLF	unk_81BF4_, SEG unk_81BF4_");
	ASM_INLINE("XOR	DI,DI");
	ASM_INLINE("JMP	_81E4D");
ASM_INLINE("_81DFE:");
	ASM_INLINE("INC	[BP-0x04].W");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("DEC	BX");
	ASM_INLINE("MOV	CL,ES:[BX].B");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	AX,0x0018");
	ASM_INLINE("MUL	DI");
	ASM_INLINE("ADD	AX,0x0028");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("ADD	BX,0x0010");
	ASM_INLINE("SHR	CL,1");
	ASM_INLINE("SHR	CL,1");
	ASM_INLINE("SHR	CL,1");
	ASM_INLINE("SHR	CL,1");
	ASM_INLINE("AND	CL,0x0F");
	ASM_INLINE("XOR	CH,CH");
	ASM_INLINE("CALLF	unk_81BF4_, SEG unk_81BF4_");
	ASM_INLINE("MOV	AX,0x0018");
	ASM_INLINE("MUL	DI");
	ASM_INLINE("ADD	AX,0x0030");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("ADD	BX,0x0010");
	ASM_INLINE("POP	CX");
	ASM_INLINE("AND	CL,0x0F");
	ASM_INLINE("XOR	CH,CH");
	ASM_INLINE("CALLF	unk_81BF4_, SEG unk_81BF4_");
	ASM_INLINE("INC	DI");
ASM_INLINE("_81E4D:");
	ASM_INLINE("CMP	DI,0x0008");
	ASM_INLINE("JL	_81DFE");
	ASM_INLINE("INC	SI");
ASM_INLINE("_81E53:");
	ASM_INLINE("CMP	SI,0x0008");
	ASM_INLINE("JGE	_81E5B");
	ASM_INLINE("JMP	_81D7F");
ASM_INLINE("_81E5B:");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
	ASM_INLINE("MOV	SP,BP");
	ASM_INLINE("POP	BP");
}

void memory_dump_init()
{
	get_bmp_cell_no; //Force include
	put_cell_no; //Force include
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("CALLF	task_delete_, SEG task_delete_");
	ASM_INLINE("MOV	AX,unk_82093_");
	ASM_INLINE("MOV	BX,SEG unk_82093_");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("CALLF	task_append_, SEG task_append_");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("CALLF	nbg_ddf_, SEG nbg_ddf_");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("CALLF	nbg_ddf_, SEG nbg_ddf_");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("MOV	CX,0x0000");
	ASM_INLINE("MOV	DX,0xA478");
	ASM_INLINE("CALLF	font_load_, SEG font_load_");
	ASM_INLINE("MOV	AX,0xA478");
	ASM_INLINE("MOV	ES,AX");
	ASM_INLINE("MOV	AX,ES:[0x0004].W");
	ASM_INLINE("SAR	AX,1");
	ASM_INLINE("SAR	AX,1");
	ASM_INLINE("SAR	AX,1");
	ASM_INLINE("DEC	AX");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("MOV	CX,0x0000");
	ASM_INLINE("MOV	DX,0xA478");
	ASM_INLINE("CALLF	get_bmp_cell_no_, SEG get_bmp_cell_no_");
	ASM_INLINE("MOV	SI,AX");
	ASM_INLINE("XOR	DI,DI");
	ASM_INLINE("JMP	_81EFF");
ASM_INLINE("_81EBD:");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("JMP	_81EF9");
ASM_INLINE("_81EC1:");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("MOV	DX,SI");
	ASM_INLINE("CALLF	put_cell_no_, SEG put_cell_no_");
	ASM_INLINE("POP	AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("MOV	DX,SI");
	ASM_INLINE("OR	DX,0x0800");
	ASM_INLINE("CALLF	put_cell_no_, SEG put_cell_no_");
	ASM_INLINE("POP	AX");
	ASM_INLINE("INC	AX");
ASM_INLINE("_81EF9:");
	ASM_INLINE("CMP	AX,0x0020");
	ASM_INLINE("JL	_81EC1");
	ASM_INLINE("INC	DI");
ASM_INLINE("_81EFF:");
	ASM_INLINE("CMP	DI,0x0020");
	ASM_INLINE("JL	_81EBD");
	ASM_INLINE("MOV	AX,0x000F");
	ASM_INLINE("MOV	BX,0x0007");
	ASM_INLINE("MOV	CX,0x0000");
	ASM_INLINE("MOV	DX,0xA478");
	ASM_INLINE("CALLF	get_bmp_cell_no_, SEG get_bmp_cell_no_");
	ASM_INLINE("MOV	SI,AX");
	ASM_INLINE("MOV	AX,0x0010");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("MOV	DX,SI");
	ASM_INLINE("OR	DX,0x0A00");
	ASM_INLINE("CALLF	put_cell_no_, SEG put_cell_no_");
	ASM_INLINE("MOV	AX,0x0048");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("MOV	DX,SI");
	ASM_INLINE("OR	DX,0x0A00");
	ASM_INLINE("CALLF	put_cell_no_, SEG put_cell_no_");
	ASM_INLINE("MOV	AX,0x0080");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("MOV	DX,SI");
	ASM_INLINE("OR	DX,0x0A00");
	ASM_INLINE("CALLF	put_cell_no_, SEG put_cell_no_");
	ASM_INLINE("MOV	AX,0x00B8");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("MOV	DX,SI");
	ASM_INLINE("OR	DX,0x0A00");
	ASM_INLINE("CALLF	put_cell_no_, SEG put_cell_no_");
	ASM_INLINE("XOR	DI,DI");
	ASM_INLINE("JMP	_81F84");
ASM_INLINE("_81F67:");
	ASM_INLINE("MOV	AX,0x0018");
	ASM_INLINE("MOV	BX,0x0001");
	ASM_INLINE("ADD	BX,DI");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("MOV	DX,SI");
	ASM_INLINE("OR	DX,0x0A00");
	ASM_INLINE("CALLF	put_cell_no_, SEG put_cell_no_");
	ASM_INLINE("INC	DI");
ASM_INLINE("_81F84:");
	ASM_INLINE("CMP	DI,0x000A");
	ASM_INLINE("JL	_81F67");
	ASM_INLINE("XOR	SI,SI");
	ASM_INLINE("JMP	_81FC0");
ASM_INLINE("_81F8D:");
	ASM_INLINE("XOR	DI,DI");
	ASM_INLINE("JMP	_81FBA");
ASM_INLINE("_81F91:");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("MOV	CX,0x0000");
	ASM_INLINE("MOV	DX,0xA478");
	ASM_INLINE("CALLF	get_bmp_cell_no_, SEG get_bmp_cell_no_");
	ASM_INLINE("MOV	DX,AX");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("CALLF	put_cell_no_, SEG put_cell_no_");
	ASM_INLINE("INC	DI");
ASM_INLINE("_81FBA:");
	ASM_INLINE("CMP	DI,0x001C");
	ASM_INLINE("JL	_81F91");
	ASM_INLINE("INC	SI");
ASM_INLINE("_81FC0:");
	ASM_INLINE("CMP	SI,0x0002");
	ASM_INLINE("JL	_81F8D");
	ASM_INLINE("XOR	SI,SI");
	ASM_INLINE("JMP	_82002");
ASM_INLINE("_81FC9:");
	ASM_INLINE("XOR	DI,DI");
	ASM_INLINE("JMP	_81FFC");
ASM_INLINE("_81FCD:");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("MOV	BX,0x000A");
	ASM_INLINE("ADD	BX,SI");
	ASM_INLINE("MOV	CX,0x0000");
	ASM_INLINE("MOV	DX,0xA478");
	ASM_INLINE("CALLF	get_bmp_cell_no_, SEG get_bmp_cell_no_");
	ASM_INLINE("MOV	DX,AX");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("MOV	BX,0x000A");
	ASM_INLINE("ADD	BX,SI");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("CALLF	put_cell_no_, SEG put_cell_no_");
	ASM_INLINE("INC	DI");
ASM_INLINE("_81FFC:");
	ASM_INLINE("CMP	DI,0x001C");
	ASM_INLINE("JL	_81FCD");
	ASM_INLINE("INC	SI");
ASM_INLINE("_82002:");
	ASM_INLINE("CMP	SI,0x0002");
	ASM_INLINE("JL	_81FC9");
	ASM_INLINE("MOV	BX,0x0000");
	ASM_INLINE("MOV	AX,0xA478");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x000C");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("MOV	BX,0x000C");
	ASM_INLINE("MOV	CX,0x001C");
	ASM_INLINE("MOV	DX,0x0006");
	ASM_INLINE("CALLF	font_putXY_, SEG font_putXY_");
	ASM_INLINE("ADD	SP,0x000A");
	ASM_INLINE("MOV	[0x0D6E].W,0x0002");
	ASM_INLINE("MOV	[0x0D70].W,0x0000");
	ASM_INLINE("MOV	[0x0D72].W,0x1000");
	ASM_INLINE("MOV	[0x0D74].W,0x0000");
	ASM_INLINE("MOV	AX,[0x0D6E].W");
	ASM_INLINE("CALLF	unk_81C27_, SEG unk_81C27_");
	ASM_INLINE("MOV	AX,[0x0D72].W");
	ASM_INLINE("CALLF	unk_81C56_, SEG unk_81C56_");
	ASM_INLINE("MOV	AX,[0x0D74].W");
	ASM_INLINE("CALLF	unk_81CB3_, SEG unk_81CB3_");
	ASM_INLINE("MOV	AX,[0x0D70].W");
	ASM_INLINE("CALLF	unk_81D10_, SEG unk_81D10_");
	ASM_INLINE("MOV	AX,[0x0D6E].W");
	ASM_INLINE("MOV	BX,[0x0D72].W");
	ASM_INLINE("MOV	CX,[0x0D74].W");
	ASM_INLINE("MOV	DX,[0x0D70].W");
	ASM_INLINE("CALLF	unk_81D3F_, SEG unk_81D3F_");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("MOV	BX,0x0001");
	ASM_INLINE("CALLF	nbg_ddf_, SEG nbg_ddf_");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("MOV	BX,0x0001");
	ASM_INLINE("CALLF	nbg_ddf_, SEG nbg_ddf_");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
}

static void unk_82093()
{
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("TEST	[0x095A].W,0x0100");
	ASM_INLINE("JZ	_820B8");
	ASM_INLINE("SUB	[0x0D74].W,0x0010");
	ASM_INLINE("MOV	AX,[0x0D6E].W");
	ASM_INLINE("MOV	BX,[0x0D72].W");
	ASM_INLINE("MOV	CX,[0x0D74].W");
	ASM_INLINE("MOV	DX,[0x0D70].W");
	ASM_INLINE("CALLF	unk_81D3F_, SEG unk_81D3F_");
	ASM_INLINE("JMP	_820D9");
ASM_INLINE("_820B8:");
	ASM_INLINE("TEST	[0x095A].W,0x0400");
	ASM_INLINE("JZ	_820D9");
	ASM_INLINE("ADD	[0x0D74].W,0x0010");
	ASM_INLINE("MOV	AX,[0x0D6E].W");
	ASM_INLINE("MOV	BX,[0x0D72].W");
	ASM_INLINE("MOV	CX,[0x0D74].W");
	ASM_INLINE("MOV	DX,[0x0D70].W");
	ASM_INLINE("CALLF	unk_81D3F_, SEG unk_81D3F_");
ASM_INLINE("_820D9:");
	ASM_INLINE("TEST	[0x095A].W,0x0200");
	ASM_INLINE("JZ	_820FB");
	ASM_INLINE("DEC	[0x0D74].W");
	ASM_INLINE("MOV	AX,[0x0D6E].W");
	ASM_INLINE("MOV	BX,[0x0D72].W");
	ASM_INLINE("MOV	CX,[0x0D74].W");
	ASM_INLINE("MOV	DX,[0x0D70].W");
	ASM_INLINE("CALLF	unk_81D3F_, SEG unk_81D3F_");
	ASM_INLINE("JMP	_8211B");
ASM_INLINE("_820FB:");
	ASM_INLINE("TEST	[0x095A].W,0x0800");
	ASM_INLINE("JZ	_8211B");
	ASM_INLINE("INC	[0x0D74].W");
	ASM_INLINE("MOV	AX,[0x0D6E].W");
	ASM_INLINE("MOV	BX,[0x0D72].W");
	ASM_INLINE("MOV	CX,[0x0D74].W");
	ASM_INLINE("MOV	DX,[0x0D70].W");
	ASM_INLINE("CALLF	unk_81D3F_, SEG unk_81D3F_");
ASM_INLINE("_8211B:");
	ASM_INLINE("TEST	[0x0956].W,0x0002");
	ASM_INLINE("JZ	_82128");
	ASM_INLINE("CALLF	task_delete_, SEG task_delete_");
ASM_INLINE("_82128:");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
}








