#include <machine.h>
#include "types.h"
#include "PAD.h"
#include "SWAN_L_C.h"
#include "MEMORY.h"
#include "SWANMAIN.h"
#include "IP_MES.h"

struct padState pad;

void pad_init()
{
	pad.unkC = 0;
	pad.unkA = 0;
	pad.unk8 = 0;
	pad.unk6 = 0;
	pad.unk4 = 0;
	pad.unk2 = 0;
	pad.unk0 = 0;
	pad.unk1A = 0;
	pad.unk18 = 0;
	pad.unk16 = 0;
	pad.unk14 = 0;
	pad.unk12 = 0;
	pad.unk10 = 0;
	pad.unkE = 0;
}

void pad_task()
{	
	pad_in; //Force include
	meminit; //Force include
	tsk_init; //Force include
	remain; //Force include
	ip_w; //Force include
	ip_r; //Force include
	ASM_INLINE("PUSH	BP");
	ASM_INLINE("MOV	BP,SP");
	ASM_INLINE("SUB	SP,0x0016");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("LEA	DI,[BP-0x16].B");
	ASM_INLINE("MOV	SI,0x00FA");
	ASM_INLINE("MOV	CX,0x0016");
	ASM_INLINE("PUSH	DS");
	ASM_INLINE("POP	ES");
	ASM_INLINE("CLD");
	ASM_INLINE("REP MOVSB");
	ASM_INLINE("MOV	SI,pad_");
	ASM_INLINE("CALLF	pad_in_, SEG pad_in_");
	ASM_INLINE("MOV	[SI].W,AX");
	ASM_INLINE("TEST	[pad_].W,0x0004");
	ASM_INLINE("JZ	_813F2");
	ASM_INLINE("TEST	[pad_].W,0x0008");
	ASM_INLINE("JZ	_813F2");
	ASM_INLINE("TEST	[pad_].W,0x0002");
	ASM_INLINE("JZ	_813F2");
	ASM_INLINE("CALLF	meminit_, SEG meminit_");
	ASM_INLINE("CALLF	pad_init_, SEG pad_init_");
	ASM_INLINE("CALLF	tsk_init_, SEG tsk_init_");
	ASM_INLINE("CALLF	remain_, SEG remain_");
ASM_INLINE("_813F2:");
	ASM_INLINE("MOV	AX,[pad_].W");
	ASM_INLINE("CMP	AX,[pad_+2].W");
	ASM_INLINE("JZ	_81419");
	ASM_INLINE("MOV	AX,[pad_].W");
	ASM_INLINE("MOV	CL,0x08");
	ASM_INLINE("SHR	AX,CL");
	ASM_INLINE("AND	AX,0x00FF");
	ASM_INLINE("MOV	[BP-0x12].B,AL");
	ASM_INLINE("MOV	AX,[pad_].W");
	ASM_INLINE("AND	AX,0x00FF");
	ASM_INLINE("MOV	[BP-0x11].B,AL");
	ASM_INLINE("LEA	AX,[BP-0x16].B");
	ASM_INLINE("CALLF	ip_w_, SEG ip_w_");
ASM_INLINE("_81419:");
	ASM_INLINE("LEA	AX,[BP-0x16].B");
	ASM_INLINE("CALLF	ip_r_, SEG ip_r_");
	ASM_INLINE("TEST	AX,AX");
	ASM_INLINE("JNZ	_81432");
	ASM_INLINE("MOV	AL,[BP-0x12].B");
	ASM_INLINE("MOV	AH,AL");
	ASM_INLINE("MOV	BL,[BP-0x11].B");
	ASM_INLINE("MOV	AL,BL");
	ASM_INLINE("MOV	[pad_+16].W,AX");
ASM_INLINE("_81432:");
	ASM_INLINE("MOV	AX,[pad_+16].W");
	ASM_INLINE("MOV	[pad_+14].W,AX");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("JMP	_81492");
ASM_INLINE("_8143C:");
	ASM_INLINE("MOV	AX,[SI+0x02].W");
	ASM_INLINE("NOT	AX");
	ASM_INLINE("AND	AX,[SI].W");
	ASM_INLINE("MOV	[SI+0x06].W,AX");
	ASM_INLINE("MOV	[SI+0x04].W,AX");
	ASM_INLINE("CMP	[SI+0x04].W,0x0000");
	ASM_INLINE("JZ	_81462");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("MOV	AX,[SI].W");
	ASM_INLINE("MOV	[BX+0x08].W,AX");
	ASM_INLINE("MOV	[SI+0x0A].W,0x0000");
	ASM_INLINE("MOV	[SI+0x0C].W,0x0003");
	ASM_INLINE("JMP	_81487");
ASM_INLINE("_81462:");
	ASM_INLINE("MOV	[SI+0x08].W,0x0000");
	ASM_INLINE("CMP	[SI+0x0A].W,0x0009");
	ASM_INLINE("JBE	_81484");
	ASM_INLINE("INC	[SI+0x0C].W");
	ASM_INLINE("CMP	[SI+0x0C].W,0x0003");
	ASM_INLINE("JBE	_81487");
	ASM_INLINE("MOV	[SI+0x0C].W,0x0000");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("MOV	AX,[SI].W");
	ASM_INLINE("MOV	[BX+0x08].W,AX");
	ASM_INLINE("JMP	_81487");
ASM_INLINE("_81484:");
	ASM_INLINE("INC	[SI+0x0A].W");
ASM_INLINE("_81487:");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("MOV	AX,[SI].W");
	ASM_INLINE("MOV	[BX+0x02].W,AX");
	ASM_INLINE("INC	CX");
	ASM_INLINE("ADD	SI,0x000E");
ASM_INLINE("_81492:");
	ASM_INLINE("CMP	CX,0x0002");
	ASM_INLINE("JL	_8143C");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	CX");
	ASM_INLINE("MOV	SP,BP");
	ASM_INLINE("POP	BP");
}

void get_pad()
{
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("MOV	CX,AX");
	ASM_INLINE("MOV	SI,BX");
ASM_INLINE("_814A5:");
	ASM_INLINE("CALLF	pad_task_, SEG pad_task_");
	ASM_INLINE("MOV	AX,CX");
	ASM_INLINE("MOV	BX,0x000E");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("MOV	BX,AX");
	ASM_INLINE("ADD	BX,pad_");
	ASM_INLINE("CMP	[BX+0x08].W,0x0000");
	ASM_INLINE("JNZ	_814C1");
	ASM_INLINE("TEST	SI,SI");
	ASM_INLINE("JNZ	_814A5");
ASM_INLINE("_814C1:");
	ASM_INLINE("MOV	AX,CX");
	ASM_INLINE("MOV	BX,0x000E");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("MOV	BX,AX");
	ASM_INLINE("ADD	BX,pad_");
	ASM_INLINE("MOV	AX,[BX+0x08].W");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
}

