#include <machine.h>
#include <memory.h>
#include "types.h"
#include "SERIAL.h"
#include "SYSTEM.h"

//SERIAL.c
u8 com_user = 0; /*020C*/
u16 com_unk = 1; /*020E*/
u16 com_unk2 = 0; /*0210*/

sSerialInfo_t rcv_work;
u8 receive_buf[260]; /*0D8C*/
static u8 unk0; /*0E90*/

static s16 near unk_82F8B(u8 a);
static s16 near unk_82FB2();
static void near unk_82FD3();
static void near unk_82FFF();
static void near unk_83097();

static u16 near unk_82BAC(sSerialInfo_t *a, u16 b)
{
	u8 ret = a->unkA[((a->unk0 + a->unk4) & 0xFF)];
	a->unk4++;
	return ret;
}

static void near unk_82BC4(sSerialInfo_t *a)
{
	a->unk0 += a->unk4;
	a->unk0 &= 0xFF;
	a->unk4 = 0;
	a->unk8--;
}

static s16 near unk_82BDC(sSerialInfo_t *a, u8 data)
{
	u16 val;
	u16 idx = (a->unk2 + a->unk6);

	if(a->unk0)
	{
		val = a->unk0 - 1;
	}
	else
	{
		val = 0xFF;
	}

	if((idx & 0xFF) != val)
	{
		a->unkA[(idx & 0xFF)] = data;
		a->unk6++;
		return 0;
	}
	return -1;
}

static void near unk_82C14(sSerialInfo_t *a)
{
	a->unk2 += a->unk6;
	a->unk2 &= 0xFF;
	a->unk6 = 0;
	a->unk8++;
}

void serial_init()
{
	memset(&rcv_work, 0, sizeof(sSerialInfo_t));
	rcv_work.unkA = receive_buf;

	{
		//required to match
		u8 val = 0xC0;
		outp8(0xB3,val);
	}
}

static void near unk_82C48()
{
	/*s16 val1;
	s16 val2;
	s16 val3;
	int i;
	
	val1 = unk_82FB2();
	if(val1 < 0)
	{
		return -1;
	}
	unk_82F8B();
	unk_82BDC(&rcv_work,val1);

	val2 = unk_82FB2();
	if(val2 < 0)
	{
		return -1;
	}
	unk_82F8B();

	val3 = unk_82FB2();
	if(val3 < 0)
	{
		return -1;
	}
	unk_82F8B();

	for(i = 0; i < val1; i++)
	{

	}*/

	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("XOR	DL,DL");
	ASM_INLINE("CALL	unk_82FB2_");
	ASM_INLINE("MOV	DI,AX");
	ASM_INLINE("CMP	DI,0x0000");
	ASM_INLINE("JGE	_82C5E");
	ASM_INLINE("MOV	AX,0xFFFF");
	ASM_INLINE("JMP	_82D24");
ASM_INLINE("_82C5E:");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("CALL	unk_82F8B_");
	ASM_INLINE("MOV	AX,0x0D80");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("CALL	unk_82BDC_");
	ASM_INLINE("CALL	unk_82FB2_");
	ASM_INLINE("MOV	CX,AX");
	ASM_INLINE("CMP	CX,0x0000");
	ASM_INLINE("JGE	_82C7B");
	ASM_INLINE("MOV	AX,0xFFFF");
	ASM_INLINE("JMP	_82D24");
ASM_INLINE("_82C7B:");
	ASM_INLINE("MOV	AL,CL");
	ASM_INLINE("CALL	unk_82F8B_");
	ASM_INLINE("MOV	AX,CX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("CALL	unk_82FB2_");
	ASM_INLINE("MOV	CX,AX");
	ASM_INLINE("CMP	CX,0x0000");
	ASM_INLINE("POP	AX");
	ASM_INLINE("JGE	_82C94");
	ASM_INLINE("MOV	AX,0xFFFF");
	ASM_INLINE("JMP	_82D24");
ASM_INLINE("_82C94:");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AL,CL");
	ASM_INLINE("CALL	unk_82F8B_");
	ASM_INLINE("CALL	unk_82FB2_");
	ASM_INLINE("MOV	CX,AX");
	ASM_INLINE("CMP	CX,0x0000");
	ASM_INLINE("POP	AX");
	ASM_INLINE("JGE	_82CAA");
	ASM_INLINE("MOV	AX,0xFFFF");
	ASM_INLINE("JMP	_82D24");
ASM_INLINE("_82CAA:");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("MOV	AL,BL");
	ASM_INLINE("CALL	unk_82F8B_");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("XOR	SI,SI");
	ASM_INLINE("POP	AX");
	ASM_INLINE("JMP	_82CFD");
ASM_INLINE("_82CB9:");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("CALL	unk_82FB2_");
	ASM_INLINE("MOV	CX,AX");
	ASM_INLINE("MOV	AL,CL");
	ASM_INLINE("CALL	unk_82F8B_");
	ASM_INLINE("CMP	AX,0x0000");
	ASM_INLINE("POP	AX");
	ASM_INLINE("POP	BX");
	ASM_INLINE("JGE	_82CD1");
	ASM_INLINE("MOV	AX,0xFFFF");
	ASM_INLINE("JMP	_82D24");
ASM_INLINE("_82CD1:");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	BL,AL");
	ASM_INLINE("XOR	BH,BH");
	ASM_INLINE("CMP	CX,BX");
	ASM_INLINE("JNZ	_82CF0");
	ASM_INLINE("MOV	BX,[0x0D82].W");
	ASM_INLINE("ADD	BX,[0x0D86].W");
	ASM_INLINE("DEC	BX");
	ASM_INLINE("AND	BX,0x00FF");
	ASM_INLINE("ADD	BX,[0x0D8A].W");
	ASM_INLINE("MOV	CL,[BX].B");
	ASM_INLINE("XOR	CH,CH");
ASM_INLINE("_82CF0:");
	ASM_INLINE("MOV	AX,0x0D80");
	ASM_INLINE("MOV	BL,CL");
	ASM_INLINE("CALL	unk_82BDC_");
	ASM_INLINE("ADD	DL,CL");
	ASM_INLINE("INC	SI");
	ASM_INLINE("POP	AX");
	ASM_INLINE("POP	BX");
ASM_INLINE("_82CFD:");
	ASM_INLINE("CMP	SI,DI");
	ASM_INLINE("JL	_82CB9");
	ASM_INLINE("CMP	DL,BL");
	ASM_INLINE("JNZ	_82D0D");
	ASM_INLINE("MOV	AX,0x0D80");
	ASM_INLINE("CALL	unk_82C14_");
	ASM_INLINE("JMP	_82D13");
ASM_INLINE("_82D0D:");
	ASM_INLINE("MOV	[0x0D86].W,0x0000");
ASM_INLINE("_82D13:");
	ASM_INLINE("MOV	AL,DL");
	ASM_INLINE("CALL	unk_82F8B_");
	ASM_INLINE("CMP	AX,0x0000");
	ASM_INLINE("JGE	_82D22");
	ASM_INLINE("MOV	AX,0xFFFF");
	ASM_INLINE("JMP	_82D24");
ASM_INLINE("_82D22:");
	ASM_INLINE("XOR	AX,AX");
ASM_INLINE("_82D24:");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
}

void serial_receive()
{
	ASM_INLINE("INC	[0x100A].W");
	ASM_INLINE("PUSHF");
	ASM_INLINE("CLI");
	ASM_INLINE("CALL	unk_82FB2_");
	ASM_INLINE("CMP	AL,0x04");
	ASM_INLINE("JZ	_82D62");
	ASM_INLINE("CMP	AL,0x5A");
	ASM_INLINE("JNZ	_82D6F");
	ASM_INLINE("CMP	[0x020C].B,0x01");
	ASM_INLINE("JZ	_82D46");
	ASM_INLINE("CALL	unk_83097_");
	ASM_INLINE("JMP	_82D49");
ASM_INLINE("_82D46:");
	ASM_INLINE("CALL	unk_82FFF_");
ASM_INLINE("_82D49:");
	ASM_INLINE("CMP	[0x020C].B,0x00");
	ASM_INLINE("JZ	_82D6F");
	ASM_INLINE("CALL	unk_82FB2_");
	ASM_INLINE("CMP	AX,0x0004");
	ASM_INLINE("JZ	_82D5C");
	ASM_INLINE("MOV	AL,0x01");
	ASM_INLINE("JMP	_82D5E");
ASM_INLINE("_82D5C:");
	ASM_INLINE("XOR	AL,AL");
ASM_INLINE("_82D5E:");
	ASM_INLINE("TEST	AL,AL");
	ASM_INLINE("JNZ	_82D6F");
ASM_INLINE("_82D62:");
	ASM_INLINE("MOV	AL,0x04");
	ASM_INLINE("CALL	unk_82F8B_");
	ASM_INLINE("CMP	AX,0x0000");
	ASM_INLINE("JL	_82D6F");
	ASM_INLINE("CALL	unk_82C48_");
ASM_INLINE("_82D6F:");
	ASM_INLINE("POPF");
}

void serial_in()
{
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("MOV	CX,AX");
	ASM_INLINE("MOV	SI,BX");
	ASM_INLINE("CMP	[0x0D88].W,0x0000");
	ASM_INLINE("JNZ	_82D83");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("JMP	_82DA8");
ASM_INLINE("_82D83:");
	ASM_INLINE("MOV	AX,0x0D80");
	ASM_INLINE("CALL	unk_82BAC_");
	ASM_INLINE("MOV	[SI].W,AX");
	ASM_INLINE("XOR	DX,DX");
	ASM_INLINE("JMP	_82D9C");
ASM_INLINE("_82D8F:");
	ASM_INLINE("MOV	AX,0x0D80");
	ASM_INLINE("CALL	unk_82BAC_");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("ADD	BX,DX");
	ASM_INLINE("MOV	[BX].B,AL");
	ASM_INLINE("INC	DX");
ASM_INLINE("_82D9C:");
	ASM_INLINE("CMP	DX,[SI].W");
	ASM_INLINE("JL	_82D8F");
	ASM_INLINE("MOV	AX,0x0D80");
	ASM_INLINE("CALL	unk_82BC4_");
	ASM_INLINE("MOV	AX,CX");
ASM_INLINE("_82DA8:");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
}

void serial_out_sub()
{
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	SI,AX");
	ASM_INLINE("MOV	DX,BX");
	ASM_INLINE("MOV	CL,[SI].B");
	ASM_INLINE("INC	CL");
	ASM_INLINE("MOV	AL,0x04");
	ASM_INLINE("CALL	unk_82F8B_");
	ASM_INLINE("CMP	AX,0x0000");
	ASM_INLINE("JGE	_82DC8");
	ASM_INLINE("MOV	AX,0xFFFF");
	ASM_INLINE("JMP	_82EEA");
ASM_INLINE("_82DC8:");
	ASM_INLINE("CALL	unk_82FB2_");
	ASM_INLINE("CMP	AX,0x0000");
	ASM_INLINE("JGE	_82DE3");
	ASM_INLINE("MOV	AL,0x04");
	ASM_INLINE("CALL	unk_82F8B_");
	ASM_INLINE("CMP	AX,0x0000");
	ASM_INLINE("JGE	_82DE0");
	ASM_INLINE("MOV	AX,0xFFFF");
	ASM_INLINE("JMP	_82EEA");
ASM_INLINE("_82DE0:");
	ASM_INLINE("CALL	unk_82FB2_");
ASM_INLINE("_82DE3:");
	ASM_INLINE("CMP	AX,0x0004");
	ASM_INLINE("JZ	_82DEE");
	ASM_INLINE("MOV	AX,0xFFFF");
	ASM_INLINE("JMP	_82EEA");
ASM_INLINE("_82DEE:");
	ASM_INLINE("MOV	AL,DL");
	ASM_INLINE("CALL	unk_82F8B_");
	ASM_INLINE("CMP	AX,0x0000");
	ASM_INLINE("JGE	_82DFE");
	ASM_INLINE("MOV	AX,0xFFFF");
	ASM_INLINE("JMP	_82EEA");
ASM_INLINE("_82DFE:");
	ASM_INLINE("CALL	unk_82FB2_");
	ASM_INLINE("CMP	AX,DX");
	ASM_INLINE("JZ	_82E0B");
	ASM_INLINE("MOV	AX,0xFFFF");
	ASM_INLINE("JMP	_82EEA");
ASM_INLINE("_82E0B:");
	ASM_INLINE("MOV	AL,[0x0E8C].B");
	ASM_INLINE("CALL	unk_82F8B_");
	ASM_INLINE("CMP	AX,0x0000");
	ASM_INLINE("JGE	_82E1C");
	ASM_INLINE("MOV	AX,0xFFFF");
	ASM_INLINE("JMP	_82EEA");
ASM_INLINE("_82E1C:");
	ASM_INLINE("CALL	unk_82FB2_");
	ASM_INLINE("MOV	BL,[0x0E8C].B");
	ASM_INLINE("XOR	BH,BH");
	ASM_INLINE("CMP	AX,BX");
	ASM_INLINE("JZ	_82E2F");
	ASM_INLINE("MOV	AX,0xFFFF");
	ASM_INLINE("JMP	_82EEA");
ASM_INLINE("_82E2F:");
	ASM_INLINE("MOV	AL,[0x0E8E].B");
	ASM_INLINE("CALL	unk_82F8B_");
	ASM_INLINE("CMP	AX,0x0000");
	ASM_INLINE("JGE	_82E40");
	ASM_INLINE("MOV	AX,0xFFFF");
	ASM_INLINE("JMP	_82EEA");
ASM_INLINE("_82E40:");
	ASM_INLINE("CALL	unk_82FB2_");
	ASM_INLINE("MOV	BL,[0x0E8E].B");
	ASM_INLINE("XOR	BH,BH");
	ASM_INLINE("CMP	AX,BX");
	ASM_INLINE("JZ	_82E53");
	ASM_INLINE("MOV	AX,0xFFFF");
	ASM_INLINE("JMP	_82EEA");
ASM_INLINE("_82E53:");
	ASM_INLINE("MOV	AL,[0x0E90].B");
	ASM_INLINE("CALL	unk_82F8B_");
	ASM_INLINE("CMP	AX,0x0000");
	ASM_INLINE("JGE	_82E64");
	ASM_INLINE("MOV	AX,0xFFFF");
	ASM_INLINE("JMP	_82EEA");
ASM_INLINE("_82E64:");
	ASM_INLINE("CALL	unk_82FB2_");
	ASM_INLINE("MOV	BL,[0x0E90].B");
	ASM_INLINE("XOR	BH,BH");
	ASM_INLINE("CMP	AX,BX");
	ASM_INLINE("JZ	_82E76");
	ASM_INLINE("MOV	AX,0xFFFF");
	ASM_INLINE("JMP	_82EEA");
ASM_INLINE("_82E76:");
	ASM_INLINE("XOR	DI,DI");
	ASM_INLINE("JMP	_82ED2");
ASM_INLINE("_82E7A:");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("ADD	BX,DI");
	ASM_INLINE("CMP	CL,[BX].B");
	ASM_INLINE("JNZ	_82EA4");
	ASM_INLINE("MOV	AL,[0x0E8C].B");
	ASM_INLINE("CALL	unk_82F8B_");
	ASM_INLINE("CMP	AX,0x0000");
	ASM_INLINE("JGE	_82E92");
	ASM_INLINE("MOV	AX,0xFFFF");
	ASM_INLINE("JMP	_82EEA");
ASM_INLINE("_82E92:");
	ASM_INLINE("CALL	unk_82FB2_");
	ASM_INLINE("MOV	BL,[0x0E8C].B");
	ASM_INLINE("XOR	BH,BH");
	ASM_INLINE("CMP	AX,BX");
	ASM_INLINE("JZ	_82ECB");
	ASM_INLINE("MOV	AX,0xFFFF");
	ASM_INLINE("JMP	_82EEA");
ASM_INLINE("_82EA4:");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("ADD	BX,DI");
	ASM_INLINE("MOV	AL,[BX].B");
	ASM_INLINE("CALL	unk_82F8B_");
	ASM_INLINE("CMP	AX,0x0000");
	ASM_INLINE("JGE	_82EB7");
	ASM_INLINE("MOV	AX,0xFFFF");
	ASM_INLINE("JMP	_82EEA");
ASM_INLINE("_82EB7:");
	ASM_INLINE("CALL	unk_82FB2_");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("ADD	BX,DI");
	ASM_INLINE("MOV	BL,[BX].B");
	ASM_INLINE("XOR	BH,BH");
	ASM_INLINE("CMP	AX,BX");
	ASM_INLINE("JZ	_82ECB");
	ASM_INLINE("MOV	AX,0xFFFF");
	ASM_INLINE("JMP	_82EEA");
ASM_INLINE("_82ECB:");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("ADD	BX,DI");
	ASM_INLINE("MOV	CL,[BX].B");
	ASM_INLINE("INC	DI");
ASM_INLINE("_82ED2:");
	ASM_INLINE("CMP	DI,DX");
	ASM_INLINE("JL	_82E7A");
	ASM_INLINE("CALL	unk_82FB2_");
	ASM_INLINE("MOV	BL,[0x0E90].B");
	ASM_INLINE("XOR	BH,BH");
	ASM_INLINE("CMP	AX,BX");
	ASM_INLINE("JZ	_82EE8");
	ASM_INLINE("MOV	AX,0xFFFF");
	ASM_INLINE("JMP	_82EEA");
ASM_INLINE("_82EE8:");
	ASM_INLINE("XOR	AX,AX");
ASM_INLINE("_82EEA:");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
}

void serial_out()
{
	serial_out_sub; //Force include
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	CX,AX");
	ASM_INLINE("MOV	DX,BX");
	ASM_INLINE("INC	[0x100C].W");
	ASM_INLINE("CMP	[0x020C].B,0x00");
	ASM_INLINE("JNZ	_82F10");
	ASM_INLINE("CALL	unk_82FFF_");
	ASM_INLINE("CMP	[0x020C].B,0x00");
	ASM_INLINE("JNZ	_82F10");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("JMP	_82F86");
ASM_INLINE("_82F10:");
	ASM_INLINE("MOV	[0x0E8C].B,0xFE");
	ASM_INLINE("MOV	[0x0E8E].B,0x7E");
	ASM_INLINE("MOV	[0x0E90].B,0x00");
	ASM_INLINE("XOR	SI,SI");
	ASM_INLINE("JMP	_82F36");
ASM_INLINE("_82F23:");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("ADD	BX,SI");
	ASM_INLINE("MOV	AL,[0x0E8C].B");
	ASM_INLINE("CMP	AL,[BX].B");
	ASM_INLINE("JNZ	_82F35");
	ASM_INLINE("DEC	[0x0E8C].B");
	ASM_INLINE("MOV	SI,0xFFFF");
ASM_INLINE("_82F35:");
	ASM_INLINE("INC	SI");
ASM_INLINE("_82F36:");
	ASM_INLINE("CMP	SI,DX");
	ASM_INLINE("JL	_82F23");
	ASM_INLINE("XOR	SI,SI");
	ASM_INLINE("JMP	_82F51");
ASM_INLINE("_82F3E:");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("ADD	BX,SI");
	ASM_INLINE("MOV	AL,[0x0E8E].B");
	ASM_INLINE("CMP	AL,[BX].B");
	ASM_INLINE("JNZ	_82F50");
	ASM_INLINE("DEC	[0x0E8E].B");
	ASM_INLINE("MOV	SI,0xFFFF");
ASM_INLINE("_82F50:");
	ASM_INLINE("INC	SI");
ASM_INLINE("_82F51:");
	ASM_INLINE("CMP	SI,DX");
	ASM_INLINE("JL	_82F3E");
	ASM_INLINE("XOR	SI,SI");
	ASM_INLINE("JMP	_82F64");
ASM_INLINE("_82F59:");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("ADD	BX,SI");
	ASM_INLINE("MOV	AL,[BX].B");
	ASM_INLINE("ADD	[0x0E90].B,AL");
	ASM_INLINE("INC	SI");
ASM_INLINE("_82F64:");
	ASM_INLINE("CMP	SI,DX");
	ASM_INLINE("JL	_82F59");
	ASM_INLINE("XOR	SI,SI");
	ASM_INLINE("JMP	_82F7F");
ASM_INLINE("_82F6C:");
	ASM_INLINE("PUSHF");
	ASM_INLINE("CLI");
	ASM_INLINE("MOV	AX,CX");
	ASM_INLINE("MOV	BX,DX");
	ASM_INLINE("CALLF	serial_out_sub_, SEG serial_out_sub_");
	ASM_INLINE("MOV	DI,AX");
	ASM_INLINE("POPF");
	ASM_INLINE("TEST	DI,DI");
	ASM_INLINE("JZ	_82F84");
	ASM_INLINE("INC	SI");
ASM_INLINE("_82F7F:");
	ASM_INLINE("CMP	SI,0x000A");
	ASM_INLINE("JL	_82F6C");
ASM_INLINE("_82F84:");
	ASM_INLINE("MOV	AX,DI");
ASM_INLINE("_82F86:");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
}

static s16 near unk_82F8B(u8 a)
{
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("MOV	DL,AL");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("JMP	_82FA6");
ASM_INLINE("_82F93:");
	ASM_INLINE("IN	AL,0xB3");
	ASM_INLINE("TEST	AL,0x04");
	ASM_INLINE("JZ	_82FA1");
	ASM_INLINE("MOV	AL,DL");
	ASM_INLINE("OUT	0xB1,AL");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("JMP	_82FAF");
ASM_INLINE("_82FA1:");
	ASM_INLINE("JMP	_82FA3");
ASM_INLINE("_82FA3:");
	ASM_INLINE("JMP	_82FA5");
ASM_INLINE("_82FA5:");
	ASM_INLINE("INC	CX");
ASM_INLINE("_82FA6:");
	ASM_INLINE("CMP	CX,0x0080");
	ASM_INLINE("JL	_82F93");
	ASM_INLINE("MOV	AX,0xFFFF");
ASM_INLINE("_82FAF:");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
}

static s16 near unk_82FB2()
{
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("JMP	_82FC8");
ASM_INLINE("_82FB7:");
	ASM_INLINE("IN	AL,0xB3");
	ASM_INLINE("TEST	AL,0x01");
	ASM_INLINE("JZ	_82FC3");
	ASM_INLINE("IN	AL,0xB1");
	ASM_INLINE("XOR	AH,AH");
	ASM_INLINE("JMP	_82FD1");
ASM_INLINE("_82FC3:");
	ASM_INLINE("JMP	_82FC5");
ASM_INLINE("_82FC5:");
	ASM_INLINE("JMP	_82FC7");
ASM_INLINE("_82FC7:");
	ASM_INLINE("INC	CX");
ASM_INLINE("_82FC8:");
	ASM_INLINE("CMP	CX,0x0080");
	ASM_INLINE("JL	_82FB7");
	ASM_INLINE("MOV	AX,0xFFFF");
ASM_INLINE("_82FD1:");
	ASM_INLINE("POP	CX");
}

static void near unk_82FD3()
{
	ASM_INLINE("CALL	unk_82FB2_");
	ASM_INLINE("CMP	AX,0xFFFF");
	ASM_INLINE("JZ	_82FF2");
	ASM_INLINE("CMP	AX,0x005A");
	ASM_INLINE("JZ	_82FEE");
	ASM_INLINE("CMP	AX,0x00A5");
	ASM_INLINE("JNZ	_82FFB");
	ASM_INLINE("MOV	[0x020C].B,0x01");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("RET");
ASM_INLINE("_82FEE:");
	ASM_INLINE("MOV	AX,0x0002");
	ASM_INLINE("RET");
ASM_INLINE("_82FF2:");
	ASM_INLINE("MOV	[0x020C].B,0x00");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("RET");
ASM_INLINE("_82FFB:");
	ASM_INLINE("MOV	AX,0x0003");
}

static void near unk_82FFF()
{
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSHF");
	ASM_INLINE("CLI");
	ASM_INLINE("MOV	AL,0x5A");
	ASM_INLINE("CALL	unk_82F8B_");
	ASM_INLINE("CMP	AX,0x0000");
	ASM_INLINE("JGE	_83014");
	ASM_INLINE("MOV	[0x020C].B,0x00");
	ASM_INLINE("JMP	_83094");
ASM_INLINE("_83014:");
	ASM_INLINE("CALL	unk_82FD3_");
	ASM_INLINE("CMP	AX,0x0003");
	ASM_INLINE("JZ	_83076");
	ASM_INLINE("CMP	AX,0x0002");
	ASM_INLINE("JZ	_83028");
	ASM_INLINE("CMP	AX,0x0001");
	ASM_INLINE("JZ	_83094");
	ASM_INLINE("JMP	_83094");
ASM_INLINE("_83028:");
	ASM_INLINE("CMP	[0x020C].B,0x01");
	ASM_INLINE("JNZ	_83034");
	ASM_INLINE("MOV	CX,0x00FF");
	ASM_INLINE("JMP	_83039");
ASM_INLINE("_83034:");
	ASM_INLINE("CALL	unk_830B1_");
	ASM_INLINE("MOV	CX,AX");
ASM_INLINE("_83039:");
	ASM_INLINE("MOV	AL,CL");
	ASM_INLINE("CALL	unk_82F8B_");
	ASM_INLINE("CMP	AX,0x0000");
	ASM_INLINE("JGE	_8304A");
	ASM_INLINE("MOV	[0x020C].B,0x00");
	ASM_INLINE("JMP	_83094");
ASM_INLINE("_8304A:");
	ASM_INLINE("CALL	unk_82FB2_");
	ASM_INLINE("CMP	AX,0x0000");
	ASM_INLINE("JGE	_83059");
	ASM_INLINE("MOV	[0x020C].B,0x00");
	ASM_INLINE("JMP	_83094");
ASM_INLINE("_83059:");
	ASM_INLINE("CMP	AX,CX");
	ASM_INLINE("JNZ	_83064");
	ASM_INLINE("MOV	[0x020C].B,0x00");
	ASM_INLINE("JMP	_83094");
ASM_INLINE("_83064:");
	ASM_INLINE("CMP	CX,AX");
	ASM_INLINE("JGE	_8306F");
	ASM_INLINE("MOV	[0x020C].B,0x02");
	ASM_INLINE("JMP	_83094");
ASM_INLINE("_8306F:");
	ASM_INLINE("MOV	[0x020C].B,0x01");
	ASM_INLINE("JMP	_83094");
ASM_INLINE("_83076:");
	ASM_INLINE("MOV	AL,0x5A");
	ASM_INLINE("CALL	unk_82F8B_");
	ASM_INLINE("CMP	AX,0x0000");
	ASM_INLINE("JGE	_83087");
	ASM_INLINE("MOV	[0x020C].B,0x00");
	ASM_INLINE("JMP	_83094");
ASM_INLINE("_83087:");
	ASM_INLINE("CALL	unk_82FD3_");
	ASM_INLINE("CMP	AX,0x0001");
	ASM_INLINE("JZ	_83094");
	ASM_INLINE("MOV	[0x020C].B,0x00");
ASM_INLINE("_83094:");
	ASM_INLINE("POPF");
	ASM_INLINE("POP	CX");
}

static void near unk_83097()
{
	if(unk_82F8B(0xA5) < 0)
	{
		com_user = 0;
	}
	else
	{
		com_user = 2;
	}
}

u16 serial_ver_info()
{
	return 0x36; /*54*/
}

static void near unk_830B1()
{
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("MOV	AX,[com_unk_].W");
	ASM_INLINE("MOV	BX,[com_unk2_].W");
	ASM_INLINE("MOV	CX,0x4E6D");
	ASM_INLINE("MOV	DX,0x41C6");
	ASM_INLINE("CALLF	0x000E, 0x9211"); //_LMUL
	ASM_INLINE("ADD	AX,0x3039");
	ASM_INLINE("ADC	BX,0x0000");
	ASM_INLINE("MOV	[com_unk_].W,AX");
	ASM_INLINE("MOV	[com_unk2_].W,BX");
	ASM_INLINE("MOV	AX,[com_unk_].W");
	ASM_INLINE("MOV	BX,[com_unk2_].W");
	ASM_INLINE("MOV	CX,0x0010");
	//ASM_INLINE("JCXZ	_830E4");
	ASM_OP2(0xE3,0x06);
ASM_INLINE("_830DE:");
	ASM_INLINE("SAR	BX,1");
	ASM_INLINE("RCR	AX,1");
	ASM_INLINE("LOOP	_830DE");
ASM_INLINE("_830E4:");
	ASM_INLINE("AND	AX,0x7FFF");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
}

u16 serial_exist()
{
	unk_830B1();
}

s16 serial_in_frag()
{
	return rcv_work.unk8;
}

