#include <machine.h>
#include "types.h"
#include "TITLE.h"
#include "SWAN_L_C.h"
#include "SWANMAIN.h"
#include "SYSTEM.h"
#include "SPRINTF.h"
#include "MEMORY.h"
#include "SOUND_CODE.h"

static char str0[] = "               ";
static char str1[] = "VERSION 000105D";
static char str2[] = "FREE PLAY      ";
static char str3[] = "ALL SAVE CLEAR!";
static char str4[] = "UNDEFINED!!    ";
static char str5[] = "               ";
static char str6[] = "TYPE 0         ";
static char str7[] = "No Suppoted    ";
static char str8[] = "--CLEAR--      ";

static const u8 far title_unk[] = {0,1,2,3,2,1};

extern u8 far G_TITLE_char_adr[];

static void unk_83CEA(u16 a)
{
	a = title_unk[a];
	font_putXY(0, 18 + a, 12, 1, 8, 14, 1, G_TITLE_char_adr);
}

static void unk_83D28(u16 a, u16 b, u8 *c)
{
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	SI,AX");
	ASM_INLINE("MOV	DI,BX");
	ASM_INLINE("JMP	_83DA6");
ASM_INLINE("_83D32:");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	BX,0x0000");
	ASM_INLINE("MOV	AX,0xB7E4");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("MOV	AL,[BX].B");
	ASM_INLINE("AND	AL,0x0F");
	ASM_INLINE("XOR	AH,AH");
	ASM_INLINE("ADD	AX,0x000C");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("MOV	BL,[BX].B");
	ASM_INLINE("XOR	BH,BH");
	ASM_INLINE("SAR	BX,1");
	ASM_INLINE("SAR	BX,1");
	ASM_INLINE("SAR	BX,1");
	ASM_INLINE("SAR	BX,1");
	ASM_INLINE("ADD	BX,0x0010");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALLF	font_putXY_, SEG font_putXY_");
	ASM_INLINE("ADD	SP,0x000A");
	ASM_INLINE("POP	CX");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("CMP	[BX].B,0x20");
	ASM_INLINE("JNZ	_83DA3");
	ASM_INLINE("MOV	AX,SI");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("MOV	AX,SI");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("MOV	CX,0x0000");
	ASM_INLINE("MOV	DX,0xB7E4");
	ASM_INLINE("CALLF	get_bmp_cell_no_, SEG get_bmp_cell_no_");
	ASM_INLINE("MOV	DX,AX");
	ASM_INLINE("POP	CX");
	ASM_INLINE("POP	BX");
	ASM_INLINE("POP	AX");
	ASM_INLINE("CALLF	put_cell_no_, SEG put_cell_no_");
ASM_INLINE("_83DA3:");
	ASM_INLINE("INC	SI");
	ASM_INLINE("POP	CX");
	ASM_INLINE("INC	CX");
ASM_INLINE("_83DA6:");
	ASM_INLINE("MOV	BX,CX");
	ASM_INLINE("CMP	[BX].B,0x00");
	ASM_INLINE("JNZ	_83D32");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
}

static void unk_83DB2()
{
	unk_83D28(0, 0, (u8*)str0);
}

static void unk_83DC1()
{
	unk_83D28(0, 0, (u8*)str1);
}

static void unk_83DD0()
{
	unk_83D28(0, 0, (u8*)str2);
}

static void unk_83DDF()
{
	unk_83D28(0, 0, (u8*)str3);
}

static void unk_83DEE()
{
	unk_83D28(0, 0, (u8*)str4);
}

static void unk_83DFD()
{
	unk_83D28(0, 0, (u8*)str5);
}

static void unk_83E0C()
{
	unk_83D28(0, 0, (u8*)str6);
}

static void unk_83E1B()
{
	unk_83D28(0, 0, (u8*)str7);
}

static void unk_83E2A()
{
	unk_83D28(0, 0, (u8*)str8);
	flash_clear();
}

static void unk_83E3E()
{
}

void title_init()
{
	task_delete; //Force include
	memalloc; //Force include
	task_append; //Force include
	nbg_ddf; //Force include
	spr_ddf; //Force include
	font_load; //Force include
	get_bmp_cell_no; //Force include
	put_cell_no; //Force include
	font_putXYT; //Force include
	put_sprite; //Force include
	fade_tone; //Force include
	fade_out; //Force include
	fade_run; //Force include
	fade_in; //Force include
	bgmreq; //Force include
	ASM_INLINE("PUSH	BP");
	ASM_INLINE("MOV	BP,SP");
	ASM_INLINE("SUB	SP,0x0002");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	DX,AX");
	ASM_INLINE("CALLF	task_delete_, SEG task_delete_");
	ASM_INLINE("MOV	AX,0x001D");
	ASM_INLINE("CALLF	memalloc_, SEG memalloc_");
	ASM_INLINE("MOV	SI,AX");
	ASM_INLINE("TEST	SI,SI");
	ASM_INLINE("JNZ	_83E61");
	ASM_INLINE("JMP	_84039");
ASM_INLINE("_83E61:");
	ASM_INLINE("MOV	AX,unk_84041_");
	ASM_INLINE("MOV	BX,SEG unk_84041_");
	ASM_INLINE("MOV	CX,SI");
	ASM_INLINE("CALLF	task_append_, SEG task_append_");
	ASM_INLINE("MOV	[SI].W,DX");
	ASM_INLINE("MOV	[SI+0x02].W,0x0000");
	ASM_INLINE("MOV	[SI+0x04].W,0x0000");
	ASM_INLINE("MOV	[SI+0x06].B,0x00");
	ASM_INLINE("MOV	[SI+0x07].W,0x0000");
	ASM_INLINE("MOV	[SI+0x09].W,0x0000");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("JMP	_83E9C");
ASM_INLINE("_83E8C:");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("ADD	BX,0x000B");
	ASM_INLINE("MOV	AX,CX");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("ADD	BX,AX");
	ASM_INLINE("MOV	[BX].W,0x0000");
	ASM_INLINE("INC	CX");
ASM_INLINE("_83E9C:");
	ASM_INLINE("CMP	CX,0x0008");
	ASM_INLINE("JL	_83E8C");
	ASM_INLINE("MOV	[SI+0x1B].W,0x0000");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("CALLF	nbg_ddf_, SEG nbg_ddf_");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("CALLF	nbg_ddf_, SEG nbg_ddf_");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("CALLF	spr_ddf_, SEG spr_ddf_");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("MOV	CX,0x0000");
	ASM_INLINE("MOV	DX,0xB7E4");
	ASM_INLINE("CALLF	font_load_, SEG font_load_");
	ASM_INLINE("MOV	AX,0x001B");
	ASM_INLINE("MOV	BX,0x0021");
	ASM_INLINE("MOV	CX,0x0000");
	ASM_INLINE("MOV	DX,0xB7E4");
	ASM_INLINE("CALLF	get_bmp_cell_no_, SEG get_bmp_cell_no_");
	ASM_INLINE("MOV	DX,AX");
	ASM_INLINE("OR	DX,0x0800");
	ASM_INLINE("XOR	SI,SI");
	ASM_INLINE("JMP	_83F10");
ASM_INLINE("_83EE9:");
	ASM_INLINE("XOR	DI,DI");
	ASM_INLINE("JMP	_83F07");
ASM_INLINE("_83EED:");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("CALLF	put_cell_no_, SEG put_cell_no_");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("CALLF	put_cell_no_, SEG put_cell_no_");
	ASM_INLINE("ADD	DI,0x0008");
ASM_INLINE("_83F07:");
	ASM_INLINE("CMP	DI,0x0100");
	ASM_INLINE("JL	_83EED");
	ASM_INLINE("ADD	SI,0x0008");
ASM_INLINE("_83F10:");
	ASM_INLINE("CMP	SI,0x0100");
	ASM_INLINE("JL	_83EE9");
	ASM_INLINE("XOR	SI,SI");
	ASM_INLINE("JMP	_83F40");
ASM_INLINE("_83F1A:");
	ASM_INLINE("MOV	BX,0x0000");
	ASM_INLINE("MOV	AX,0xB7E4");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,SI");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("MOV	CX,0x0005");
	ASM_INLINE("MOV	DX,0x0002");
	ASM_INLINE("CALLF	font_putXY_, SEG font_putXY_");
	ASM_INLINE("ADD	SP,0x000A");
	ASM_INLINE("INC	SI");
ASM_INLINE("_83F40:");
	ASM_INLINE("CMP	SI,0x0010");
	ASM_INLINE("JL	_83F1A");
	ASM_INLINE("MOV	BX,0x0000");
	ASM_INLINE("MOV	AX,0xB7E4");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x0005");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x0005");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("MOV	CX,0x0017");
	ASM_INLINE("MOV	DX,0x0012");
	ASM_INLINE("CALLF	font_putXY_, SEG font_putXY_");
	ASM_INLINE("ADD	SP,0x000A");
	ASM_INLINE("MOV	BX,0x0000");
	ASM_INLINE("MOV	AX,0xB7E4");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x0E00");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x0002");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("MOV	BX,0x0016");
	ASM_INLINE("MOV	CX,0x0005");
	ASM_INLINE("MOV	DX,0x0009");
	ASM_INLINE("CALLF	font_putXYT_, SEG font_putXYT_");
	ASM_INLINE("ADD	SP,0x000C");
	ASM_INLINE("MOV	[BP-0x02].W,0x0000");
	ASM_INLINE("XOR	SI,SI");
	ASM_INLINE("JMP	_83FED");
ASM_INLINE("_83F9E:");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("JMP	_83FE7");
ASM_INLINE("_83FA2:");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,0x0005");
	ASM_INLINE("ADD	AX,BX");
	ASM_INLINE("MOV	BX,0x0016");
	ASM_INLINE("ADD	BX,SI");
	ASM_INLINE("MOV	CX,0x0000");
	ASM_INLINE("MOV	DX,0xB7E4");
	ASM_INLINE("CALLF	get_bmp_cell_no_, SEG get_bmp_cell_no_");
	ASM_INLINE("MOV	DI,AX");
	ASM_INLINE("MOV	AX,0x0004");
	ASM_INLINE("POP	BX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("INC	[BP-0x02].W");
	ASM_INLINE("MOV	AX,[BP-0x02].W");
	ASM_INLINE("DEC	AX");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("MOV	CX,SI");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("SHL	CX,1");
	ASM_INLINE("ADD	CX,0x0010");
	ASM_INLINE("MOV	DX,0x2000");
	ASM_INLINE("OR	DX,DI");
	ASM_INLINE("CALLF	put_sprite_, SEG put_sprite_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("POP	BX");
	ASM_INLINE("INC	BX");
ASM_INLINE("_83FE7:");
	ASM_INLINE("CMP	BX,0x0005");
	ASM_INLINE("JL	_83FA2");
	ASM_INLINE("INC	SI");
ASM_INLINE("_83FED:");
	ASM_INLINE("CMP	SI,0x0009");
	ASM_INLINE("JL	_83F9E");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("CALLF	unk_83CEA_, SEG unk_83CEA_");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("CALLF	fade_tone_, SEG fade_tone_");
	ASM_INLINE("MOV	AX,0x0064");
	ASM_INLINE("CALLF	fade_out_, SEG fade_out_");
	ASM_INLINE("CALLF	fade_run_, SEG fade_run_");
	ASM_INLINE("MOV	AX,0x000A");
	ASM_INLINE("CALLF	fade_in_, SEG fade_in_");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("MOV	BX,0x0001");
	ASM_INLINE("CALLF	nbg_ddf_, SEG nbg_ddf_");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("MOV	BX,0x0001");
	ASM_INLINE("CALLF	nbg_ddf_, SEG nbg_ddf_");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("CALLF	spr_ddf_, SEG spr_ddf_");
	ASM_INLINE("MOV	AL,0x01");
	ASM_INLINE("CALLF	bgmreq_, SEG bgmreq_");
ASM_INLINE("_84039:");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
	ASM_INLINE("MOV	SP,BP");
	ASM_INLINE("POP	BP");
}

static void unk_84041()
{
	sereq; //Force include
	memfree; //Force include
	task_delete_fade; //Force include
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("MOV	SI,AX");
	ASM_INLINE("TEST	[0x0956].W,0x0800");
	ASM_INLINE("JZ	_840A6");
	ASM_INLINE("CMP	[SI+0x07].W,0x0000");
	ASM_INLINE("JZ	_840A6");
	ASM_INLINE("MOV	AL,0x12");
	ASM_INLINE("CALLF	sereq_, SEG sereq_");
	ASM_INLINE("MOV	AX,[SI+0x1B].W");
	ASM_INLINE("SUB	AX,0xFFFC");
	ASM_INLINE("MOV	BX,0x0005");
	ASM_INLINE("CWD");
	ASM_INLINE("IDIV	BX");
	ASM_INLINE("MOV	[SI+0x1B].W,DX");
	ASM_INLINE("MOV	AX,[SI+0x1B].W");
	ASM_INLINE("CMP	AX,0x0004");
	ASM_INLINE("JZ	_840A1");
	ASM_INLINE("CMP	AX,0x0003");
	ASM_INLINE("JZ	_8409A");
	ASM_INLINE("CMP	AX,0x0002");
	ASM_INLINE("JZ	_84093");
	ASM_INLINE("CMP	AX,0x0001");
	ASM_INLINE("JZ	_8408C");
	ASM_INLINE("TEST	AX,AX");
	ASM_INLINE("JNZ	_840A6");
	ASM_INLINE("CALLF	unk_83DB2_, SEG unk_83DB2_");
	ASM_INLINE("JMP	_840A6");
ASM_INLINE("_8408C:");
	ASM_INLINE("CALLF	unk_83DC1_, SEG unk_83DC1_");
	ASM_INLINE("JMP	_840A6");
ASM_INLINE("_84093:");
	ASM_INLINE("CALLF	unk_83DD0_, SEG unk_83DD0_");
	ASM_INLINE("JMP	_840A6");
ASM_INLINE("_8409A:");
	ASM_INLINE("CALLF	unk_83DDF_, SEG unk_83DDF_");
	ASM_INLINE("JMP	_840A6");
ASM_INLINE("_840A1:");
	ASM_INLINE("CALLF	unk_83DEE_, SEG unk_83DEE_");
ASM_INLINE("_840A6:");
	ASM_INLINE("TEST	[0x0956].W,0x0200");
	ASM_INLINE("JZ	_84106");
	ASM_INLINE("CMP	[SI+0x07].W,0x0000");
	ASM_INLINE("JZ	_84106");
	ASM_INLINE("MOV	AL,0x12");
	ASM_INLINE("CALLF	sereq_, SEG sereq_");
	ASM_INLINE("MOV	AX,[SI+0x1B].W");
	ASM_INLINE("ADD	AX,0x0006");
	ASM_INLINE("MOV	BX,0x0005");
	ASM_INLINE("CWD");
	ASM_INLINE("IDIV	BX");
	ASM_INLINE("MOV	[SI+0x1B].W,DX");
	ASM_INLINE("MOV	AX,[SI+0x1B].W");
	ASM_INLINE("CMP	AX,0x0004");
	ASM_INLINE("JZ	_84101");
	ASM_INLINE("CMP	AX,0x0003");
	ASM_INLINE("JZ	_840FA");
	ASM_INLINE("CMP	AX,0x0002");
	ASM_INLINE("JZ	_840F3");
	ASM_INLINE("CMP	AX,0x0001");
	ASM_INLINE("JZ	_840EC");
	ASM_INLINE("TEST	AX,AX");
	ASM_INLINE("JNZ	_84106");
	ASM_INLINE("CALLF	unk_83DB2_, SEG unk_83DB2_");
	ASM_INLINE("JMP	_84106");
ASM_INLINE("_840EC:");
	ASM_INLINE("CALLF	unk_83DC1_, SEG unk_83DC1_");
	ASM_INLINE("JMP	_84106");
ASM_INLINE("_840F3:");
	ASM_INLINE("CALLF	unk_83DD0_, SEG unk_83DD0_");
	ASM_INLINE("JMP	_84106");
ASM_INLINE("_840FA:");
	ASM_INLINE("CALLF	unk_83DDF_, SEG unk_83DDF_");
	ASM_INLINE("JMP	_84106");
ASM_INLINE("_84101:");
	ASM_INLINE("CALLF	unk_83DEE_, SEG unk_83DEE_");
ASM_INLINE("_84106:");
	ASM_INLINE("TEST	[0x0956].W,0x0004");
	ASM_INLINE("JZ	_84157");
	ASM_INLINE("CMP	[SI+0x07].W,0x0000");
	ASM_INLINE("JZ	_84157");
	ASM_INLINE("MOV	AL,0x10");
	ASM_INLINE("CALLF	sereq_, SEG sereq_");
	ASM_INLINE("MOV	AX,[SI+0x1B].W");
	ASM_INLINE("CMP	AX,0x0004");
	ASM_INLINE("JZ	_84152");
	ASM_INLINE("CMP	AX,0x0003");
	ASM_INLINE("JZ	_8414B");
	ASM_INLINE("CMP	AX,0x0002");
	ASM_INLINE("JZ	_84144");
	ASM_INLINE("CMP	AX,0x0001");
	ASM_INLINE("JZ	_8413D");
	ASM_INLINE("TEST	AX,AX");
	ASM_INLINE("JNZ	_84157");
	ASM_INLINE("CALLF	unk_83DFD_, SEG unk_83DFD_");
	ASM_INLINE("JMP	_84157");
ASM_INLINE("_8413D:");
	ASM_INLINE("CALLF	unk_83E0C_, SEG unk_83E0C_");
	ASM_INLINE("JMP	_84157");
ASM_INLINE("_84144:");
	ASM_INLINE("CALLF	unk_83E1B_, SEG unk_83E1B_");
	ASM_INLINE("JMP	_84157");
ASM_INLINE("_8414B:");
	ASM_INLINE("CALLF	unk_83E2A_, SEG unk_83E2A_");
	ASM_INLINE("JMP	_84157");
ASM_INLINE("_84152:");
	ASM_INLINE("CALLF	unk_83E3E_, SEG unk_83E3E_");
ASM_INLINE("_84157:");
	ASM_INLINE("CMP	[0x0956].W,0x0000");
	ASM_INLINE("JNZ	_84161");
	ASM_INLINE("JMP	_8421B");
ASM_INLINE("_84161:");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("ADD	BX,0x000B");
	ASM_INLINE("MOV	AX,[SI+0x09].W");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("ADD	BX,AX");
	ASM_INLINE("MOV	AX,[0x0956].W");
	ASM_INLINE("MOV	[BX].W,AX");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("MOV	AX,[BX+0x09].W");
	ASM_INLINE("INC	AX");
	ASM_INLINE("AND	AX,0x0007");
	ASM_INLINE("MOV	[SI+0x09].W,AX");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("ADD	BX,0x000B");
	ASM_INLINE("MOV	AX,[SI+0x09].W");
	ASM_INLINE("DEC	AX");
	ASM_INLINE("AND	AX,0x0007");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("ADD	BX,AX");
	ASM_INLINE("TEST	[BX].W,0x0200");
	ASM_INLINE("JNZ	_84197");
	ASM_INLINE("JMP	_8421B");
ASM_INLINE("_84197:");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("ADD	BX,0x000B");
	ASM_INLINE("MOV	AX,[SI+0x09].W");
	ASM_INLINE("SUB	AX,0x0002");
	ASM_INLINE("AND	AX,0x0007");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("ADD	BX,AX");
	ASM_INLINE("TEST	[BX].W,0x0800");
	ASM_INLINE("JZ	_8421B");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("ADD	BX,0x000B");
	ASM_INLINE("MOV	AX,[SI+0x09].W");
	ASM_INLINE("SUB	AX,0x0003");
	ASM_INLINE("AND	AX,0x0007");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("ADD	BX,AX");
	ASM_INLINE("TEST	[BX].W,0x0400");
	ASM_INLINE("JZ	_8421B");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("ADD	BX,0x000B");
	ASM_INLINE("MOV	AX,[SI+0x09].W");
	ASM_INLINE("SUB	AX,0x0004");
	ASM_INLINE("AND	AX,0x0007");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("ADD	BX,AX");
	ASM_INLINE("TEST	[BX].W,0x0400");
	ASM_INLINE("JZ	_8421B");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("ADD	BX,0x000B");
	ASM_INLINE("MOV	AX,[SI+0x09].W");
	ASM_INLINE("SUB	AX,0x0005");
	ASM_INLINE("AND	AX,0x0007");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("ADD	BX,AX");
	ASM_INLINE("TEST	[BX].W,0x0400");
	ASM_INLINE("JZ	_8421B");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("ADD	BX,0x000B");
	ASM_INLINE("MOV	AX,[SI+0x09].W");
	ASM_INLINE("SUB	AX,0x0006");
	ASM_INLINE("AND	AX,0x0007");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("ADD	BX,AX");
	ASM_INLINE("TEST	[BX].W,0x0100");
	ASM_INLINE("JZ	_8421B");
	ASM_INLINE("MOV	[SI+0x07].W,0x0001");
	ASM_INLINE("MOV	AL,0x10");
	ASM_INLINE("CALLF	sereq_, SEG sereq_");
ASM_INLINE("_8421B:");
	ASM_INLINE("TEST	[0x0956].W,0x0002");
	ASM_INLINE("JZ	_8423E");
	ASM_INLINE("MOV	AL,0x0A");
	ASM_INLINE("CALLF	sereq_, SEG sereq_");
	ASM_INLINE("MOV	AX,SI");
	ASM_INLINE("CALLF	memfree_, SEG memfree_");
	ASM_INLINE("CALLF	task_delete_, SEG task_delete_");
	ASM_INLINE("MOV	AX,0x000A");
	ASM_INLINE("CALLF	task_delete_fade_, SEG task_delete_fade_");
ASM_INLINE("_8423E:");
	ASM_INLINE("INC	[SI+0x04].W");
	ASM_INLINE("CMP	[SI+0x04].W,0x0003");
	ASM_INLINE("JLE	_84261");
	ASM_INLINE("MOV	[SI+0x04].W,0x0000");
	ASM_INLINE("MOV	AX,[SI+0x02].W");
	ASM_INLINE("INC	AX");
	ASM_INLINE("MOV	BX,0x0006");
	ASM_INLINE("CWD");
	ASM_INLINE("IDIV	BX");
	ASM_INLINE("MOV	[SI+0x02].W,DX");
	ASM_INLINE("MOV	AX,[SI+0x02].W");
	ASM_INLINE("CALLF	unk_83CEA_, SEG unk_83CEA_");
ASM_INLINE("_84261:");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("INC	[SI+0x06].B");
	ASM_INLINE("MOV	CL,[SI+0x06].B");
	ASM_INLINE("XOR	CH,CH");
	ASM_INLINE("CALLF	0x0072, 0x80EB");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
}







 