#include <machine.h>
#include "types.h"
#include "unisel.h"
#include "tuneup.h"
#include "SWAN_L_C.h"
#include "SWANMAIN.h"
#include "SPRINTF.h"
#include "SYSTEM.h"
#include "SOUND_CODE.h"
#include "PUT_TEXT.h"
#include "MEMORY.h"
#include "PAD.h"
#include "story.h"
#include "m_cpu2p.h"
#include "m_game.h"
#include "stagesel.h"
#include "flash.h"
#include "IP_MES.h"
#include "menu.h"

static char str0[] = "%02d"; /*070A*/
static char str1[] = "%02d"; /*0710*/
static char str2[] = "%02d"; /*0716*/
static char str3[] = "%02d"; /*071C*/
static char str4[] = "--"; /*0722*/
static char str5[] = "%02d"; /*0726*/
static char str6[] = "%02d"; /*072C*/
static char str7[] = "%02d"; /*0732*/
static char str8[] = "--"; /*0738*/

/*B9C3:0000*/ static const char far unisel00[] = " AU-NAME HP EN TP";
/*B9C4:0002*/ static const char far unisel01[] = " No File -- -- --";
/*B9C5:0004*/ static const char far unisel02[] = "  PLAY   DELETE  ";
/*B9C6:0006*/ static const char far unisel03[] = "TYPE";
/*B9C6:000C*/ static const char far unisel04[] = "NAME";
/*B9C7:0002*/ static const char far unisel05[] = "STAGE";
/*B9C7:0008*/ static const char far unisel06[] = "HP";
/*B9C7:000C*/ static const char far unisel07[] = "ENG";
/*B9C8:0000*/ static const char far unisel08[] = "TP";
/*B9C8:0004*/ static const char far unisel09[] = "PLAYER    ";
/*B9C9:0000*/ static const char far unisel10[] = "       CPU";
/*B9C9:000C*/ static const char far unisel11[] = "PLAYER/CPU";
/*B9CA:0008*/ static const char far unisel12[] = "SAVE FILE%1d";
/*B9CB:0006*/ static const char far unisel13[] = "NEW GAME  ";
/*B9CC:0002*/ static const char far unisel14[] = "          ";

/*B9CC:000E*/
static const char far * far unisel[] =
{
    unisel09,
    unisel09,
    unisel10,
    unisel11,
    unisel12,
    unisel13,
    unisel14,
};

static void unk_8C874(struct UniselWork *work);

static void near unk_8B5EC()
{
	s16 i;
	s16 j;
	u8 *ptr;

	for (i = 1; i < 9; i++)
	{
		ptr = (i * 0x1d + (SAVE_DATA_START + 0x3C) + 0x0D);
		for (j = 0; j < 16; j++,ptr++)
		{
			if (4 < *ptr)
			{
				*ptr = 4;
			}
		}

		ptr = (i * 0x1d + (SAVE_DATA_START + 0x3C));
		if(ptr[0x1C])
		{
			ptr = (i * 0x1d + (SAVE_DATA_START + 0x3C) + 0x0D);
			for (j = 0; j < 16; j++)
			{
				*ptr = 0;
				ptr++;
			}
			*(i * 0x1d + (SAVE_DATA_START + 0x3C) + 1) = *(i * 0x1d + (SAVE_DATA_START + 0x3C) + 1) ? 0 : 1;
		}
	}
}

static s16 near unk_8B67E(u16 val)
{
	s16 i;

	for(i = 1; i < 9; i++)
	{
		if(*(SAVE_DATA_START + 0x3C + (i * 0x1d)) == val)
		{
			return i;
		}
	}
	return 0;
}

static s16 near unk_8B6AB()
{
	s16 i;

	for(i = 1; i < 9; i++)
	{
		if(*(SAVE_DATA_START + 0x3C + (i * 0x1d)) == -1)
		{
			return i;
		}
	}
	return 0;
}

static u16 near unk_8B6D1()
{
	return 9;
}

static void near unk_8B6D5(s16 a, s16 b, s16 c, s16 d)
{
	s16 i = 0;
	s16 j = 0;

	font_put2XY(0, 0x12, 1, 1, a + i, b + j, 1, G_UNISE2_char_adr);

	for (i = 1; i < c - 1; i++)
	{
		font_put2XY(1, 0x12, 1, 1, a + i, b + j, 1, G_UNISE2_char_adr);
	}

	font_put2XY(2, 0x12, 1, 1, a + i, b + j, 1, G_UNISE2_char_adr);

	for (j = 1; j < d - 1; j++)
	{
		i = 0;
		font_put2XY(3, 0x12, 1, 1, a + i, b + j, 1, G_UNISE2_char_adr);

		for (i = 1; i < c - 1; i++)
		{
			font_put2XY(4, 0x12, 1, 1, a + i, b + j, 1, G_UNISE2_char_adr);
		}

		font_put2XY(5, 0x12, 1, 1, a + i, b + j, 1, G_UNISE2_char_adr);
	}

	i = 0;
	font_put2XY(6, 0x12, 1, 1, a + i, b + j, 1, G_UNISE2_char_adr);

	for (i = 1; i < c - 1; i++)
	{
		font_put2XY(7, 0x12, 1, 1, a + i, b + j, 1, G_UNISE2_char_adr);
	}

	font_put2XY(8, 0x12, 1, 1, a + i, b + j, 1, G_UNISE2_char_adr);
}

static void near unk_8B8D1(s16 a, s16 b, s16 c, s16 d)
{
	if (d)
	{
		font_put2XY(9, 0x12, 1, 1, a + 1, b + 2 + c, 1, G_UNISE2_char_adr);
	}
	else
	{
		font_put2XY(10, 0x12, 1, 1, a + 1, b + 2 + c, 1, G_UNISE2_char_adr);
	}
}

static void near unk_8B92E(s16 a, s16 b, s16 c, s16 d)
{
	if (d)
	{
		font_put2XY(9, 0x12, 1, 1, a + 2 + c * 7, b + 10, 1, G_UNISE2_char_adr);
	}
	else
	{
		font_put2XY(10, 0x12, 1, 1, a + 2 + c * 7, b + 10, 1, G_UNISE2_char_adr);
	}
}

static void near unk_8B99D()
{
	bmp_print; //Force include
	hsprintf; //Force include
	ASM_INLINE("PUSH	BP");
	ASM_INLINE("MOV	BP,SP");
	ASM_INLINE("SUB	SP,0x0024");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	SI,BX");
	ASM_INLINE("MOV	DI,0x1E59");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("LEA	DI,[BP-0x20].B");
	ASM_INLINE("MOV	[BP-0x24].W,0x0000");
	ASM_INLINE("MOV	[BP-0x22].W,0xB9C3");
ASM_INLINE("_8B9BB:");
	ASM_INLINE("INC	[BP-0x24].W");
	ASM_INLINE("LES	BX,[BP-0x24]");
	ASM_INLINE("DEC	BX");
	ASM_INLINE("MOV	BL,ES:[BX].B");
	ASM_INLINE("MOV	[DI].B,BL");
	ASM_INLINE("INC	DI");
	ASM_INLINE("TEST	BL,BL");
	ASM_INLINE("JNZ	_8B9BB");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("INC	AX");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("INC	BX");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("LEA	CX,[BP-0x20].B");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALLF	bmp_print_, SEG bmp_print_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("XOR	DX,DX");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	AX");
	ASM_INLINE("JMP	_8BB72");
ASM_INLINE("_8B9F4:");
	ASM_INLINE("CMP	[DI].B,0xFF");
	ASM_INLINE("JNZ	_8B9FC");
	ASM_INLINE("JMP	_8BB23");
ASM_INLINE("_8B9FC:");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("LEA	BX,[BP-0x20].B");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	CX,0xA78E");
	ASM_INLINE("MOV	ES,CX");
	ASM_INLINE("MOV	BL,[DI].B");
	ASM_INLINE("XOR	BH,BH");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	//ASM_INLINE("MOV	CX,ES:[BX+0x000A].W");
	ASM_OP5(0x26,0x8B,0x8F,0x0A,0x00);
	//ASM_INLINE("MOV	BX,ES:[BX+0x000C].W");
	ASM_OP5(0x26,0x8B,0x9F,0x0C,0x00);
	ASM_INLINE("MOV	[BP-0x24].W,CX");
	ASM_INLINE("MOV	[BP-0x22].W,BX");
	ASM_INLINE("POP	BX");
ASM_INLINE("_8BA20:");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("INC	[BP-0x24].W");
	ASM_INLINE("LES	BX,[BP-0x24]");
	ASM_INLINE("DEC	BX");
	ASM_INLINE("MOV	CL,ES:[BX].B");
	ASM_INLINE("POP	BX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	[BX].B,CL");
	ASM_INLINE("POP	BX");
	ASM_INLINE("INC	BX");
	ASM_INLINE("TEST	CL,CL");
	ASM_INLINE("JNZ	_8BA20");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("ADD	AX,0x0002");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("ADD	BX,0x0002");
	ASM_INLINE("ADD	BX,DX");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("LEA	CX,[BP-0x20].B");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALLF	bmp_print_, SEG bmp_print_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("MOV	BL,[DI+0x02].B");
	ASM_INLINE("XOR	BH,BH");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	BX,0x070A");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("LEA	BX,[BP-0x20].B");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("CALLF	hsprintf_, SEG hsprintf_");
	ASM_INLINE("ADD	SP,0x0006");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("POP	AX");
	ASM_INLINE("POP	DX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("ADD	AX,0x000A");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("ADD	BX,0x0002");
	ASM_INLINE("ADD	BX,DX");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("LEA	CX,[BP-0x20].B");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALLF	bmp_print_, SEG bmp_print_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("MOV	BL,[DI+0x03].B");
	ASM_INLINE("XOR	BH,BH");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	BX,0x0710");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("LEA	BX,[BP-0x20].B");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("CALLF	hsprintf_, SEG hsprintf_");
	ASM_INLINE("ADD	SP,0x0006");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("POP	AX");
	ASM_INLINE("POP	DX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("ADD	AX,0x000D");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("ADD	BX,0x0002");
	ASM_INLINE("ADD	BX,DX");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("LEA	CX,[BP-0x20].B");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALLF	bmp_print_, SEG bmp_print_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("MOV	BL,[DI+0x04].B");
	ASM_INLINE("XOR	BH,BH");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	BX,0x0716");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("LEA	BX,[BP-0x20].B");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("CALLF	hsprintf_, SEG hsprintf_");
	ASM_INLINE("ADD	SP,0x0006");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("POP	AX");
	ASM_INLINE("POP	DX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("ADD	AX,0x0010");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("ADD	BX,0x0002");
	ASM_INLINE("ADD	BX,DX");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("LEA	CX,[BP-0x20].B");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALLF	bmp_print_, SEG bmp_print_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("POP	AX");
	ASM_INLINE("POP	DX");
	ASM_INLINE("JMP	_8BB6E");
ASM_INLINE("_8BB23:");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("LEA	BX,[BP-0x20].B");
	ASM_INLINE("MOV	[BP-0x24].W,0x0002");
	ASM_INLINE("MOV	[BP-0x22].W,0xB9C4");
ASM_INLINE("_8BB32:");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("INC	[BP-0x24].W");
	ASM_INLINE("LES	BX,[BP-0x24]");
	ASM_INLINE("DEC	BX");
	ASM_INLINE("MOV	CL,ES:[BX].B");
	ASM_INLINE("POP	BX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	[BX].B,CL");
	ASM_INLINE("POP	BX");
	ASM_INLINE("INC	BX");
	ASM_INLINE("TEST	CL,CL");
	ASM_INLINE("JNZ	_8BB32");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("INC	AX");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("ADD	BX,0x0002");
	ASM_INLINE("ADD	BX,DX");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("LEA	CX,[BP-0x20].B");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALLF	bmp_print_, SEG bmp_print_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("POP	AX");
	ASM_INLINE("POP	DX");
ASM_INLINE("_8BB6E:");
	ASM_INLINE("ADD	DI,0x001D");
	ASM_INLINE("INC	DX");
ASM_INLINE("_8BB72:");
	ASM_INLINE("CMP	DX,0x0008");
	ASM_INLINE("JGE	_8BB7A");
	ASM_INLINE("JMP	_8B9F4");
ASM_INLINE("_8BB7A:");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("LEA	DI,[BP-0x20].B");
	ASM_INLINE("MOV	[BP-0x24].W,0x0004");
	ASM_INLINE("MOV	[BP-0x22].W,0xB9C5");
ASM_INLINE("_8BB88:");
	ASM_INLINE("INC	[BP-0x24].W");
	ASM_INLINE("LES	BX,[BP-0x24]");
	ASM_INLINE("DEC	BX");
	ASM_INLINE("MOV	BL,ES:[BX].B");
	ASM_INLINE("MOV	[DI].B,BL");
	ASM_INLINE("INC	DI");
	ASM_INLINE("TEST	BL,BL");
	ASM_INLINE("JNZ	_8BB88");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("INC	AX");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("ADD	BX,0x0002");
	ASM_INLINE("ADD	BX,DX");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("LEA	CX,[BP-0x20].B");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALLF	bmp_print_, SEG bmp_print_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("POP	AX");
	ASM_INLINE("JMP	_8BBCD");
ASM_INLINE("_8BBC3:");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("XOR	DX,DX");
	ASM_INLINE("CALL	unk_8B8D1_");
	ASM_INLINE("INC	CX");
	ASM_INLINE("POP	AX");
ASM_INLINE("_8BBCD:");
	ASM_INLINE("CMP	CX,0x0008");
	ASM_INLINE("JL	_8BBC3");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("JMP	_8BBE0");
ASM_INLINE("_8BBD6:");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("XOR	DX,DX");
	ASM_INLINE("CALL	unk_8B92E_");
	ASM_INLINE("INC	CX");
	ASM_INLINE("POP	AX");
ASM_INLINE("_8BBE0:");
	ASM_INLINE("CMP	CX,0x0002");
	ASM_INLINE("JL	_8BBD6");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
	ASM_INLINE("MOV	SP,BP");
	ASM_INLINE("POP	BP");
}

static void near unk_8BBED(s16 a, s16 b, s16 c, s16 d)
{
	char buffer[32];
	const char far *src;
    char *dst;
    char val;

	dst = buffer;
	src = unisel02;

    do {
        val = *src++;
		*dst++ = val;
    } while(val);

	bmp_print((a + 1) << 3, (b + 1 + d - 3) << 3, buffer, 1, 0);
}

static void near unk_8BC45()
{
	ASM_INLINE("PUSH	BP");
	ASM_INLINE("MOV	BP,SP");
	ASM_INLINE("SUB	SP,0x0014");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("LEA	SI,[BP-0x10].B");
	ASM_INLINE("MOV	[BP-0x14].W,0x0006");
	ASM_INLINE("MOV	[BP-0x12].W,0xB9C6");
ASM_INLINE("_8BC5B:");
	ASM_INLINE("INC	[BP-0x14].W");
	ASM_INLINE("LES	BX,[BP-0x14]");
	ASM_INLINE("DEC	BX");
	ASM_INLINE("MOV	AL,ES:[BX].B");
	ASM_INLINE("MOV	[SI].B,AL");
	ASM_INLINE("INC	SI");
	ASM_INLINE("TEST	AL,AL");
	ASM_INLINE("JNZ	_8BC5B");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("MOV	BX,0x0018");
	ASM_INLINE("LEA	CX,[BP-0x10].B");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALLF	bmp_print_, SEG bmp_print_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("LEA	SI,[BP-0x10].B");
	ASM_INLINE("MOV	[BP-0x14].W,0x000C");
	ASM_INLINE("MOV	[BP-0x12].W,0xB9C6");
ASM_INLINE("_8BC8F:");
	ASM_INLINE("INC	[BP-0x14].W");
	ASM_INLINE("LES	BX,[BP-0x14]");
	ASM_INLINE("DEC	BX");
	ASM_INLINE("MOV	AL,ES:[BX].B");
	ASM_INLINE("MOV	[SI].B,AL");
	ASM_INLINE("INC	SI");
	ASM_INLINE("TEST	AL,AL");
	ASM_INLINE("JNZ	_8BC8F");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("MOV	BX,0x0030");
	ASM_INLINE("LEA	CX,[BP-0x10].B");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALLF	bmp_print_, SEG bmp_print_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("LEA	SI,[BP-0x10].B");
	ASM_INLINE("MOV	[BP-0x14].W,0x0002");
	ASM_INLINE("MOV	[BP-0x12].W,0xB9C7");
ASM_INLINE("_8BCC3:");
	ASM_INLINE("INC	[BP-0x14].W");
	ASM_INLINE("LES	BX,[BP-0x14]");
	ASM_INLINE("DEC	BX");
	ASM_INLINE("MOV	AL,ES:[BX].B");
	ASM_INLINE("MOV	[SI].B,AL");
	ASM_INLINE("INC	SI");
	ASM_INLINE("TEST	AL,AL");
	ASM_INLINE("JNZ	_8BCC3");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("MOV	BX,0x0048");
	ASM_INLINE("LEA	CX,[BP-0x10].B");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALLF	bmp_print_, SEG bmp_print_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("LEA	SI,[BP-0x10].B");
	ASM_INLINE("MOV	[BP-0x14].W,0x0008");
	ASM_INLINE("MOV	[BP-0x12].W,0xB9C7");
ASM_INLINE("_8BCF7:");
	ASM_INLINE("INC	[BP-0x14].W");
	ASM_INLINE("LES	BX,[BP-0x14]");
	ASM_INLINE("DEC	BX");
	ASM_INLINE("MOV	AL,ES:[BX].B");
	ASM_INLINE("MOV	[SI].B,AL");
	ASM_INLINE("INC	SI");
	ASM_INLINE("TEST	AL,AL");
	ASM_INLINE("JNZ	_8BCF7");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("MOV	BX,0x0060");
	ASM_INLINE("LEA	CX,[BP-0x10].B");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALLF	bmp_print_, SEG bmp_print_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("LEA	SI,[BP-0x10].B");
	ASM_INLINE("MOV	[BP-0x14].W,0x000C");
	ASM_INLINE("MOV	[BP-0x12].W,0xB9C7");
ASM_INLINE("_8BD2B:");
	ASM_INLINE("INC	[BP-0x14].W");
	ASM_INLINE("LES	BX,[BP-0x14]");
	ASM_INLINE("DEC	BX");
	ASM_INLINE("MOV	AL,ES:[BX].B");
	ASM_INLINE("MOV	[SI].B,AL");
	ASM_INLINE("INC	SI");
	ASM_INLINE("TEST	AL,AL");
	ASM_INLINE("JNZ	_8BD2B");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("MOV	BX,0x0068");
	ASM_INLINE("LEA	CX,[BP-0x10].B");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALLF	bmp_print_, SEG bmp_print_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("LEA	SI,[BP-0x10].B");
	ASM_INLINE("MOV	[BP-0x14].W,0x0000");
	ASM_INLINE("MOV	[BP-0x12].W,0xB9C8");
ASM_INLINE("_8BD5F:");
	ASM_INLINE("INC	[BP-0x14].W");
	ASM_INLINE("LES	BX,[BP-0x14]");
	ASM_INLINE("DEC	BX");
	ASM_INLINE("MOV	AL,ES:[BX].B");
	ASM_INLINE("MOV	[SI].B,AL");
	ASM_INLINE("INC	SI");
	ASM_INLINE("TEST	AL,AL");
	ASM_INLINE("JNZ	_8BD5F");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("MOV	BX,0x0070");
	ASM_INLINE("LEA	CX,[BP-0x10].B");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALLF	bmp_print_, SEG bmp_print_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
	ASM_INLINE("MOV	SP,BP");
	ASM_INLINE("POP	BP");
}

static void near unk_8BD8D(s16 a, s16 b, s16 c, s16 d)
{
	switch(c / 20)
	{
		case 0:
		{
			font_put2XY((c - 00) << 2, 0, 4, 4, a, b, 1, G_AU1_char_adr);
			break;
		}
		case 1:
		{
			font_put2XY((c - 20) << 2, 0, 4, 4, a, b, 1, G_AU2_char_adr);
			break;
		}
		case 2:
		{
			font_put2XY((c - 40) << 2, 0, 4, 4, a, b, 1, G_AU3_char_adr);
		}
		case 3:
		{
			break;
		}
	}
}

static void near unk_8BE2C(s16 a, s16 b, s16 c, s16 d)
{
	switch(c / 20)
	{
		case 0:
		{
			font_put2XY((c - 00) << 2, 4, 2, 3, a, b, 1, G_AU1_char_adr);
			break;
		}
		case 1:
		{
			font_put2XY((c - 20) << 2, 4, 2, 3, a, b, 1, G_AU2_char_adr);
			break;
		}
		case 2:
		{
			font_put2XY((c - 40) << 2, 4, 2, 3, a, b, 1, G_AU3_char_adr);
		}
		case 3:
		{
			break;
		}
	}
}

static void near unk_8BECE(s16 a)
{
	u8 *ptr = SAVE_DATA_START+0x0B;
	if (a - 3 < 0)
	{
		unk_8BE2C(0xc, 3, 0x32, a);
	}
	else if ((ptr[a - 3] & 0x80))
	{
		unk_8BE2C(0xc, 3, a - 3, a);
	}
	else
	{
		unk_8BE2C(0xc, 3, 0x31, a);
	}

	if (a - 2 < 0)
	{
		unk_8BE2C(0xe, 3, 0x32, a);
	}
	else if ((ptr[a - 2] & 0x80))
	{
		unk_8BE2C(0xe, 3, a - 2, a);
	}
	else
	{
		unk_8BE2C(0xe, 3, 0x31, a);
	}

	if (a - 1 < 0)
	{
		unk_8BE2C(0x10,3,0x32,a);
	}
	else if ((ptr[a - 1] & 0x80))
	{
		unk_8BE2C(0x10, 3, a - 1, a);
	}
	else
	{
		unk_8BE2C(0x10, 3, 0x31, a);
	}

	if ((ptr[a] & 0x80))
	{
		unk_8BD8D(0x12, 3, a, a);
	}
	else
	{
		unk_8BD8D(0x12, 3, 0x31, a);
	}

	if (0x29 < a + 1)
	{
		unk_8BE2C(0x16, 4, 0x32, a);
	}
	else if ((ptr[a + 1] & 0x80))
	{
		unk_8BE2C(0x16, 4, a + 1, a);
	}
	else
	{
		unk_8BE2C(0x16, 4, 0x31, a);
	}

	if (0x29 < a + 2)
	{
		unk_8BE2C(0x18,4,0x32,a);
	}
	else if ((ptr[a + 2] & 0x80))
	{
		unk_8BE2C(0x18, 4, a + 2, a);
	}
	else
	{
		unk_8BE2C(0x18, 4, 0x31, a);
	}

	if (0x29 < a + 3)
	{
		unk_8BE2C(0x1a, 4, 0x32, a);
	}
	else if ((ptr[a + 3] & 0x80))
	{
		unk_8BE2C(0x1a, 4, a += 3, a); //required to match
	}
	else
	{
		unk_8BE2C(0x1a, 4, 0x31, a);
	}
}

static void near unk_8C070(u16 val)
{
	stage_get; //Force include
	ASM_INLINE("PUSH	BP");
	ASM_INLINE("MOV	BP,SP");
	ASM_INLINE("SUB	SP,0x0058");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	DI,AX");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("MOV	BX,0x000F");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("MOV	CX,0x0004");
	ASM_INLINE("MOV	BX,0xA751");
	ASM_INLINE("ADD	CX,AX");
	ASM_INLINE("MOV	[BP-0x04].W,CX");
	ASM_INLINE("MOV	[BP-0x02].W,BX");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("CALL	unk_8B67E_");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("MOV	BL,ES:[BX].B");
	ASM_INLINE("MOV	[BP-0x13].B,BL");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("MOV	BL,ES:[BX+0x01].B");
	ASM_INLINE("MOV	[BP-0x12].B,BL");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("MOV	BL,ES:[BX+0x02].B");
	ASM_INLINE("MOV	[BP-0x11].B,BL");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("MOV	BL,ES:[BX+0x03].B");
	ASM_INLINE("MOV	[BP-0x10].B,BL");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("MOV	BL,ES:[BX+0x04].B");
	ASM_INLINE("MOV	[BP-0x0F].B,BL");
	ASM_INLINE("XOR	SI,SI");
	ASM_INLINE("JMP	_8C0DA");
ASM_INLINE("_8C0CB:");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("ADD	BX,0x0005");
	ASM_INLINE("ADD	BX,SI");
	ASM_INLINE("MOV	BL,ES:[BX].B");
	ASM_INLINE("MOV	-0x0E[BP+SI].B,BL");
	ASM_INLINE("INC	SI");
ASM_INLINE("_8C0DA:");
	ASM_INLINE("CMP	SI,0x0008");
	ASM_INLINE("JL	_8C0CB");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("MOV	BL,ES:[BX+0x0D].B");
	ASM_INLINE("MOV	[BP-0x06].B,BL");
	ASM_INLINE("MOV	BL,[0x1E07].B");
	ASM_INLINE("CMP	BL,0x03");
	ASM_INLINE("JNZ	_8C0F5");
	ASM_INLINE("JMP	_8C213");
ASM_INLINE("_8C0F5:");
	ASM_INLINE("CMP	BL,0x02");
	ASM_INLINE("JNZ	_8C0FD");
	ASM_INLINE("JMP	_8C189");
ASM_INLINE("_8C0FD:");
	ASM_INLINE("CMP	BL,0x01");
	ASM_INLINE("JZ	_8C109");
	ASM_INLINE("TEST	BL,BL");
	ASM_INLINE("JZ	_8C109");
	ASM_INLINE("JMP	_8C213");
ASM_INLINE("_8C109:");
	ASM_INLINE("TEST	AX,AX");
	ASM_INLINE("JZ	_8C189");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	BX,0xA751");
	ASM_INLINE("MOV	ES,BX");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("MOV	BX,0x000F");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("MOV	BX,AX");
	//ASM_INLINE("MOV	BL,ES:[BX+0x0004].B");
	ASM_OP5(0x26,0x8A,0x9F,0x04,0x00);
	ASM_INLINE("MOV	[BP-0x13].B,BL");
	ASM_INLINE("POP	AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("CALLF	stage_get_, SEG stage_get_");
	ASM_INLINE("MOV	[BP-0x12].B,AL");
	ASM_INLINE("POP	AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	BX,0x001D");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("MOV	BX,AX");
	ASM_INLINE("ADD	BX,0x1E3C");
	ASM_INLINE("MOV	BL,[BX+0x02].B");
	ASM_INLINE("MOV	[BP-0x11].B,BL");
	ASM_INLINE("POP	AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	BX,0x001D");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("MOV	BX,AX");
	ASM_INLINE("ADD	BX,0x1E3C");
	ASM_INLINE("MOV	BL,[BX+0x03].B");
	ASM_INLINE("MOV	[BP-0x10].B,BL");
	ASM_INLINE("POP	AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	BX,0x001D");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("MOV	BX,AX");
	ASM_INLINE("ADD	BX,0x1E3C");
	ASM_INLINE("MOV	BL,[BX+0x04].B");
	ASM_INLINE("MOV	[BP-0x0F].B,BL");
	ASM_INLINE("XOR	SI,SI");
	ASM_INLINE("POP	AX");
	ASM_INLINE("JMP	_8C184");
ASM_INLINE("_8C16C:");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	BX,0x001D");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("MOV	BX,AX");
	ASM_INLINE("ADD	BX,0x1E3C");
	ASM_INLINE("ADD	BX,0x0005");
	ASM_INLINE("ADD	BX,SI");
	ASM_INLINE("MOV	BL,[BX].B");
	ASM_INLINE("MOV	-0x0E[BP+SI].B,BL");
	ASM_INLINE("INC	SI");
	ASM_INLINE("POP	AX");
ASM_INLINE("_8C184:");
	ASM_INLINE("CMP	SI,0x0008");
	ASM_INLINE("JL	_8C16C");
ASM_INLINE("_8C189:");
	ASM_INLINE("CMP	[0x1E08].B,0x00");
	ASM_INLINE("JNZ	_8C193");
	ASM_INLINE("JMP	_8C213");
ASM_INLINE("_8C193:");
	ASM_INLINE("TEST	AX,AX");
	ASM_INLINE("JZ	_8C213");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	BX,0xA751");
	ASM_INLINE("MOV	ES,BX");
	ASM_INLINE("MOV	AX,DI");
	ASM_INLINE("MOV	BX,0x000F");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("MOV	BX,AX");
	//ASM_INLINE("MOV	BL,ES:[BX+0x0004].B");
	ASM_OP5(0x26,0x8A,0x9F,0x04,0x00);
	ASM_INLINE("MOV	[BP-0x13].B,BL");
	ASM_INLINE("POP	AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("CALLF	stage_get_, SEG stage_get_");
	ASM_INLINE("MOV	[BP-0x12].B,AL");
	ASM_INLINE("POP	AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	BX,0x001D");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("MOV	BX,AX");
	ASM_INLINE("ADD	BX,0x1E3C");
	ASM_INLINE("MOV	BL,[BX+0x02].B");
	ASM_INLINE("MOV	[BP-0x11].B,BL");
	ASM_INLINE("POP	AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	BX,0x001D");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("MOV	BX,AX");
	ASM_INLINE("ADD	BX,0x1E3C");
	ASM_INLINE("MOV	BL,[BX+0x03].B");
	ASM_INLINE("MOV	[BP-0x10].B,BL");
	ASM_INLINE("POP	AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	BX,0x001D");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("MOV	BX,AX");
	ASM_INLINE("ADD	BX,0x1E3C");
	ASM_INLINE("MOV	BL,[BX+0x04].B");
	ASM_INLINE("MOV	[BP-0x0F].B,BL");
	ASM_INLINE("XOR	SI,SI");
	ASM_INLINE("POP	AX");
	ASM_INLINE("JMP	_8C20E");
ASM_INLINE("_8C1F6:");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	BX,0x001D");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("MOV	BX,AX");
	ASM_INLINE("ADD	BX,0x1E3C");
	ASM_INLINE("ADD	BX,0x0005");
	ASM_INLINE("ADD	BX,SI");
	ASM_INLINE("MOV	BL,[BX].B");
	ASM_INLINE("MOV	-0x0E[BP+SI].B,BL");
	ASM_INLINE("INC	SI");
	ASM_INLINE("POP	AX");
ASM_INLINE("_8C20E:");
	ASM_INLINE("CMP	SI,0x0008");
	ASM_INLINE("JL	_8C1F6");
ASM_INLINE("_8C213:");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("LEA	SI,[BP-0x33].B");
	ASM_INLINE("MOV	BX,0xA79C");
	ASM_INLINE("MOV	ES,BX");
	ASM_INLINE("MOV	AL,[BP-0x13].B");
	ASM_INLINE("CBW");
	ASM_INLINE("MOV	BX,AX");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	//ASM_INLINE("MOV	CX,ES:[BX+0x0002].W");
	ASM_OP5(0x26,0x8B,0x8F,0x02,0x00);
	//ASM_INLINE("MOV	BX,ES:[BX+0x0004].W");
	ASM_OP5(0x26,0x8B,0x9F,0x04,0x00);
	ASM_INLINE("MOV	[BP-0x37].W,CX");
	ASM_INLINE("MOV	[BP-0x35].W,BX");
ASM_INLINE("_8C236:");
	ASM_INLINE("INC	[BP-0x37].W");
	ASM_INLINE("LES	BX,[BP-0x37]");
	ASM_INLINE("DEC	BX");
	ASM_INLINE("MOV	BL,ES:[BX].B");
	ASM_INLINE("MOV	[SI].B,BL");
	ASM_INLINE("INC	SI");
	ASM_INLINE("TEST	BL,BL");
	ASM_INLINE("JNZ	_8C236");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,0x0028");
	ASM_INLINE("MOV	BX,0x0018");
	ASM_INLINE("LEA	CX,[BP-0x33].B");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALLF	bmp_print_, SEG bmp_print_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("LEA	SI,[BP-0x33].B");
	ASM_INLINE("MOV	BX,0xB9CC");
	ASM_INLINE("MOV	ES,BX");
	ASM_INLINE("MOV	AL,[BP-0x06].B");
	ASM_INLINE("CBW");
	ASM_INLINE("MOV	BX,AX");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	//ASM_INLINE("MOV	CX,ES:[BX+0x000E].W");
	ASM_OP5(0x26,0x8B,0x8F,0x0E,0x00);
	//ASM_INLINE("MOV	BX,ES:[BX+0x0010].W");
	ASM_OP5(0x26,0x8B,0x9F,0x10,0x00);
	ASM_INLINE("MOV	[BP-0x37].W,CX");
	ASM_INLINE("MOV	[BP-0x35].W,BX");
ASM_INLINE("_8C280:");
	ASM_INLINE("INC	[BP-0x37].W");
	ASM_INLINE("LES	BX,[BP-0x37]");
	ASM_INLINE("DEC	BX");
	ASM_INLINE("MOV	BL,ES:[BX].B");
	ASM_INLINE("MOV	[SI].B,BL");
	ASM_INLINE("INC	SI");
	ASM_INLINE("TEST	BL,BL");
	ASM_INLINE("JNZ	_8C280");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,0x0010");
	ASM_INLINE("MOV	BX,0x0020");
	ASM_INLINE("LEA	CX,[BP-0x33].B");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALLF	bmp_print_, SEG bmp_print_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("LEA	SI,[BP-0x33].B");
	ASM_INLINE("MOV	BX,0xA78E");
	ASM_INLINE("MOV	ES,BX");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("SHL	BX,1");
	//ASM_INLINE("MOV	CX,ES:[BX+0x000A].W");
	ASM_OP5(0x26,0x8B,0x8F,0x0A,0x00);
	//ASM_INLINE("MOV	BX,ES:[BX+0x000C].W");
	ASM_OP5(0x26,0x8B,0x9F,0x0C,0x00);
	ASM_INLINE("MOV	[BP-0x37].W,CX");
	ASM_INLINE("MOV	[BP-0x35].W,BX");
ASM_INLINE("_8C2C6:");
	ASM_INLINE("INC	[BP-0x37].W");
	ASM_INLINE("LES	BX,[BP-0x37]");
	ASM_INLINE("DEC	BX");
	ASM_INLINE("MOV	BL,ES:[BX].B");
	ASM_INLINE("MOV	[SI].B,BL");
	ASM_INLINE("INC	SI");
	ASM_INLINE("TEST	BL,BL");
	ASM_INLINE("JNZ	_8C2C6");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,0x0028");
	ASM_INLINE("MOV	BX,0x0030");
	ASM_INLINE("LEA	CX,[BP-0x33].B");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALLF	bmp_print_, SEG bmp_print_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("TEST	[DI+0x1E0B].B,0x80");
	ASM_INLINE("POP	AX");
	ASM_INLINE("JNZ	_8C2F9");
	ASM_INLINE("JMP	_8C3C9");
ASM_INLINE("_8C2F9:");
	ASM_INLINE("LEA	SI,[BP-0x33].B");
	ASM_INLINE("MOV	BX,0xB9CC");
	ASM_INLINE("MOV	ES,BX");
	//ASM_INLINE("MOV	CX,ES:[0x0022].W");
	ASM_OP5(0x26,0x8B,0x0E,0x22,0x00);
	//ASM_INLINE("MOV	BX,ES:[0x0024].W");
	ASM_OP5(0x26,0x8B,0x1E,0x24,0x00);
	ASM_INLINE("MOV	[BP-0x37].W,CX");
	ASM_INLINE("MOV	[BP-0x35].W,BX");
ASM_INLINE("_8C311:");
	ASM_INLINE("INC	[BP-0x37].W");
	ASM_INLINE("LES	BX,[BP-0x37]");
	ASM_INLINE("DEC	BX");
	ASM_INLINE("MOV	BL,ES:[BX].B");
	ASM_INLINE("MOV	[SI].B,BL");
	ASM_INLINE("INC	SI");
	ASM_INLINE("TEST	BL,BL");
	ASM_INLINE("JNZ	_8C311");
	ASM_INLINE("MOV	BL,[0x1E07].B");
	ASM_INLINE("CMP	BL,0x03");
	ASM_INLINE("JNZ	_8C32E");
	ASM_INLINE("JMP	_8C3F1");
ASM_INLINE("_8C32E:");
	ASM_INLINE("CMP	BL,0x02");
	ASM_INLINE("JZ	_8C382");
	ASM_INLINE("CMP	BL,0x01");
	ASM_INLINE("JZ	_8C33F");
	ASM_INLINE("TEST	BL,BL");
	ASM_INLINE("JZ	_8C33F");
	ASM_INLINE("JMP	_8C3F1");
ASM_INLINE("_8C33F:");
	ASM_INLINE("TEST	AX,AX");
	ASM_INLINE("JNZ	_8C346");
	ASM_INLINE("JMP	_8C3F1");
ASM_INLINE("_8C346:");
	ASM_INLINE("LEA	SI,[BP-0x57].B");
	ASM_INLINE("MOV	BX,0xB9CC");
	ASM_INLINE("MOV	ES,BX");
	//ASM_INLINE("MOV	CX,ES:[0x001E].W");
	ASM_OP5(0x26,0x8B,0x0E,0x1E,0x00);
	//ASM_INLINE("MOV	BX,ES:[0x0020].W");
	ASM_OP5(0x26,0x8B,0x1E,0x20,0x00);
	ASM_INLINE("MOV	[BP-0x37].W,CX");
	ASM_INLINE("MOV	[BP-0x35].W,BX");
ASM_INLINE("_8C35E:");
	ASM_INLINE("INC	[BP-0x37].W");
	ASM_INLINE("LES	BX,[BP-0x37]");
	ASM_INLINE("DEC	BX");
	ASM_INLINE("MOV	BL,ES:[BX].B");
	ASM_INLINE("MOV	[SI].B,BL");
	ASM_INLINE("INC	SI");
	ASM_INLINE("TEST	BL,BL");
	ASM_INLINE("JNZ	_8C35E");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("LEA	AX,[BP-0x57].B");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("LEA	AX,[BP-0x33].B");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("CALLF	hsprintf_, SEG hsprintf_");
	ASM_INLINE("ADD	SP,0x0006");
	ASM_INLINE("JMP	_8C3F1");
ASM_INLINE("_8C382:");
	ASM_INLINE("CMP	[0x1E08].B,0x00");
	ASM_INLINE("JZ	_8C3F1");
	ASM_INLINE("TEST	AX,AX");
	ASM_INLINE("JZ	_8C3F1");
	ASM_INLINE("LEA	SI,[BP-0x57].B");
	ASM_INLINE("MOV	BX,0xB9CC");
	ASM_INLINE("MOV	ES,BX");
	//ASM_INLINE("MOV	CX,ES:[0x001E].W");
	ASM_OP5(0x26,0x8B,0x0E,0x1E,0x00);
	//ASM_INLINE("MOV	BX,ES:[0x0020].W");
	ASM_OP5(0x26,0x8B,0x1E,0x20,0x00);
	ASM_INLINE("MOV	[BP-0x37].W,CX");
	ASM_INLINE("MOV	[BP-0x35].W,BX");
ASM_INLINE("_8C3A5:");
	ASM_INLINE("INC	[BP-0x37].W");
	ASM_INLINE("LES	BX,[BP-0x37]");
	ASM_INLINE("DEC	BX");
	ASM_INLINE("MOV	BL,ES:[BX].B");
	ASM_INLINE("MOV	[SI].B,BL");
	ASM_INLINE("INC	SI");
	ASM_INLINE("TEST	BL,BL");
	ASM_INLINE("JNZ	_8C3A5");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("LEA	AX,[BP-0x57].B");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("LEA	AX,[BP-0x33].B");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("CALLF	hsprintf_, SEG hsprintf_");
	ASM_INLINE("ADD	SP,0x0006");
	ASM_INLINE("JMP	_8C3F1");
ASM_INLINE("_8C3C9:");
	ASM_INLINE("LEA	BX,[BP-0x33].B");
	ASM_INLINE("MOV	AX,0xB9CC");
	ASM_INLINE("MOV	ES,AX");
	//ASM_INLINE("MOV	CX,ES:[0x0026].W");
	ASM_OP5(0x26,0x8B,0x0E,0x26,0x00);
	//ASM_INLINE("MOV	AX,ES:[0x0028].W");
	ASM_OP4(0x26,0xA1,0x28,0x00);
	ASM_INLINE("MOV	[BP-0x37].W,CX");
	ASM_INLINE("MOV	[BP-0x35].W,AX");
ASM_INLINE("_8C3E0:");
	ASM_INLINE("INC	[BP-0x37].W");
	ASM_INLINE("LES	SI,[BP-0x37]");
	ASM_INLINE("DEC	SI");
	ASM_INLINE("MOV	AL,ES:[SI].B");
	ASM_INLINE("MOV	[BX].B,AL");
	ASM_INLINE("INC	BX");
	ASM_INLINE("TEST	AL,AL");
	ASM_INLINE("JNZ	_8C3E0");
ASM_INLINE("_8C3F1:");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x0010");
	ASM_INLINE("MOV	BX,0x0038");
	ASM_INLINE("LEA	CX,[BP-0x33].B");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALLF	bmp_print_, SEG bmp_print_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("CMP	[BP-0x12].B,0x00");
	ASM_INLINE("JZ	_8C43C");
	ASM_INLINE("MOV	AL,[BP-0x12].B");
	ASM_INLINE("CBW");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x071C");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("LEA	AX,[BP-0x33].B");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("CALLF	hsprintf_, SEG hsprintf_");
	ASM_INLINE("ADD	SP,0x0006");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x0028");
	ASM_INLINE("MOV	BX,0x0050");
	ASM_INLINE("LEA	CX,[BP-0x33].B");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALLF	bmp_print_, SEG bmp_print_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("JMP	_8C453");
ASM_INLINE("_8C43C:");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x0028");
	ASM_INLINE("MOV	BX,0x0050");
	ASM_INLINE("MOV	CX,0x0722");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALLF	bmp_print_, SEG bmp_print_");
	ASM_INLINE("ADD	SP,0x0002");
ASM_INLINE("_8C453:");
	ASM_INLINE("MOV	AL,[BP-0x11].B");
	ASM_INLINE("CBW");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x0726");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("LEA	AX,[BP-0x33].B");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("CALLF	hsprintf_, SEG hsprintf_");
	ASM_INLINE("ADD	SP,0x0006");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x0028");
	ASM_INLINE("MOV	BX,0x0060");
	ASM_INLINE("LEA	CX,[BP-0x33].B");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALLF	bmp_print_, SEG bmp_print_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("MOV	AL,[BP-0x10].B");
	ASM_INLINE("CBW");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x072C");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("LEA	AX,[BP-0x33].B");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("CALLF	hsprintf_, SEG hsprintf_");
	ASM_INLINE("ADD	SP,0x0006");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x0028");
	ASM_INLINE("MOV	BX,0x0068");
	ASM_INLINE("LEA	CX,[BP-0x33].B");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALLF	bmp_print_, SEG bmp_print_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("CMP	[BP-0x0F].B,0x00");
	ASM_INLINE("JZ	_8C4DF");
	ASM_INLINE("MOV	AL,[BP-0x0F].B");
	ASM_INLINE("CBW");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x0732");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("LEA	AX,[BP-0x33].B");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("CALLF	hsprintf_, SEG hsprintf_");
	ASM_INLINE("ADD	SP,0x0006");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x0028");
	ASM_INLINE("MOV	BX,0x0070");
	ASM_INLINE("LEA	CX,[BP-0x33].B");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALLF	bmp_print_, SEG bmp_print_");
	ASM_INLINE("ADD	SP,0x0002");
	ASM_INLINE("JMP	_8C4F6");
ASM_INLINE("_8C4DF:");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x0028");
	ASM_INLINE("MOV	BX,0x0070");
	ASM_INLINE("MOV	CX,0x0738");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALLF	bmp_print_, SEG bmp_print_");
	ASM_INLINE("ADD	SP,0x0002");
ASM_INLINE("_8C4F6:");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("XOR	SI,SI");
	ASM_INLINE("JMP	_8C5C9");
ASM_INLINE("_8C4FD:");
	ASM_INLINE("CMP	-0x0E[BP+SI].B,0xFF");
	ASM_INLINE("JZ	_8C57E");
	ASM_INLINE("MOV	AL,-0x0E[BP+SI].B");
	ASM_INLINE("CBW");
	ASM_INLINE("MOV	DI,AX");
	ASM_INLINE("MOV	BX,0x0000");
	ASM_INLINE("MOV	AX,0xAF36");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,SI");
	ASM_INLINE("SAR	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("ADD	AX,0x0008");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x000A");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("AND	BX,0x0001");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("ADD	AX,0x0010");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x0008");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("MOV	CX,0x0002");
	ASM_INLINE("MOV	DX,0x0002");
	ASM_INLINE("CALLF	font_put2XY_, SEG font_put2XY_");
	ASM_INLINE("ADD	SP,0x000A");
	ASM_INLINE("MOV	BX,0x0000");
	ASM_INLINE("MOV	AX,0xAF36");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,SI");
	ASM_INLINE("SAR	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("ADD	AX,0x0008");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x000A");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("AND	BX,0x0001");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("ADD	AX,0x0008");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("SHL	DI,1");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("MOV	CX,0x0008");
	ASM_INLINE("MOV	DX,0x0002");
	ASM_INLINE("CALLF	font_put2XY_, SEG font_put2XY_");
	ASM_INLINE("ADD	SP,0x000A");
	ASM_INLINE("JMP	_8C5C8");
ASM_INLINE("_8C57E:");
	ASM_INLINE("MOV	BX,0x0000");
	ASM_INLINE("MOV	AX,0xB9CF");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,SI");
	ASM_INLINE("SAR	AX,1");
	ASM_INLINE("SHL	AX,1");
	ASM_INLINE("ADD	AX,0x0008");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x000A");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("AND	BX,0x0001");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("ADD	AX,0x0008");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x000A");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("AND	BX,0x0001");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("ADD	AX,0x0008");
	ASM_INLINE("MOV	BX,SI");
	ASM_INLINE("SAR	BX,1");
	ASM_INLINE("SHL	BX,1");
	ASM_INLINE("ADD	BX,0x0008");
	ASM_INLINE("MOV	CX,0x000A");
	ASM_INLINE("MOV	DX,0x0002");
	ASM_INLINE("CALLF	font_put2XY_, SEG font_put2XY_");
	ASM_INLINE("ADD	SP,0x000A");
ASM_INLINE("_8C5C8:");
	ASM_INLINE("INC	SI");
ASM_INLINE("_8C5C9:");
	ASM_INLINE("CMP	SI,0x0008");
	ASM_INLINE("JGE	_8C5D1");
	ASM_INLINE("JMP	_8C4FD");
ASM_INLINE("_8C5D1:");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
	ASM_INLINE("MOV	SP,BP");
	ASM_INLINE("POP	BP");
}

static void near unk_8C5D9(struct UniselWork *work)
{
	/*
	switch(SAVE_DATA_START[0x07])
	{
		case 0:
		{
			break;
		}
		case 1:
		{
			break;
		}
		case 2:
		{
			font_put2XY(0xb, 0x12, 7, 1, 2, 0x10, 1, G_UNISE2_char_adr);
			font_put2XY(0x12, 0x12, 1, 1, 9, 0x10, 1, G_UNISE2_char_adr);
			font_put2XY(0xb, 0x12, 7, 1, 0x12, 0x10, 1, G_UNISE2_char_adr);
			font_put2XY(0x13, 0x12 ,1, 1, 0x19, 0x10, 1, G_UNISE2_char_adr);
			break;
		}
		case 3:
		{
			break;
		}
	}*/


	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("MOV	AL,[0x1E07].B");
	ASM_INLINE("CMP	AL,0x03");
	ASM_INLINE("JNZ	_8C5E5");
	ASM_INLINE("JMP	_8C69A");
ASM_INLINE("_8C5E5:");
	ASM_INLINE("CMP	AL,0x02");
	ASM_INLINE("JZ	_8C5FA");
	ASM_INLINE("CMP	AL,0x01");
	ASM_INLINE("JNZ	_8C5F0");
	ASM_INLINE("JMP	_8C69A");
ASM_INLINE("_8C5F0:");
	ASM_INLINE("TEST	AL,AL");
	ASM_INLINE("JNZ	_8C5F7");
	ASM_INLINE("JMP	_8C69A");
ASM_INLINE("_8C5F7:");
	ASM_INLINE("JMP	_8C69A");
ASM_INLINE("_8C5FA:");
	ASM_INLINE("MOV	BX,0x0000");
	ASM_INLINE("MOV	AX,0xB9CF");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x0010");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x0002");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x000B");
	ASM_INLINE("MOV	BX,0x0012");
	ASM_INLINE("MOV	CX,0x0007");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALLF	font_put2XY_, SEG font_put2XY_");
	ASM_INLINE("ADD	SP,0x000A");
	ASM_INLINE("MOV	BX,0x0000");
	ASM_INLINE("MOV	AX,0xB9CF");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x0010");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x0009");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x0012");
	ASM_INLINE("MOV	BX,0x0012");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALLF	font_put2XY_, SEG font_put2XY_");
	ASM_INLINE("ADD	SP,0x000A");
	ASM_INLINE("MOV	BX,0x0000");
	ASM_INLINE("MOV	AX,0xB9CF");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x0010");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x0012");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x000B");
	ASM_INLINE("MOV	BX,0x0012");
	ASM_INLINE("MOV	CX,0x0007");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALLF	font_put2XY_, SEG font_put2XY_");
	ASM_INLINE("ADD	SP,0x000A");
	ASM_INLINE("MOV	BX,0x0000");
	ASM_INLINE("MOV	AX,0xB9CF");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x0010");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x0019");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,0x0013");
	ASM_INLINE("MOV	BX,0x0012");
	ASM_INLINE("MOV	CX,0x0001");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALLF	font_put2XY_, SEG font_put2XY_");
	ASM_INLINE("ADD	SP,0x000A");
ASM_INLINE("_8C69A:");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
}

static void near unk_8C69D(struct UniselWork *work)
{
	u8 val = SAVE_DATA_START[0x07];

	if(val == 3)
	{
		return;
	}
	if(val != 2)
	{
		if(val == 1)
		{
			return;
		}
		if(val == 0) 
		{
			return;
		}
	}
	else
	{
		if (work->unk2 == 2)
		{
			font_put2XY(0x18,0x12,4,1,4,0x11,1,&G_UNISE2_char_adr);
		}
		else
		{
			font_put2XY(0x14,0x12,4,1,4,0x11,1,&G_UNISE2_char_adr);
		}
		if (work->unkA == 1)
		{
			font_put2XY(0x18,0x12,4,1,0x14,0x11,1,&G_UNISE2_char_adr);
		}
		else
		{
			font_put2XY(0x14,0x12,4,1,0x14,0x11,1,&G_UNISE2_char_adr);
		}
	}
}

void unisel_init(void *buf)
{
	struct UniselWork *work;

	task_delete();
	work = (struct UniselWork *)memalloc(sizeof (struct UniselWork));
	if (work != NULL)
	{
		task_append((task_pointer)unk_8C874, (u16)work);
		work->unk0 = buf;
		work->unk2 = 0;
		work->unk4 = 0;
		work->unk6 = 0;
		work->unk8 = 0;
		work->unkA = 0;
		unk_8B5EC();

		{
			/*073C*/
			u8 unisel_data[] = {
				0x01, 0x01, 0xA8, 0xC0,
				0x00, 0x00, 0x00, 0x00,
				0x00, 0x00, 0x00, 0x00,
				0x00, 0x00, 0x00, 0x00,
				0x00, 0x00, 0x00, 0x00,
				0x04, 0x00,
			};
			ip_clear(unisel_data);
		}

		nbg_ddf(0,0);
		nbg_ddf(1,0);
		spr_ddf(0);
		bitmap(1);
		font_put2XY(0, 0, 0x1c, 0x12, 0, 0, 1, G_UNISE2_char_adr);
		unk_8BC45();
		unk_8C5D9(work);
		unk_8BECE(work->unk4);
		unk_8C070(work->unk4);
		fade_tone(0);
		fade_out(100);
		fade_run();
		fade_in(10);
		nbg_ddf(0,1);
		nbg_ddf(1,1);
		bgmreq(2);
	}
}

static void unk_8C874(struct UniselWork *work)
{
	sereq; //Force include
	memfree; //Force include
	task_delete_fade; //Force include
	stage_select_init; //Force include
	menu_init; //Force include
	m_game_init; //Force include
	ASM_INLINE("PUSH	BP");
	ASM_INLINE("MOV	BP,SP");
	ASM_INLINE("SUB	SP,0x0004");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("MOV	SI,AX");
	ASM_INLINE("MOV	AX,[SI].W");
	ASM_INLINE("MOV	AX,[SI+0x02].W");
	ASM_INLINE("CMP	AX,0x0002");
	ASM_INLINE("JNZ	_8C88D");
	ASM_INLINE("JMP	_8CE9C");
ASM_INLINE("_8C88D:");
	ASM_INLINE("CMP	AX,0x0001");
	ASM_INLINE("JNZ	_8C895");
	ASM_INLINE("JMP	_8CC95");
ASM_INLINE("_8C895:");
	ASM_INLINE("TEST	AX,AX");
	ASM_INLINE("JZ	_8C89C");
	ASM_INLINE("JMP	_8CEDA");
ASM_INLINE("_8C89C:");
	ASM_INLINE("TEST	[0x0956].W,0x0800");
	ASM_INLINE("JZ	_8C8C2");
	ASM_INLINE("MOV	AL,0x0C");
	ASM_INLINE("CALLF	sereq_, SEG sereq_");
	ASM_INLINE("CMP	[SI+0x04].W,0x0000");
	ASM_INLINE("JLE	_8C8E6");
	ASM_INLINE("DEC	[SI+0x04].W");
	ASM_INLINE("MOV	AX,[SI+0x04].W");
	ASM_INLINE("CALL	unk_8BECE_");
	ASM_INLINE("MOV	AX,[SI+0x04].W");
	ASM_INLINE("CALL	unk_8C070_");
	ASM_INLINE("JMP	_8C8E6");
ASM_INLINE("_8C8C2:");
	ASM_INLINE("TEST	[0x0956].W,0x0200");
	ASM_INLINE("JZ	_8C8E6");
	ASM_INLINE("MOV	AL,0x0C");
	ASM_INLINE("CALLF	sereq_, SEG sereq_");
	ASM_INLINE("CMP	[SI+0x04].W,0x0029");
	ASM_INLINE("JGE	_8C8E6");
	ASM_INLINE("INC	[SI+0x04].W");
	ASM_INLINE("MOV	AX,[SI+0x04].W");
	ASM_INLINE("CALL	unk_8BECE_");
	ASM_INLINE("MOV	AX,[SI+0x04].W");
	ASM_INLINE("CALL	unk_8C070_");
ASM_INLINE("_8C8E6:");
	ASM_INLINE("MOV	AL,[0x1E07].B");
	ASM_INLINE("CMP	AL,0x03");
	ASM_INLINE("JNZ	_8C8F0");
	ASM_INLINE("JMP	_8C9B7");
ASM_INLINE("_8C8F0:");
	ASM_INLINE("CMP	AL,0x02");
	ASM_INLINE("JZ	_8C95A");
	ASM_INLINE("CMP	AL,0x01");
	ASM_INLINE("JZ	_8C8FF");
	ASM_INLINE("TEST	AL,AL");
	ASM_INLINE("JZ	_8C8FF");
	ASM_INLINE("JMP	_8C9B7");
ASM_INLINE("_8C8FF:");
	ASM_INLINE("TEST	[0x0956].W,0x0100");
	ASM_INLINE("JNZ	_8C912");
	ASM_INLINE("TEST	[0x0956].W,0x0400");
	ASM_INLINE("JNZ	_8C912");
	ASM_INLINE("JMP	_8C9B7");
ASM_INLINE("_8C912:");
	ASM_INLINE("MOV	[SI+0x02].W,0x0001");
	ASM_INLINE("MOV	[SI+0x08].W,0x0000");
	ASM_INLINE("MOV	AX,0x0005");
	ASM_INLINE("MOV	BX,0x0003");
	ASM_INLINE("MOV	CX,0x0013");
	ASM_INLINE("MOV	DX,0x000C");
	ASM_INLINE("CALL	unk_8B6D5_");
	ASM_INLINE("MOV	AX,0x0005");
	ASM_INLINE("MOV	BX,0x0003");
	ASM_INLINE("MOV	CX,0x0013");
	ASM_INLINE("MOV	DX,0x000C");
	ASM_INLINE("CALL	unk_8B99D_");
	ASM_INLINE("MOV	AX,0x0005");
	ASM_INLINE("MOV	BX,0x0003");
	ASM_INLINE("MOV	CX,[SI+0x06].W");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALL	unk_8B8D1_");
	ASM_INLINE("MOV	AX,0x0005");
	ASM_INLINE("MOV	BX,0x0003");
	ASM_INLINE("MOV	CX,[SI+0x08].W");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALL	unk_8B92E_");
	ASM_INLINE("JMP	_8C9B7");
ASM_INLINE("_8C95A:");
	ASM_INLINE("CMP	[0x1E08].B,0x00");
	ASM_INLINE("JZ	_8C9B7");
	ASM_INLINE("TEST	[0x0956].W,0x0100");
	ASM_INLINE("JNZ	_8C971");
	ASM_INLINE("TEST	[0x0956].W,0x0400");
	ASM_INLINE("JZ	_8C9B7");
ASM_INLINE("_8C971:");
	ASM_INLINE("MOV	[SI+0x02].W,0x0001");
	ASM_INLINE("MOV	[SI+0x08].W,0x0000");
	ASM_INLINE("MOV	AX,0x0005");
	ASM_INLINE("MOV	BX,0x0003");
	ASM_INLINE("MOV	CX,0x0013");
	ASM_INLINE("MOV	DX,0x000C");
	ASM_INLINE("CALL	unk_8B6D5_");
	ASM_INLINE("MOV	AX,0x0005");
	ASM_INLINE("MOV	BX,0x0003");
	ASM_INLINE("MOV	CX,0x0013");
	ASM_INLINE("MOV	DX,0x000C");
	ASM_INLINE("CALL	unk_8B99D_");
	ASM_INLINE("MOV	AX,0x0005");
	ASM_INLINE("MOV	BX,0x0003");
	ASM_INLINE("MOV	CX,[SI+0x06].W");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALL	unk_8B8D1_");
	ASM_INLINE("MOV	AX,0x0005");
	ASM_INLINE("MOV	BX,0x0003");
	ASM_INLINE("MOV	CX,[SI+0x08].W");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALL	unk_8B92E_");
ASM_INLINE("_8C9B7:");
	ASM_INLINE("TEST	[0x0956].W,0x0002");
	ASM_INLINE("JNZ	_8C9CA");
	ASM_INLINE("TEST	[0x0956].W,0x0004");
	ASM_INLINE("JNZ	_8C9CA");
	ASM_INLINE("JMP	_8CC43");
ASM_INLINE("_8C9CA:");
	ASM_INLINE("MOV	BX,[SI+0x04].W");
	ASM_INLINE("TEST	[BX+0x1E0B].B,0x80");
	ASM_INLINE("JNZ	_8C9D7");
	ASM_INLINE("JMP	_8CC39");
ASM_INLINE("_8C9D7:");
	ASM_INLINE("MOV	AL,0x0A");
	ASM_INLINE("CALLF	sereq_, SEG sereq_");
	ASM_INLINE("MOV	AL,[0x1E07].B");
	ASM_INLINE("CMP	AL,0x03");
	ASM_INLINE("JNZ	_8C9E8");
	ASM_INLINE("JMP	_8CEDA");
ASM_INLINE("_8C9E8:");
	ASM_INLINE("CMP	AL,0x02");
	ASM_INLINE("JNZ	_8C9EF");
	ASM_INLINE("JMP	_8CB0A");
ASM_INLINE("_8C9EF:");
	ASM_INLINE("CMP	AL,0x01");
	ASM_INLINE("JZ	_8C9FA");
	ASM_INLINE("TEST	AL,AL");
	ASM_INLINE("JZ	_8C9FA");
	ASM_INLINE("JMP	_8CEDA");
ASM_INLINE("_8C9FA:");
	ASM_INLINE("MOV	AX,[SI+0x04].W");
	ASM_INLINE("CALL	unk_8B67E_");
	ASM_INLINE("TEST	AX,AX");
	ASM_INLINE("JZ	_8CA0A");
	ASM_INLINE("MOV	[0x1E0A].B,AL");
	ASM_INLINE("JMP	_8CADF");
ASM_INLINE("_8CA0A:");
	ASM_INLINE("CALL	unk_8B6AB_");
	ASM_INLINE("TEST	AX,AX");
	ASM_INLINE("JNZ	_8CA14");
	ASM_INLINE("JMP	_8CA97");
ASM_INLINE("_8CA14:");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,[SI+0x04].W");
	ASM_INLINE("MOV	BX,0x000F");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("MOV	CX,0x0004");
	ASM_INLINE("MOV	BX,0xA751");
	ASM_INLINE("ADD	CX,AX");
	ASM_INLINE("MOV	[BP-0x04].W,CX");
	ASM_INLINE("MOV	[BP-0x02].W,BX");
	ASM_INLINE("POP	AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	[0x1E0A].B,AL");
	ASM_INLINE("MOV	BX,0x001D");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("MOV	DI,AX");
	ASM_INLINE("ADD	DI,0x1E3C");
	ASM_INLINE("MOV	BX,[SI+0x04].W");
	ASM_INLINE("MOV	[DI].B,BL");
	ASM_INLINE("MOV	[DI+0x01].B,0x00");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("MOV	BL,ES:[BX+0x02].B");
	ASM_INLINE("MOV	[DI+0x02].B,BL");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("MOV	BL,ES:[BX+0x03].B");
	ASM_INLINE("MOV	[DI+0x03].B,BL");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("MOV	BL,ES:[BX+0x04].B");
	ASM_INLINE("MOV	[DI+0x04].B,BL");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("JMP	_8CA7B");
ASM_INLINE("_8CA66:");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("ADD	BX,0x0005");
	ASM_INLINE("ADD	BX,CX");
	ASM_INLINE("MOV	AL,ES:[BX].B");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("ADD	BX,0x0005");
	ASM_INLINE("ADD	BX,CX");
	ASM_INLINE("MOV	[BX].B,AL");
	ASM_INLINE("INC	CX");
ASM_INLINE("_8CA7B:");
	ASM_INLINE("CMP	CX,0x0008");
	ASM_INLINE("JL	_8CA66");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("JMP	_8CA8F");
ASM_INLINE("_8CA84:");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("ADD	BX,0x000D");
	ASM_INLINE("ADD	BX,CX");
	ASM_INLINE("MOV	[BX].B,0x00");
	ASM_INLINE("INC	CX");
ASM_INLINE("_8CA8F:");
	ASM_INLINE("CMP	CX,0x0010");
	ASM_INLINE("JL	_8CA84");
	ASM_INLINE("POP	AX");
	ASM_INLINE("JMP	_8CADF");
ASM_INLINE("_8CA97:");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	[SI+0x02].W,0x0001");
	ASM_INLINE("MOV	[SI+0x08].W,0x0000");
	ASM_INLINE("MOV	AX,0x0005");
	ASM_INLINE("MOV	BX,0x0003");
	ASM_INLINE("MOV	CX,0x0013");
	ASM_INLINE("MOV	DX,0x000C");
	ASM_INLINE("CALL	unk_8B6D5_");
	ASM_INLINE("MOV	AX,0x0005");
	ASM_INLINE("MOV	BX,0x0003");
	ASM_INLINE("MOV	CX,0x0013");
	ASM_INLINE("MOV	DX,0x000C");
	ASM_INLINE("CALL	unk_8B99D_");
	ASM_INLINE("MOV	AX,0x0005");
	ASM_INLINE("MOV	BX,0x0003");
	ASM_INLINE("MOV	CX,[SI+0x06].W");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALL	unk_8B8D1_");
	ASM_INLINE("MOV	AX,0x0005");
	ASM_INLINE("MOV	BX,0x0003");
	ASM_INLINE("MOV	CX,[SI+0x08].W");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALL	unk_8B92E_");
	ASM_INLINE("POP	AX");
ASM_INLINE("_8CADF:");
	ASM_INLINE("TEST	AX,AX");
	ASM_INLINE("JNZ	_8CAE6");
	ASM_INLINE("JMP	_8CEDA");
ASM_INLINE("_8CAE6:");
	ASM_INLINE("MOV	AX,SI");
	ASM_INLINE("CALLF	memfree_, SEG memfree_");
	ASM_INLINE("CALLF	task_delete_, SEG task_delete_");
	ASM_INLINE("MOV	AX,stage_select_init_");
	ASM_INLINE("MOV	BX,SEG stage_select_init_");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("CALLF	task_append_, SEG task_append_");
	ASM_INLINE("MOV	AX,0x000A");
	ASM_INLINE("CALLF	task_delete_fade_, SEG task_delete_fade_");
	ASM_INLINE("JMP	_8CEDA");
ASM_INLINE("_8CB0A:");
	ASM_INLINE("CMP	[0x1E08].B,0x00");
	ASM_INLINE("JNZ	_8CB14");
	ASM_INLINE("JMP	_8CBA5");
ASM_INLINE("_8CB14:");
	ASM_INLINE("MOV	AX,[SI+0x04].W");
	ASM_INLINE("CALL	unk_8B67E_");
	ASM_INLINE("TEST	AX,AX");
	ASM_INLINE("JZ	_8CB21");
	ASM_INLINE("JMP	_8CC26");
ASM_INLINE("_8CB21:");
	ASM_INLINE("CALL	unk_8B6D1_");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,[SI+0x04].W");
	ASM_INLINE("MOV	BX,0x000F");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("MOV	CX,0x0004");
	ASM_INLINE("MOV	BX,0xA751");
	ASM_INLINE("ADD	CX,AX");
	ASM_INLINE("MOV	[BP-0x04].W,CX");
	ASM_INLINE("MOV	[BP-0x02].W,BX");
	ASM_INLINE("POP	AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	BX,0x001D");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("MOV	DI,AX");
	ASM_INLINE("ADD	DI,0x1E3C");
	ASM_INLINE("MOV	BX,[SI+0x04].W");
	ASM_INLINE("MOV	[DI].B,BL");
	ASM_INLINE("MOV	[DI+0x01].B,0x00");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("MOV	BL,ES:[BX+0x02].B");
	ASM_INLINE("MOV	[DI+0x02].B,BL");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("MOV	BL,ES:[BX+0x03].B");
	ASM_INLINE("MOV	[DI+0x03].B,BL");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("MOV	BL,ES:[BX+0x04].B");
	ASM_INLINE("MOV	[DI+0x04].B,BL");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("JMP	_8CB88");
ASM_INLINE("_8CB73:");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("ADD	BX,0x0005");
	ASM_INLINE("ADD	BX,CX");
	ASM_INLINE("MOV	AL,ES:[BX].B");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("ADD	BX,0x0005");
	ASM_INLINE("ADD	BX,CX");
	ASM_INLINE("MOV	[BX].B,AL");
	ASM_INLINE("INC	CX");
ASM_INLINE("_8CB88:");
	ASM_INLINE("CMP	CX,0x0008");
	ASM_INLINE("JL	_8CB73");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("JMP	_8CB9C");
ASM_INLINE("_8CB91:");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("ADD	BX,0x000D");
	ASM_INLINE("ADD	BX,CX");
	ASM_INLINE("MOV	[BX].B,0x00");
	ASM_INLINE("INC	CX");
ASM_INLINE("_8CB9C:");
	ASM_INLINE("CMP	CX,0x0010");
	ASM_INLINE("JL	_8CB91");
	ASM_INLINE("POP	AX");
	ASM_INLINE("JMP	_8CC26");
ASM_INLINE("_8CBA5:");
	ASM_INLINE("CALL	unk_8B6D1_");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	AX,[SI+0x04].W");
	ASM_INLINE("MOV	BX,0x000F");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("MOV	CX,0x0004");
	ASM_INLINE("MOV	BX,0xA751");
	ASM_INLINE("ADD	CX,AX");
	ASM_INLINE("MOV	[BP-0x04].W,CX");
	ASM_INLINE("MOV	[BP-0x02].W,BX");
	ASM_INLINE("POP	AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("MOV	BX,0x001D");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("MOV	DI,AX");
	ASM_INLINE("ADD	DI,0x1E3C");
	ASM_INLINE("MOV	BX,[SI+0x04].W");
	ASM_INLINE("MOV	[DI].B,BL");
	ASM_INLINE("MOV	[DI+0x01].B,0x00");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("MOV	BL,ES:[BX+0x02].B");
	ASM_INLINE("MOV	[DI+0x02].B,BL");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("MOV	BL,ES:[BX+0x03].B");
	ASM_INLINE("MOV	[DI+0x03].B,BL");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("MOV	BL,ES:[BX+0x04].B");
	ASM_INLINE("MOV	[DI+0x04].B,BL");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("JMP	_8CC0C");
ASM_INLINE("_8CBF7:");
	ASM_INLINE("LES	BX,[BP-0x04]");
	ASM_INLINE("ADD	BX,0x0005");
	ASM_INLINE("ADD	BX,CX");
	ASM_INLINE("MOV	AL,ES:[BX].B");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("ADD	BX,0x0005");
	ASM_INLINE("ADD	BX,CX");
	ASM_INLINE("MOV	[BX].B,AL");
	ASM_INLINE("INC	CX");
ASM_INLINE("_8CC0C:");
	ASM_INLINE("CMP	CX,0x0008");
	ASM_INLINE("JL	_8CBF7");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("JMP	_8CC20");
ASM_INLINE("_8CC15:");
	ASM_INLINE("MOV	BX,DI");
	ASM_INLINE("ADD	BX,0x000D");
	ASM_INLINE("ADD	BX,CX");
	ASM_INLINE("MOV	[BX].B,0x00");
	ASM_INLINE("INC	CX");
ASM_INLINE("_8CC20:");
	ASM_INLINE("CMP	CX,0x0010");
	ASM_INLINE("JL	_8CC15");
	ASM_INLINE("POP	AX");
ASM_INLINE("_8CC26:");
	ASM_INLINE("MOV	[0x1E0A].B,AL");
	ASM_INLINE("MOV	AX,SI");
	ASM_INLINE("MOV	BX,0x0001");
	ASM_INLINE("CALL	unk_8CEEC_");
	ASM_INLINE("MOV	[SI+0x02].W,0x0002");
	ASM_INLINE("JMP	_8CEDA");
ASM_INLINE("_8CC39:");
	ASM_INLINE("MOV	AL,0x0B");
	ASM_INLINE("CALLF	sereq_, SEG sereq_");
	ASM_INLINE("JMP	_8CEDA");
ASM_INLINE("_8CC43:");
	ASM_INLINE("TEST	[0x0956].W,0x0008");
	ASM_INLINE("JNZ	_8CC4E");
	ASM_INLINE("JMP	_8CEDA");
ASM_INLINE("_8CC4E:");
	ASM_INLINE("MOV	AL,[0x1E07].B");
	ASM_INLINE("CMP	AL,0x03");
	ASM_INLINE("JZ	_8CC6A");
	ASM_INLINE("CMP	AL,0x02");
	ASM_INLINE("JZ	_8CC63");
	ASM_INLINE("CMP	AL,0x01");
	ASM_INLINE("JZ	_8CC6A");
	ASM_INLINE("TEST	AL,AL");
	ASM_INLINE("JZ	_8CC6A");
	ASM_INLINE("JMP	_8CC6A");
ASM_INLINE("_8CC63:");
	ASM_INLINE("MOV	AX,SI");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("CALL	unk_8CEEC_");
ASM_INLINE("_8CC6A:");
	ASM_INLINE("MOV	AL,0x0B");
	ASM_INLINE("CALLF	sereq_, SEG sereq_");
	ASM_INLINE("MOV	AX,SI");
	ASM_INLINE("CALLF	memfree_, SEG memfree_");
	ASM_INLINE("CALLF	task_delete_, SEG task_delete_");
	ASM_INLINE("MOV	AX,menu_init_");
	ASM_INLINE("MOV	BX,SEG menu_init_");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("CALLF	task_append_, SEG task_append_");
	ASM_INLINE("MOV	AX,0x000A");
	ASM_INLINE("CALLF	task_delete_fade_, SEG task_delete_fade_");
	ASM_INLINE("JMP	_8CEDA");
ASM_INLINE("_8CC95:");
	ASM_INLINE("TEST	[0x0956].W,0x0100");
	ASM_INLINE("JZ	_8CCCC");
	ASM_INLINE("MOV	AL,0x0C");
	ASM_INLINE("CALLF	sereq_, SEG sereq_");
	ASM_INLINE("CMP	[SI+0x06].W,0x0000");
	ASM_INLINE("JLE	_8CD01");
	ASM_INLINE("MOV	AX,0x0005");
	ASM_INLINE("MOV	BX,0x0003");
	ASM_INLINE("MOV	CX,[SI+0x06].W");
	ASM_INLINE("XOR	DX,DX");
	ASM_INLINE("CALL	unk_8B8D1_");
	ASM_INLINE("DEC	[SI+0x06].W");
	ASM_INLINE("MOV	AX,0x0005");
	ASM_INLINE("MOV	BX,0x0003");
	ASM_INLINE("MOV	CX,[SI+0x06].W");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALL	unk_8B8D1_");
	ASM_INLINE("JMP	_8CD01");
ASM_INLINE("_8CCCC:");
	ASM_INLINE("TEST	[0x0956].W,0x0400");
	ASM_INLINE("JZ	_8CD01");
	ASM_INLINE("MOV	AL,0x0C");
	ASM_INLINE("CALLF	sereq_, SEG sereq_");
	ASM_INLINE("CMP	[SI+0x06].W,0x0007");
	ASM_INLINE("JGE	_8CD01");
	ASM_INLINE("MOV	AX,0x0005");
	ASM_INLINE("MOV	BX,0x0003");
	ASM_INLINE("MOV	CX,[SI+0x06].W");
	ASM_INLINE("XOR	DX,DX");
	ASM_INLINE("CALL	unk_8B8D1_");
	ASM_INLINE("INC	[SI+0x06].W");
	ASM_INLINE("MOV	AX,0x0005");
	ASM_INLINE("MOV	BX,0x0003");
	ASM_INLINE("MOV	CX,[SI+0x06].W");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALL	unk_8B8D1_");
ASM_INLINE("_8CD01:");
	ASM_INLINE("TEST	[0x0956].W,0x0800");
	ASM_INLINE("JZ	_8CD38");
	ASM_INLINE("MOV	AL,0x0C");
	ASM_INLINE("CALLF	sereq_, SEG sereq_");
	ASM_INLINE("CMP	[SI+0x08].W,0x0000");
	ASM_INLINE("JLE	_8CD6D");
	ASM_INLINE("MOV	AX,0x0005");
	ASM_INLINE("MOV	BX,0x0003");
	ASM_INLINE("MOV	CX,[SI+0x08].W");
	ASM_INLINE("XOR	DX,DX");
	ASM_INLINE("CALL	unk_8B92E_");
	ASM_INLINE("DEC	[SI+0x08].W");
	ASM_INLINE("MOV	AX,0x0005");
	ASM_INLINE("MOV	BX,0x0003");
	ASM_INLINE("MOV	CX,[SI+0x08].W");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALL	unk_8B92E_");
	ASM_INLINE("JMP	_8CD6D");
ASM_INLINE("_8CD38:");
	ASM_INLINE("TEST	[0x0956].W,0x0200");
	ASM_INLINE("JZ	_8CD6D");
	ASM_INLINE("MOV	AL,0x0C");
	ASM_INLINE("CALLF	sereq_, SEG sereq_");
	ASM_INLINE("CMP	[SI+0x08].W,0x0001");
	ASM_INLINE("JGE	_8CD6D");
	ASM_INLINE("MOV	AX,0x0005");
	ASM_INLINE("MOV	BX,0x0003");
	ASM_INLINE("MOV	CX,[SI+0x08].W");
	ASM_INLINE("XOR	DX,DX");
	ASM_INLINE("CALL	unk_8B92E_");
	ASM_INLINE("INC	[SI+0x08].W");
	ASM_INLINE("MOV	AX,0x0005");
	ASM_INLINE("MOV	BX,0x0003");
	ASM_INLINE("MOV	CX,[SI+0x08].W");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALL	unk_8B92E_");
ASM_INLINE("_8CD6D:");
	ASM_INLINE("TEST	[0x0956].W,0x0004");
	ASM_INLINE("JNZ	_8CD78");
	ASM_INLINE("JMP	_8CE50");
ASM_INLINE("_8CD78:");
	ASM_INLINE("MOV	AL,0x0A");
	ASM_INLINE("CALLF	sereq_, SEG sereq_");
	ASM_INLINE("CMP	[SI+0x08].W,0x0000");
	ASM_INLINE("JZ	_8CDC7");
	ASM_INLINE("MOV	AX,[SI+0x06].W");
	ASM_INLINE("MOV	BX,0x001D");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("MOV	BX,AX");
	ASM_INLINE("ADD	BX,0x001D");
	ASM_INLINE("MOV	[BX+0x1E3C].B,0xFF");
	ASM_INLINE("MOV	AX,0x0005");
	ASM_INLINE("MOV	BX,0x0003");
	ASM_INLINE("MOV	CX,0x0013");
	ASM_INLINE("MOV	DX,0x000C");
	ASM_INLINE("CALL	unk_8B99D_");
	ASM_INLINE("MOV	AX,0x0005");
	ASM_INLINE("MOV	BX,0x0003");
	ASM_INLINE("MOV	CX,[SI+0x06].W");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALL	unk_8B8D1_");
	ASM_INLINE("MOV	AX,0x0005");
	ASM_INLINE("MOV	BX,0x0003");
	ASM_INLINE("MOV	CX,[SI+0x08].W");
	ASM_INLINE("MOV	DX,0x0001");
	ASM_INLINE("CALL	unk_8B92E_");
	ASM_INLINE("JMP	_8CEDA");
ASM_INLINE("_8CDC7:");
	ASM_INLINE("MOV	AL,[0x1E07].B");
	ASM_INLINE("CMP	AL,0x03");
	ASM_INLINE("JNZ	_8CDD1");
	ASM_INLINE("JMP	_8CEDA");
ASM_INLINE("_8CDD1:");
	ASM_INLINE("CMP	AL,0x02");
	ASM_INLINE("JZ	_8CE22");
	ASM_INLINE("CMP	AL,0x01");
	ASM_INLINE("JZ	_8CDE0");
	ASM_INLINE("TEST	AL,AL");
	ASM_INLINE("JZ	_8CDE0");
	ASM_INLINE("JMP	_8CEDA");
ASM_INLINE("_8CDE0:");
	ASM_INLINE("MOV	AX,[SI+0x06].W");
	ASM_INLINE("MOV	BX,0x001D");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("MOV	BX,AX");
	ASM_INLINE("ADD	BX,0x001D");
	ASM_INLINE("CMP	[BX+0x1E3C].B,0xFF");
	ASM_INLINE("JNZ	_8CDF7");
	ASM_INLINE("JMP	_8CEDA");
ASM_INLINE("_8CDF7:");
	ASM_INLINE("MOV	AX,[SI+0x06].W");
	ASM_INLINE("INC	AX");
	ASM_INLINE("MOV	[0x1E0A].B,AL");
	ASM_INLINE("MOV	AX,SI");
	ASM_INLINE("CALLF	memfree_, SEG memfree_");
	ASM_INLINE("CALLF	task_delete_, SEG task_delete_");
	ASM_INLINE("MOV	AX,stage_select_init_");
	ASM_INLINE("MOV	BX,SEG stage_select_init_");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("CALLF	task_append_, SEG task_append_");
	ASM_INLINE("MOV	AX,0x000A");
	ASM_INLINE("CALLF	task_delete_fade_, SEG task_delete_fade_");
	ASM_INLINE("JMP	_8CEDA");
ASM_INLINE("_8CE22:");
	ASM_INLINE("MOV	AX,[SI+0x06].W");
	ASM_INLINE("MOV	BX,0x001D");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("MOV	BX,AX");
	ASM_INLINE("ADD	BX,0x001D");
	ASM_INLINE("CMP	[BX+0x1E3C].B,0xFF");
	ASM_INLINE("JNZ	_8CE39");
	ASM_INLINE("JMP	_8CEDA");
ASM_INLINE("_8CE39:");
	ASM_INLINE("MOV	AX,[SI+0x06].W");
	ASM_INLINE("INC	AX");
	ASM_INLINE("MOV	[0x1E0A].B,AL");
	ASM_INLINE("MOV	AX,SI");
	ASM_INLINE("MOV	BX,0x0001");
	ASM_INLINE("CALL	unk_8CEEC_");
	ASM_INLINE("MOV	[SI+0x02].W,0x0002");
	ASM_INLINE("JMP	_8CEDA");
ASM_INLINE("_8CE50:");
	ASM_INLINE("TEST	[0x0956].W,0x0008");
	ASM_INLINE("JNZ	_8CE5B");
	ASM_INLINE("JMP	_8CEDA");
ASM_INLINE("_8CE5B:");
	ASM_INLINE("MOV	AL,0x0B");
	ASM_INLINE("CALLF	sereq_, SEG sereq_");
	ASM_INLINE("MOV	[SI+0x02].W,0x0000");
	ASM_INLINE("MOV	BX,0x0000");
	ASM_INLINE("MOV	AX,0xB9CF");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("PUSH	BX");
	ASM_INLINE("MOV	AX,0x0001");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("PUSH	AX");
	ASM_INLINE("XOR	AX,AX");
	ASM_INLINE("XOR	BX,BX");
	ASM_INLINE("MOV	CX,0x001C");
	ASM_INLINE("MOV	DX,0x0012");
	ASM_INLINE("CALLF	font_put2XY_, SEG font_put2XY_");
	ASM_INLINE("ADD	SP,0x000A");
	ASM_INLINE("CALL	unk_8BC45_");
	ASM_INLINE("MOV	AX,[SI+0x04].W");
	ASM_INLINE("CALL	unk_8BECE_");
	ASM_INLINE("MOV	AX,[SI+0x04].W");
	ASM_INLINE("CALL	unk_8C070_");
	ASM_INLINE("JMP	_8CEDA");
ASM_INLINE("_8CE9C:");
	ASM_INLINE("TEST	[0x0956].W,0x0008");
	ASM_INLINE("JZ	_8CEB3");
	ASM_INLINE("MOV	AX,SI");
	ASM_INLINE("MOV	BX,0x0002");
	ASM_INLINE("CALL	unk_8CEEC_");
	ASM_INLINE("MOV	[SI+0x02].W,0x0000");
	ASM_INLINE("JMP	_8CEDA");
ASM_INLINE("_8CEB3:");
	ASM_INLINE("CMP	[SI+0x0A].W,0x0000");
	ASM_INLINE("JZ	_8CEDA");
	ASM_INLINE("MOV	AX,SI");
	ASM_INLINE("CALLF	memfree_, SEG memfree_");
	ASM_INLINE("CALLF	task_delete_, SEG task_delete_");
	ASM_INLINE("MOV	AX,m_game_init_");
	ASM_INLINE("MOV	BX,SEG m_game_init_");
	ASM_INLINE("XOR	CX,CX");
	ASM_INLINE("CALLF	task_append_, SEG task_append_");
	ASM_INLINE("MOV	AX,0x000A");
	ASM_INLINE("CALLF	task_delete_fade_, SEG task_delete_fade_");
ASM_INLINE("_8CEDA:");
	ASM_INLINE("MOV	AX,SI");
	ASM_INLINE("CALL	unk_8C69D_");
	ASM_INLINE("MOV	AX,SI");
	ASM_INLINE("CALL	unk_8CF48_");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
	ASM_INLINE("MOV	SP,BP");
	ASM_INLINE("POP	BP");
}

/*0752*/
static u8 unisel_data2[] = {
	0x01, 0x01, 0xA8, 0xC0,
	0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00,
	0x04, 0x00,
};

static void near unk_8CEEC(struct UniselWork *work, u16 idx)
{
/*	u8 *ptr;

	u8 unisel_data2[] = {
		0x01, 0x01, 0xA8, 0xC0,
		0x00, 0x00, 0x00, 0x00,
		0x00, 0x00, 0x00, 0x00,
		0x00, 0x00, 0x00, 0x00,
		0x00, 0x00, 0x00, 0x00,
		0x04, 0x00,
	};

	unisel_data2[4] = idx;

	switch(idx)
	{
		default:
		case 0:
		{
			break;
		}
		case 1:
		{
			ptr = (SAVE_DATA_START[0x0A] * 0x1D + (SAVE_DATA_START + 0x3C));
			unisel_data2[5] = ptr[0];
			unisel_data2[6] = ptr[2];
			unisel_data2[7] = ptr[3];
		}
		case 2:
		{
			break;
		}
	}
	ip_w(unisel_data2);*/

	ip_w; //Force include
	ASM_INLINE("PUSH	BP");
	ASM_INLINE("MOV	BP,SP");
	ASM_INLINE("SUB	SP,0x0016");
	ASM_INLINE("PUSH	CX");
	ASM_INLINE("PUSH	DX");
	ASM_INLINE("PUSH	SI");
	ASM_INLINE("PUSH	DI");
	ASM_INLINE("LEA	DI,[BP-0x16].B");
	ASM_INLINE("MOV	SI,unisel_data2_");
	ASM_INLINE("MOV	CX,0x0016");
	ASM_INLINE("PUSH	DS");
	ASM_INLINE("POP	ES");
	ASM_INLINE("CLD");
	ASM_INLINE("REP MOVSB");
	ASM_INLINE("MOV	[BP-0x12].B,BL");
	ASM_INLINE("CMP	BX,0x0002");
	ASM_INLINE("JZ	_8CF38");
	ASM_INLINE("CMP	BX,0x0001");
	ASM_INLINE("JZ	_8CF17");
	ASM_INLINE("TEST	BX,BX");
	ASM_INLINE("JZ	_8CF38");
	ASM_INLINE("JMP	_8CF38");
ASM_INLINE("_8CF17:");
	ASM_INLINE("MOV	AL,[0x1E0A].B");
	ASM_INLINE("XOR	AH,AH");
	ASM_INLINE("MOV	BX,0x001D");
	ASM_INLINE("MUL	BX");
	ASM_INLINE("MOV	BX,AX");
	ASM_INLINE("ADD	BX,0x1E3C");
	ASM_INLINE("MOV	AL,[BX].B");
	ASM_INLINE("MOV	[BP-0x11].B,AL");
	ASM_INLINE("MOV	AL,[BX+0x02].B");
	ASM_INLINE("MOV	[BP-0x10].B,AL");
	ASM_INLINE("MOV	AL,[BX+0x03].B");
	ASM_INLINE("MOV	[BP-0x0F].B,AL");
ASM_INLINE("_8CF38:");
	ASM_INLINE("LEA	AX,[BP-0x16].B");
	ASM_INLINE("CALLF	ip_w_, SEG ip_w_");
	ASM_INLINE("POP	DI");
	ASM_INLINE("POP	SI");
	ASM_INLINE("POP	DX");
	ASM_INLINE("POP	CX");
	ASM_INLINE("MOV	SP,BP");
	ASM_INLINE("POP	BP");
}

/*0768*/
/*static u8 unisel_data3[] = {
	0x01, 0x01, 0xA8, 0xC0,
	0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00,
	0x04, 0x00 
};*/

static void near unk_8CF48(struct UniselWork *work)
{
	u8 *ptr;
	u8 unisel_data3[] = {
		0x01, 0x01, 0xA8, 0xC0,
		0x00, 0x00, 0x00, 0x00,
		0x00, 0x00, 0x00, 0x00,
		0x00, 0x00, 0x00, 0x00,
		0x00, 0x00, 0x00, 0x00,
		0x04, 0x00 
	};

	if(ip_r(unisel_data3) == 0)
	{
		switch(unisel_data3[4])
		{
			case 0:
			{
				sereq(0xb);
				memfree(work);
				task_delete();
				task_append((task_pointer)menu_init, 0);
				task_delete_fade(10);
				break;
			}
			case 1:
			{
				ptr = SAVE_DATA_START + 0x3C;
				ptr[0] = unisel_data3[5];
				ptr[2] = unisel_data3[6];
				ptr[3] = unisel_data3[7];
				work->unkA = 1;
				break;
			}
			case 2:
			{
				work->unkA = 0;
				break;
			}
		}
	}
}
